### ISSUE TITLE
Desaggregate industry demand

### ISSUE THREAD

**Issue by birgits** [openego/eGon-data#1001]
I realised that the data in demand.egon_osm_ind_load_curves and demand.egon_sites_ind_load_curves is given per bus ID. In eDisGo we need the data per OSM area respectively industrial site. @IlkaCu and I discussed that in the process of determining the load time series an intermediate table (or two, one for OSM areas and one for sites) could be created giving the load curve per OSM area / industrial site. This new table should contain the site ID or geometry of the industrial load, the load time series and the bus ID (for easy filtering).

**Comment by nesnoj** [comment]
@IlkaCu Could you please create a PR for your branch?

**Comment by nesnoj** [comment]
> @IlkaCu Could you please create a PR for your branch?

did it
