### ISSUE TITLE
Let's do the CI branch again

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#1017]
Due to the recent issues with the last, newly created `continuous-integration/run-everything-over-the-weekend-2022-10-10` branch, we're creating a a new CI branch. Since the last one is rather recent the transition to the new one will not proceed according to the regular workflow, but will instead follow the TODOs below:

  - [x] @IlkaCu merges her pending changes into `dev`
  - [x] @gnn creates the [new CI](https://github.com/openego/eGon-data/tree/continuous-integration/run-everything-2022-11-01)
  - [x] @AmeliaNadal merges her pending changes into the new CI
  - [x] @khelfen  merges his pending changes into the new CI
  - [x] @nailend & @birgits merges their pending changes into the new CI
  - [x] @ClaraBuettner merge their pending changes into the new CI
  - [x] the new CI gets started on one of the newly rented servers 
  - [x] the value of `max_connections` is checked using a command mentioned in a [comment](https://github.com/openego/eGon-data/issues/799#issuecomment-1293459470) of [issue #799](https://github.com/openego/eGon-data/issues/799)

Please tick your box once your done with your TODO. And maybe ping the person responsible for your successor TODO via Element.

**Comment by gnn** [comment]
Since the run hasn't been a "weekend run" for quite some time now, I took the liberty of shortening the name. The new CI branch is called [`continuous-integration/run-everything-2022-11-01`](https://github.com/openego/eGon-data/tree/continuous-integration/run-everything-2022-11-01).

**Comment by nesnoj** [comment]
ping!

**Comment by nailend** [comment]
@ClaraBuettner would you like to merge your stuff before me. I have to leave the office in 15 mins but would do this later when I come home. Approx. 10 pm

**Comment by ClaraBuettner** [comment]
> @ClaraBuettner would you like to merge your stuff before me? I have to leave the office in 15 mins but would do this later when I come home. Approx. 10 pm

Yes, we can change the order. I will do this in the description and write you when I'm done.

**Comment by khelfen** [comment]
I'm done as well @ClaraBuettner

**Comment by ClaraBuettner** [comment]
I'm done as well @nailend

**Comment by gnn** [comment]
Running.
```sql
SELECT name, setting, short_desc, vartype, max_val, boot_val, reset_val, pending_restart
FROM pg_settings
WHERE name = 'max_connections';
```

outputs:

|      name       | setting |                     short_desc                     | vartype | max_val | boot_val | reset_val | pending_restart
|-----------------|---------|----------------------------------------------------|---------|---------|----------|-----------|-----------------
|max_connections | 2048    | Sets the maximum number of concurrent connections. | integer | 262143  | 100      | 2048      | f

**Comment by nesnoj** [comment]
`osm.to-postgres` in 2h20m ?? Woohoo! :racing_car:

**Comment by nesnoj** [comment]
`FATAL:  sorry, too many clients already` o_O

**Comment by ClaraBuettner** [comment]
We discussed about creating a new CI-branch which can run in parallel on the server in Flensburg. If you're not against, I will create a new branch from https://github.com/openego/eGon-data/tree/continuous-integration/run-everything-2022-11-01 , to avoid that all features which are already in that don't have to be merged again. 

We would like to start the run on Friday.

**Comment by nesnoj** [comment]
I'm done too.
@IlkaCu my load area branch #1020 already contains your branch [`features/#1001-desaggregate-industry-demands`](https://github.com/openego/eGon-data/tree/features/%231001-desaggregate-industry-demands) so if you don't have any further local changes, you can skip this one.

**Comment by nesnoj** [comment]
@ClaraBuettner is your recent manual quickfix for [these lines](https://github.com/openego/eGon-data/blob/90d16d969070c2dbc09e4ccb107b9c4c798e8f61/src/egon/data/datasets/heat_demand_timeseries/__init__.py#L365-L368) required again?

**Comment by ClaraBuettner** [comment]
> @ClaraBuettner is your recent manual quickfix for [these lines](https://github.com/openego/eGon-data/blob/90d16d969070c2dbc09e4ccb107b9c4c798e8f61/src/egon/data/datasets/heat_demand_timeseries/__init__.py#L365-L368) required again?

Yes, I think is is needed again. I will add this on a branch an merge it into the newest CI.

**Comment by nesnoj** [comment]
:space_invader: :space_invader: :space_invader: Launched :space_invader: :space_invader: :space_invader:
