### ISSUE TITLE
Can the "feature/dlr_tests" branch be deleted?

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#102]
The branch was dealing with working without docker, which is fixed by now. Nonetheless, there might be code on the branch which is still of interest to others and this is something which the authors are most qualified to decide. If there's no code on the branch which you want do keep around, just post a note here and I'll delete it. Or you can do it directly, whichever you prefer.

**Comment by AmeliaNadal** [comment]
I do not think that there might be code on the branch which is still of interest to others. However, could I keep this branch to do some personal tests?
If you think that it is problematic to have this "unnecessary" (for the community) branch, I could delete it, but I would rather keep it, if it is fine to you.

**Comment by AmeliaNadal** [comment]
This branch has been deleted.
