### ISSUE TITLE
Installation problem caused by psycopg2-2.8.6

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#103]
The installation of eGon-data in a fresh virtual environment failed with this error message: 

```
Collecting psycopg2
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/ilka/virtuelle_Umgebungen/test_DR/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p651s6ig/psycopg2_3248e9c1e2004cf98df66004c471784d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p651s6ig/psycopg2_3248e9c1e2004cf98df66004c471784d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xxa5__c8
         cwd: /tmp/pip-install-p651s6ig/psycopg2_3248e9c1e2004cf98df66004c471784d/
    Complete output (7 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-xxa5__c8/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-xxa5__c8/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-xxa5__c8/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-xxa5__c8/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-xxa5__c8/psycopg2.egg-info/SOURCES.txt'
    Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\n'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I tried to set the psycopg2 version to 2.8.5 in setup.py but in my case this didn't help.

**Comment by gnn** [comment]
The `psycopg2` installation should be fixed with a `sudo apt install libpq-dev`. Could you try out and confirm? If the fix works, I'll add the system dependency to the installation instructions and close this issue.

**Comment by ClaraBuettner** [comment]
This solves the problem for me. 
But I had to uninstall pgadmin4 and re-install it in a virtual environment because pgadmin4 and libpq-dev needed different versions of libpq5. I can document which steps I needed to do this if others also want to use pgadmin4.

**Comment by IlkaCu** [comment]
> This solves the problem for me.
> But I had to uninstall pgadmin4 and re-install it in a virtual environment because pgadmin4 and libpq-dev needed different versions of libpq5. I can document which steps I needed to do this if others also want to use pgadmin4.

That would help me a lot, I also experienced this problem: 

`Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libpq-dev : Hängt ab von: libpq5 (= 10.15-0ubuntu0.18.04.1) aber 13.1-1.pgdg18.04+1 soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
`

**Comment by ClaraBuettner** [comment]
Here is what I did: 

Install libpg5=10.15-0ubuntu0.18.04.1 even if it removes pgadmin4 

Install pgAdmin4 in virtual environment:

* create subdirectories
** `sudo mkdir /var/lib/pgadmin`
** `sudo mkdir /var/log/pgadmin`

* set permissions to these folders
** `sudo chown $USER /var/lib/pgadmin`
**` sudo chown $USER /var/log/pgadmin`

* create virtual environment 
** `virtualenv pgadmin4 --clear -p python3.7`

* activate virtual environment 
** `source pgadmin4/bin/activate`

* install pgadmin4
** `pip install pgadmin4 `

* start pgadmin4
** `pgadmin4`
** set email address and password in the initial start
** open http://127.0.0.1:5050 in your browser

Use pgadmin4:

* activate virtual environment 
** `source pgadmin4/bin/activate`

* start pgadmin4
** `pgadmin4`
** open http://127.0.0.1:5050 in your browser

**Comment by gnn** [comment]
Since `libpq-dev` is a hard system dependency for `psycopg2` and there's no way around having it installed I moved the `pgAdmin4` discussion to issue #105, so I can close this one, once `libpq-dev` is noted as a system dependency.
