### ISSUE TITLE
CH4 demands TS abroad eGon2035

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#1038]
In  eGon2035, the CH4 demands TS abroad seem to not have the right number of time steps. This should be corrected.
The changes would probably occur in src/egon/data/datasets/gas_neighbours/eGon2035.py  and affect the task gas_neighbours.eGon2035.tyndp-gas-demand which has no other task depending on (except gas_neighbours.eGon100RE.insert-gas-neigbours-eGon100RE).

**Comment by nesnoj** [comment]
Another good reason for #928 ;)

**Comment by IlkaCu** [comment]
Could this be related to old p-e-s results with a lower temporal resolution? How many time steps do the times series abroad have?

**Comment by AmeliaNadal** [comment]
This issue was related to old p-e-s results with a lower temporal resolution and does not occur anymore with the new p-e-s results.
