### ISSUE TITLE
PV rooftop fails in SH mode

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#1055]
In `dev` here you try to obtain the weather cells:
https://github.com/openego/eGon-data/blob/4a2d0168ccd3deca5d8333ba1442b5b47ada90ab/src/egon/data/datasets/power_plants/pv_rooftop.py#L247-L255

This apparently works for DE but in SH mode the cfg is overwritten:
https://github.com/openego/eGon-data/blob/4a2d0168ccd3deca5d8333ba1442b5b47ada90ab/src/egon/data/datasets/power_plants/pv_rooftop.py#L163-L164
which results in a key error later. This second assignment does not exist in the CI, why?

**Comment by nesnoj** [comment]
Seems that it has been added in 4a2d0168ccd3deca5d8333ba1442b5b47ada90ab

**Comment by khelfen** [comment]
> Seems that it has been added in [4a2d016](https://github.com/openego/eGon-data/commit/4a2d0168ccd3deca5d8333ba1442b5b47ada90ab)

Ah yes, you are right! Thank you for the fast fix! :D
