### ISSUE TITLE
Start next CI run for Germany

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#1057]
We want to start another CI run for Germany 
Please tick as soon as you are done with your open implementations/merges: 

- [x] @gnn  - one small issue
- [x] @ClaraBuettner  - set another dependency in Julians branch 
- [x] @birgits  - merge branches
- [x] @IlkaCu  - check for problems in industrial demands distribution
- [x] @IlkaCu  - Include low flex scenario 
- [x] @khelfen - DSM desaggregation
- [ ] @nesnoj  - MaStR data 
   
Deadline: Next Friday, Jonathan starts the run as soon as he is done 
Current CI branch: continuous-integration/run-everything-2022-11-10

**Comment by nesnoj** [comment]
For sake of performance, I'd go for the new instance, d'accord?
Please backup stuff you wanna keep in advance.

**Comment by khelfen** [comment]
Hey :) I would also add my dsm desaggregation if that's okay (?)

**Comment by khelfen** [comment]
Is there a merge order this time or can I already merge my changes into the Ci? And the deadline is today or next weeks friday?

**Comment by nesnoj** [comment]
> Is there a merge order this time or can I already merge my changes into the CI? And the deadline is today or next weeks friday?

It's today but I'm not sute whether everybody can make it? From my point of view go ahead merging..

**Comment by ClaraBuettner** [comment]
> Is there a merge order this time or can I already merge my changes into the CI? And the deadline is today or next weeks friday?

Oh, I'm sorry if there was an order, I already did my changes on Julians branch, and I also merged another fix into that CI yesterday. But that one didn't effected other datasets.

**Comment by nesnoj** [comment]
Anything up to come @gnn @IlkaCu ?

**Comment by gnn** [comment]
Sorry for the delay. Done now.

**Comment by nesnoj** [comment]
> Sorry for the delay. Done now.

The run had been already started. But it will be included in the parallel one starting tonight.

**Comment by nesnoj** [comment]
@IlkaCu According to your commits it seems that you integrated the lowflex scenario on Friday, so I ticked the checkbox above.

@ClaraBuettner Task `heat_demand_timeseries.district-heating` failed yesterday, could you please take care?

**Comment by nesnoj** [comment]
Hetzner run finished.
Total duration: `~8d15h`
