### ISSUE TITLE
Tests do not run on macOS with Python 3.7 & 3.8

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#106]
Tests with Python 3.7 & 3.8 are currently [deactiivated](https://github.com/openego/eGon-data/blob/5b4a14303170f6443bb27e6969db278fb3f71c11/.github/workflows/build.yml#L33-L37).

Re-activate to see why it is failing.

As a hint, when we used Travis, some additional stuff got installed on macOS, see [here](https://github.com/openego/eGon-data/blob/5b4a14303170f6443bb27e6969db278fb3f71c11/.travis.yml#L48-L57)

**Comment by nesnoj** [comment]
Won't tackle this, cf. https://github.com/openego/eGon-data/issues/42#issuecomment-1276334113
