### ISSUE TITLE
Integrate electrical load curves from demandregio

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#109]
Demandregio's disaggregator will be used to create electrical load curves for industry and CTS. 
We need to decide: 
* if we want to integrate load cureves on nuts3-level or directly in the highest resolution 
* how we disaggregate the curves within one nuts3-region (linear to overall demand?) 
* how the table structure should look like 
* if we want to have one curve per nuts3 region for each wz or only for CTS and industry (this might be needed for dsm?)
This task also depends on the decision of using point data for industrial sites.

**Comment by IlkaCu** [comment]
After a discussion with @ClaraBuettner we suggest to avoid storing time series for cts and industry on the nuts-3 or 100x100m level in our data base. We would instead store the normalized load time series per sector (standard load profiles from DemandRegio) to create the resulting curves ad hoc.
