### ISSUE TITLE
Carrier naming land transport EV within grid.egon_etrago_load

### ISSUE THREAD

**Issue by khelfen** [openego/eGon-data#1105]
@nesnoj within the table  `grid.egon_etrago_load` there are two carriers for EV at the moment. `land transport EV` and `land_transport_EV`. Is there any reasoning for that? Should we change `land transport EV` to `land_transport_EV` as at the moment it is the only carrier with whitespaces instead of underscores?

**Comment by nesnoj** [comment]
Hey @khelfen, I used `land transport EV` as it is [used in p-e-s as well](https://github.com/openego/pypsa-eur-sec/blob/6b099a7372c3510ae6bef8df722ab201c7a044a6/scripts/prepare_sector_network.py#L1323) and I wanted to be in line with its carrier naming (which was also requested by @ClaraBuettner earlier). But I can alter this if needed.
Moreover, I used further carriers with spaces such as `BEV charger`. Am I to adjust all of them?

@IlkaCu This was discussed yesterday but unfortunately I wasn't able to take part. Shall I change it?

**Comment by khelfen** [comment]
> Hey @khelfen, I used `land transport EV` as it is [used in p-e-s as well](https://github.com/openego/pypsa-eur-sec/blob/6b099a7372c3510ae6bef8df722ab201c7a044a6/scripts/prepare_sector_network.py#L1323) and I wanted to be in line with its carrier naming (which was also requested by @ClaraBuettner earlier). But I can alter this if needed. Moreover, I used further carriers with spaces such as `BEV charger`. Am I to adjust all of them?
> 
> @IlkaCu This was discussed yesterday but unfortunately I wasn't able to take part. Shall I change it?

In that case I'm just wondering where does `land_transport_EV` come from? I couldn't find it mentioned in the code base anywhere. TBH `land transport EV` is fine with me (having your reasoning in mind) but the double naming is confusing :thinking:

**Comment by nesnoj** [comment]
> In that case I'm just wondering where does `land_transport_EV` come from? I couldn't find it mentioned in the code base anywhere. TBH `land transport EV` is fine with me (having your reasoning in mind) but the double naming is confusing thinking

I found some replacements for the p-e-s components [here](https://github.com/openego/eGon-data/blob/7a7ea3433fb2aca761b29f9ecffe38003e9e6cbc/src/egon/data/datasets/pypsaeursec/__init__.py) (search for `carrier.str.replace(" ", "_")`) but this only covers neighboring countries, doesn't it?
@IlkaCu @ClaraBuettner Please drop us a note if you have more information or a clear opinion how to proceed.

**Comment by nesnoj** [comment]
From today's webco: I will rename the carriers

**Comment by khelfen** [comment]
> From today's webco: I will rename the carriers

@mltja FYI

**Comment by nesnoj** [comment]
I checked the DB tables and it depends on the scnenario:
- `eGon2035`: white spaces
- `eGon2035_lowflex`: white spaces
- `eGon100RE`: white spaces (my components) and underscores (only 14, I guess they come from p-e-s)
- `eGon100RE_lowflex`: white spaces
