### ISSUE TITLE
include pgrouting extension

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGon-data#115]
For #4 it is necessary to have the extension pgrouting. Unfortunately, so far I was not able to get this extension working. osmTGmod throws an error stating that the pgrouting.control file is missing in the extensions folder of postgresql (/usr/share/postgresql/12/extension).

I tried numerous things. Withing egon-data I tried out 31af5bdbf9b3b7e3d58a26f31add64b425793650

Furthermore I tried this: https://docs.pgrouting.org/3.0/en/pgRouting-installation.html
It is failing because boost was not available when executing the cmake command. Installing boost did not work either.

I also found this: https://github.com/pgRouting/docker-pgrouting
which so far did not lead to anything really. To change our docker to this image seems to be most promising to me though right now.

**Comment by gplssm** [comment]
Thanks for researching on that!

From my point of view, we could simply switch our docker container from https://github.com/openego/eGon-data/blob/e53c7c292ef39dc81133321f5679527f23fcd81e/src/egon/data/airflow/docker-compose.yml#L4 to https://github.com/pgRouting/docker-pgrouting/tree/master/12-3.0-3.1.1

Maybe we have to a command for installing pgrouting inside the container in the Dockerfile as we do [for postgis](https://github.com/openego/eGon-data/blob/e53c7c292ef39dc81133321f5679527f23fcd81e/src/egon/data/airflow/Dockerfile.postgis#L4).

**Comment by gnn** [comment]
> I tried numerous things. Withing egon-data I tried out [31af5bd](https://github.com/openego/eGon-data/commit/31af5bdbf9b3b7e3d58a26f31add64b425793650)

And what was the result? Because after installing `postgresql-12-pgrouting`, I was able to install the `pgrouting` extension without an error and the `/usr/share/postgresql/12/extension/pgrouting.control` file is also present. If you want to install the `postgresql-12-pgrouting` package into your currently running container, you can do so by running
```sh
docker exec -it egon-data-local-database /bin/bash
```
which will drop you into a shell inside the docker container, where you can do `apt install postgresql-12-pgrouting`. After this, I was able to `CREATE EXTENSION pgrouting;` without an error.
Running `apt install postgresql-12-pgrouting` might give you an error about not being able to connect to the repository. If this happens, create the file `/etc/docker/daemon.json` with the following contents (or add them if the file already exists):
```json
{
  "dns": ["208.67.222.222","208.67.220.220"]
}
```
and run `sudo systemctl restart docker.service`.

**Comment by gplssm** [comment]
I've experienced another or the same issue with creating the docker container and installing pgrouting

```
egon-data --database-name egon-data-sh --dataset-boundary Schleswig-Holstein --jobs=12 serve
WARNING: Found orphan containers (meta_tool, caddy, jupyterlab, gogs, gogs_db, meta_db) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building egon-data-local-database-service
Step 1/4 : FROM postgres:12
 ---> adf2b126dda8
Step 2/4 : RUN apt-get update
 ---> Using cache
 ---> e0f550429f0c
Step 3/4 : RUN apt-get install -y postgresql-12-postgis-3
 ---> Using cache
 ---> fedab999cf77
Step 4/4 : RUN apt-get install -y postgresql-12-pgrouting
 ---> Running in 911fe915a326
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  postgresql-12-pgrouting-scripts
Suggested packages:
  postgresql-12-pgrouting-doc
The following NEW packages will be installed:
  postgresql-12-pgrouting postgresql-12-pgrouting-scripts
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 812 kB of archives.
After this operation, 9,783 kB of additional disk space will be used.
Err:1 http://apt.postgresql.org/pub/repos/apt buster-pgdg/main amd64 postgresql-12-pgrouting-scripts all 3.0.0~rc1-1.pgdg100+1
  404  Not Found [IP: 72.32.157.246 80]
Err:2 http://apt.postgresql.org/pub/repos/apt buster-pgdg/main amd64 postgresql-12-pgrouting amd64 3.0.0~rc1-1.pgdg100+1
  404  Not Found [IP: 72.32.157.246 80]
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/pgrouting/postgresql-12-pgrouting-scripts_3.0.0~rc1-1.pgdg100+1_all.deb  404  Not Found [IP: 72.32.157.246 80]
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/pgrouting/postgresql-12-pgrouting_3.0.0~rc1-1.pgdg100+1_amd64.deb  404  Not Found [IP: 72.32.157.246 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'egon-data-local-database-service' failed to build: The command '/bin/sh -c apt-get install -y postgresql-12-pgrouting' returned a non-zero code: 100
```

Without understanding it in detail, I propose to change `Dockerfile.postgis` to the following

```
FROM postgres:12

RUN apt-get update
RUN apt-get install -y postgresql-12-postgis-3
RUN apt-get update
RUN apt-get install -y postgresql-12-pgrouting
```

I'll provide a fix, eventually including a test to avoid that other people are bothered by this in the future.
