### ISSUE TITLE
Import and match data on industrial consumers from external sources

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#117]
Data from external sources on industrial electricity consumers need to be imported and matched to each other. 

- hotmaps
- s-eenergies
- Thesis DLR-VE

**Comment by ClaraBuettner** [comment]
I implemented the reduced import in test mode. I was also able to fix the hotmaps data export (maybe it's not the most elegant way, but it is working). 
I'm wondering if we should try to prevent using the old dataset.yml structure and use instead the new one with sources and targets.
