### ISSUE TITLE
Review and move 'lowvoltage' scripts 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#12]
Scripts from DP-section 'lowvoltage' need to be reviewed, adjusted and moved to the new repo:

- [ ] ego_dp_lv_substation.sql
- [ ] ego_dp_lv_substation_voronoi.sql
- [ ] ego_dp_lv_loadcut.sql
- [ ] ego_dp_lv_griddistrict.sql
- [ ] ego_dp_lv_consumption_peakload.sql

**Comment by nesnoj** [comment]
Done
