### ISSUE TITLE
Create power plant table 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#122]
We need to agree on the structure for a table containing all power plants for both scenarios.
One suggestion for structuring this table: 
```
class EgonPowerPlants(Base):
    __tablename__ = 'egon_power_plants'
    __table_args__ = {'schema': 'supply'}
    id = Column(Integer, Sequence('pp_seq'), primary_key=True)
    source = Column(String)     # source of data (MaStr/NEP/...)
    source_id = Column(String)  # id used in original source
    carrier = Column(String)
    chp = Column(String)
    el_capacity = Column(Float)
    th_capacity = Column(Float)
    subst_id = Column(Integer)
    voltage_level = Column(Integer)
    w_id = Column(Integer)      # id of corresponding weather grid cell
    scenario = Column(String)
    geom = Column(Geometry('POINT', 4326), index=True))
```
Questions to discuss: 
* Do we create one table for all power plants and scenarios?
* Or is a division between CHP and el. power plants useful? 
* Are additional columns needed?

**Comment by ClaraBuettner** [comment]
The creation of the table is integrated. 
But I'm wondering if we should add a column for the municipality because this is included in MaStR for power plants <30kW. Another option would be to apply the allocation process for small power plants before inserting in the table.
