### ISSUE TITLE
Create table for weather-dependent feed-in time series

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#123]
A table to store weather-dependent time series for the electricity generation of PV and wind power plants per weather grid cell needs to be created. 
It could look like this: 
```
class EgonReFeedIn(Base):
    __tablename__ = 'egon_re_feed_in'
    __table_args__ = {'schema': 'supply'}
    w_id = Column(Integer)
    weather_year = Column(Integer)
    carrier = Column(String)
    feedin = Column(ARRAY(Float()))
```

**Comment by ClaraBuettner** [comment]
I added the table on the corresponding branch. I also included a table with the geometry of the weather cells. This was also part of the old data-processing and used to match renewable power plants to weather data. 
Therefore I already added the download of the weather data using feedinlib. The installation was a bit tricky, and it currently still installs an older pandas version which I fixed only manually. 
The weather data download requires an account at the CDS website. I'll add this to the documentation.
