### ISSUE TITLE
Review and move 'REA' scripts

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#13]
Scripts from DP-section 'REA' need to be reviewed, adjusted and moved to the new repo:

- [ ] rea/ego_dp_lattice_500m.sql
- [ ] rea/ego_dp_lattice_50m.sql
- [ ] rea/ego_dp_rea_wpa_per_mvgd.sql
- [ ] rea/ego_dp_rea_lattice_per_area_500m.sql
- [ ] rea/ego_dp_rea_lattice_per_area_50m.sql
- [ ] rea/ego_dp_rea_setup.sql
- [ ] rea/ego_dp_rea_m1.sql
- [ ] rea/ego_dp_rea_m2.sql
- [ ] rea/ego_dp_rea_m3.sql
- [ ] rea/ego_dp_rea_m4.sql
- [ ] rea/ego_dp_rea_m5.sql
- [ ] rea/ego_dp_rea_results.sql    

The DP-section 'REA' deals with the reallocation of renewable powerplants without an exact or an incorrect georeferencing.

**Comment by IlkaCu** [comment]
In table boundaries.bkg_vg250_6_gem administrative districts consist of different polygons with the same nuts code. This caused some errors in the former data processing and needs to be taken into account when moving the REA scripts to egon-data. @ClaraBuettner: Can you name the exact script which caused the error?

**Comment by ClaraBuettner** [comment]
The script is actually part of the preprocessing, the new capacities are added twice for the regions with the same  rs (Regionalschlüssel), see here: https://github.com/openego/data_processing/blob/ae3c537a3299eb9465df163fe127ef3df18073c6/preprocessing/sql_snippets/ego_dp_res_rea_by_scenario.sql#L574-L605

**Comment by IlkaCu** [comment]
We decided to completely rework the process to position renewable power plants in our future scenarios. Therefore we won't need to migrate the REA scripts from the former data processing to egon-data. 
Some methods from the REA scripts might be reused in our new workflow.
