### ISSUE TITLE
standard CRS for geodata

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#131]
Do we have a standard CRS for geodata yet?

I've seen ETRS89/LAEA Europe (3035) in VG250 and WGS84 (4326) in etrago and power plants. I recommend to use only one CRS if possible. In open_eGo this was 3035 and imo it's a good choice as we're doing a lot of area calculation stuff WGS84 is not suitable for (or we need a lot of transformations..)

What do you think? (you might had this discussion already?)

PS: https://imgs.xkcd.com/comics/map_projections.png

**Comment by IlkaCu** [comment]
In open_eGo we agreed on using 3035 OR 4326 (see: https://redmine.iks.cs.ovgu.de/oe/projects/open_ego/wiki/Koordinatenreferenzsysteme_(CRS)) and until now we followed this guideline in eGon too. 
@nesnoj: If you see the need to reconsider this decision, we could discuss it tomorrow morning during our standup meeting.

**Comment by nesnoj** [comment]
Ooops, thanks for pointing me to resources I added.. :roll_eyes: 
I'd prefer a single CRS but if there's a good reason to keep WGS84, we can keep it..

**Comment by nesnoj** [comment]
Obsolete
