### ISSUE TITLE
Add post-processing for MaStR data

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#134]
With #130 cleaned MaStR was added to the pipeline. This data does not include some important processing steps of open-MaStR post-processing (geom column, removal of units outside Germany, ...).

Either provide post-processed data on Zenodo and download it here or execute the post-processing on the

**Comment by ClaraBuettner** [comment]
I already implemented some of these steps here: 
https://github.com/openego/eGon-data/blob/501072fd3f13f58521c7e307892425def7c59fdf/src/egon/data/processing/power_plants/__init__.py#L85-L99
I can also move it to another place or remove them when this is done in open-MaStR. I had already written them before for some analysis and thought I could use them intermediate directly in my script.

**Comment by nesnoj** [comment]
Outdated
