### ISSUE TITLE
Change docker database port to less common one

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#137]
Currently, when using a dockered database, the port 54321 is used. As this is a favorite of many (at least at RLI) and multiple docker database instances exist on the infrastructure I use, conflicts come up. I ran into the situation that the DAG failed because a wrong database was used :(

I suggest to change the port number to a less common one. 
@gnn are the any technical restrictions (length of the number) or are there any recommendations (preferred ranges)?

**Comment by gnn** [comment]
Not at all.  Ports below 1024 are privileged, so they're usually only usable with root privileges. Unprivileged ports are standardised a little bit randomly. But the range from 49152 to 65535 is apparently intended for custom services and other stuff. So we should be safe in that range. I'll make the database port configurable when implementing an option for using multiple different databases.
