### ISSUE TITLE
Requesting reviews for PRs

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#145]
During the intensive week some questions regarding PRs arose

- What needs to be reviewed? 
  - Just that the code working? 
  - That data is correct? 
  - That Tests pass? 
  - That documentation is up-to-date? 
  - That CHANGELOG is up-to-date
- Asking for a review
  - Asking for reviewing specific aspects helps reviewers a lot
  - When multiple people are asked for a review it should avoided that they check/test the same things

**Comment by nesnoj** [comment]
>     * What needs to be reviewed?

* That the meta data is complete and correct?
