### ISSUE TITLE
Map zensus cells to bounaries only once

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#165]
The zensus cells are mapped to boundaries.vg250_gem ([inside a SQL-query](https://github.com/openego/eGon-data/blob/fc1adc0437c0df8197f2fede59c0829686962684/src/egon/data/processing/zensus_vg250/zensus_population_inside_germany.py#L240-L244)) and to boundaries.vg250_krs ([here](https://github.com/openego/eGon-data/blob/fc1adc0437c0df8197f2fede59c0829686962684/src/egon/data/processing/zensus/__init__.py#L73)). 

When I wrote the second one, I did not knew that the first one will be added later on. As @IlkaCu said, I could rewrite it and use only the zensus cells inside Germany. But we would still have two spatial joins combining zensus cells and vg250 which need about 12 or 6 minutes only for Schleswig-Holstein. 
I would prefer to do this only once and create a table which maps all (populated) zensus cells to the boundaries.vg250_gem and use this in all function which need it.
@gplssm @IlkaCu: What do you think?

**Comment by gplssm** [comment]
I think it definitely makes sense to re-use the population data mapped on municipalities for higher aggregations like `krs`. This should save time and we'll be happy about it later :)

**Comment by IlkaCu** [comment]
I like that idea, but I would suggest to go one step further and create a central table which maps the zensus_id of all zensus cells to municipalities, administrative districts (Kreise), weather cells, load areas and and maybe also mv grid districts.

**Comment by ClaraBuettner** [comment]
> I like that idea, but I would suggest to go one step further and create a central table which maps the zensus_id of all zensus cells to municipalities, administrative districts (Kreise), weather cells, load areas and and maybe also mv grid districts.

We can also do this. I'm just wondering how we should name this table (`boundaries.egon_zensus_vg250_era5_grid_`... might be a little too long...) Maybe this indicates that separate tables (`egon_zenus_vg250; egon_zensus_era5; egon_zensus_loadarea`) would be better. 
However, I can start to implement the match to the municipalities and add additional columns or tables if we need them.

**Comment by ClaraBuettner** [comment]
While implementing the centralized mapping of zensus to vg250, I needed to take a closer look into the population-in-municipalities task. 
It raised some questions apart from the things I wanted to implement. I was mainly wondering why we map only the status quo population but not the forecast we use e.g. for electrical demands. But I don't know which information is used in upcoming tasks like the load area creation. @gplssm Could you help?

**Comment by ClaraBuettner** [comment]
I currently assign a municipality to at least all zensus cells with a population, even if the centroid is slightly out of the vg250 boundaries. Otherwise we would loose some people (~50 in Schleswig-Holstein).
@gplssm and @IlkaCu this is still to discuss. If you would prefer to keep the other option and delete the cells outside of the borders, please tell me.
