### ISSUE TITLE
Task 'zensus-inside-germany' fails

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#166]
The task 'zensus-inside-germany' fails with the following error when the task already run before since the data is not deleted from the table. 

```
> psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "destatis_zensus_population_per_ha_inside_germany_pkey"
> DETAIL:  Key (gid)=(173) already exists.
```
I also noticed that the index of this table is still called 'gid' but we decided in #140 to rename it to 'id'.

**Comment by gplssm** [comment]
I change it to empty/delete the table if it exists prio to this task
