### ISSUE TITLE
Change gid columns to id columns

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#169]
VG250 and zensus_vg250 tables use `gid` as name for the primary key column. According to the decision in this should be changed to `id`. Affects

- [ ] All VG250 tables
- [ ] Processing steps that combine vg250 and zensus
- [ ] Potentially all subsequent processing steps that work on data results from the two above

**Comment by IlkaCu** [comment]
@KathiEsterl: Could you please take over this task? Beside the vg250 and zensus_vg250 tables please also check the other tables in our workflow for `gid` columns and rename them to `id`.

**Comment by KathiEsterl** [comment]
I will work on this task here: [https://github.com/openego/eGon-data/tree/features/%23169-renaming-gid-and-subst_id](url)
This branch combines the issues explained above (gid -> id) and the renaming explained in issue #335 (subst_id -> bus_id).
