### ISSUE TITLE
Configure issue labels for this repo

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#17]
I would like to change the issue labels. Current set labels can be seen [here](https://github.com/openego/eGon-data/labels).
I propose to change it to the following list of labels:

- bug
- docs
- feature
- integration (aspects of integrating a new data set)
- data (discuss a dataset [dt. fachliche Diskussion])
- decision wanted
- workflow
- question
- help wanted

Do you have any comments on this? @IlkaCu @gnn

**Comment by IlkaCu** [comment]
Looks good. 
We could add 'question' to the list or does label 'help wanted' cover this?

**Comment by gplssm** [comment]
@gnn any further comments on this? Otherwise, I'll change labels accordingly.

**Comment by gnn** [comment]
The only comment I have is asking whether "wontfix" and "duplicate" are really necessary because that's something that usually goes into the closing statement of an issue, i.e. "Closed as wontfix." or "Closed as duplicate of #duplicate.". So those appear only on closed bugs and if someone finds a closed bug, I really want them to read at least the last part of the discussion.
But if you find them helpful, go ahead and use them too. Everything else seems fine.

**Comment by gnn** [comment]
Now that I'm actually opening an issue there's one other label which we are also using in "oemof" and which is pretty helpful. That would be `decision wanted` and I don't think it's covered by the other labels. Maybe we divide `data-integration` and `data-discussion` into the three labels `data`, `integration` and `discussion`. The we could use `discussion` the way we would use `decision wanted` wanted and we could use the other labels to further differentiate what the decision/`discussion` is about.

**Comment by gplssm** [comment]
> The only comment I have is asking whether "wontfix" and "duplicate" are really necessary because that's something that usually goes into the closing statement of an issue, i.e. "Closed as wontfix." or "Closed as duplicate of #duplicate.". So those appear only on closed bugs and if someone finds a closed bug, I really want them to read at least the last part of the discussion.
> But if you find them helpful, go ahead and use them too. Everything else seems fine.

Good points. Accepted. I gonna remove these labels

**Comment by gplssm** [comment]
> Now that I'm actually opening an issue there's one other label which we are also using in "oemof" and which is pretty helpful. That would be `decision wanted` and I don't think it's covered by the other labels. Maybe we divide `data-integration` and `data-discussion` into the three labels `data`, `integration` and `discussion`. The we could use `discussion` the way we would use `decision wanted` wanted and we could use the other labels to further differentiate what the decision/`discussion` is about.

I realized that I like `decision wanted` more that `discussion` and chose this. Apart from, I followed you suggestion.

**Comment by gplssm** [comment]
I changed the labels accordingly.
