### ISSUE TITLE
Add MaStR Lokationen data

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#174]
Information about locations of power plant facilities is needed to decide on the grid connection points

**Comment by gplssm** [comment]
I've more or less finished to add location data download to open-MaStR. Now, I could need some advice to decide how the data format of the CSV file for locations will look like. Can you help  me @ClaraBuettner ?

I receive MaStR location data in the following format:

One table with basic information

```
{'LokationMastrNummer': 'SEL961291281120',
   'NameDerTechnischenLokation': None,
   'Lokationtyp': 'Stromerzeugungslokation',
   'AnzahlNetzanschlusspunkte': 0}
```

A second table with extended information (the relevant data for our use case).

```
{'DatumLetzteAktualisierung': datetime.datetime(2019, 2, 6, 12, 46, 6, 817259),
 'MastrNummer': 'SEL993378731952',
 'NameDerTechnischenLokation': None,
 'VerknuepfteEinheiten': [{'MaStRNummer': 'SEE981092551413',
   'Einheittyp': 'Verbrennung',
   'Einheitart': 'Stromerzeugungseinheit'}],
 'Netzanschlusspunkte': [{'NetzbetreiberMastrNummer': 'SNB913006238462',
   'NetzanschlusspunktMastrNummer': 'SAN973166892140',
   'NetzanschlusspunktBezeichnung': None,
   'letzteAenderung': datetime.datetime(2019, 2, 6, 12, 46, 6, 817259),
   'Messlokation': 'DE00096406217GERZ100098000000S011',
   'Spannungsebene': 'Mittelspannung',
   'Nettoengpassleistung': Decimal('1960'),
   'BilanzierungsgebietNetzanschlusspunkt': 505,
   'Netzanschlusskapazitaet': None}]}
```

See also the related ORMs ([basic](https://github.com/OpenEnergyPlatform/open-MaStR/blob/c91c080e4bef2447f056ed618dca14fbdec311f6/open_mastr/soap_api/orm.py#L371-L377) and [extended](https://github.com/OpenEnergyPlatform/open-MaStR/blob/c91c080e4bef2447f056ed618dca14fbdec311f6/open_mastr/soap_api/orm.py#L380-L387)). As you see there, `VerknuepfteEinheiten` and `Netzanschlusspunkte` are defined as JSONB. For exporting raw data to CSV, I would prefer to write it to a single table without any JSON strings inside. This means, Iwould like to flatten the JSONs and create a column for each of the fields in the JSON strings.

Now the tricky part

- each location can have 1..N linked units
- each location *usually* has **one** grid connection point (Netzanschlusspunkte), but exceptions with multiple exist

It needs to be decided how to store the data contained in the two JSON fields


**VerknuepfteEinheiten**

Three options

1. One column VerknuepfteEinheiten with a list of SEE numbers (like on the webportal). This would also mean that the `Einheittyp` has a list of respective types
2. Create one row for each of the linked units while repeating the `LokationMastrNummer`
3. Keep the JSON data format for this column

**Netzanschlusspunkte**

Two options

1. Create one row for each on the `Netzanschlusspunkte` of a location (should not happend too often) while repeating `LokationMastrNummer`. If this is combined with option 2 from above and in the (worst) case of multiple units **and** multiple grid connection points, this would imply that rows for locations are repeated and for each repetition the linked units are repeated
2. Keep the JSON data format for this column


By the way, I've noticed that the table Einheiten on the webportal contains more data (e.g. Gemeinde). This data needs to be downloaded separately. Namely, it's the Marktakteursdata which can be linked via `NetzbetreiberMastrNummer`. Do you need this data?

**Comment by ClaraBuettner** [comment]
> It needs to be decided how to store the data contained in the two JSON fields
> 
> **VerknuepfteEinheiten**
> 
> Three options
> 
>     1. One column VerknuepfteEinheiten with a list of SEE numbers (like on the webportal). This would also mean that the `Einheittyp` has a list of respective types
> 
>     2. Create one row for each of the linked units while repeating the `LokationMastrNummer`
> 
>     3. Keep the JSON data format for this column
> 
> 
I think I would vote for the first option. It seems to be easier to create the csv file than with option 3 and doesn't create as much lines as option 2. It might be a little more complicated to match the VerknuepfteEinheiten iof the list, but we can just match the other way around and look for the Lokation and Netzverknüpfungspunkt for each entry in the Stromerzeugungseinheiten (which I would do anyhow). 

> **Netzanschlusspunkte**
> 
> Two options
> 
>     1. Create one row for each on the `Netzanschlusspunkte` of a location (should not happend too often) while repeating `LokationMastrNummer`. If this is combined with option 2 from above and in the (worst) case of multiple units **and** multiple grid connection points, this would imply that rows for locations are repeated and for each repetition the linked units are repeated
> 
>     2. Keep the JSON data format for this column
> 
> 
I would vote for option 1. As you mentioned, this shouldn't happen too often. And since I would choose the first option for the VerknuepfteEinheiten we won't have the worst case of additional rows. 

> By the way, I've noticed that the table Einheiten on the webportal contains more data (e.g. Gemeinde). This data needs to be downloaded separately. Namely, it's the Marktakteursdata which can be linked via `NetzbetreiberMastrNummer`. Do you need this data?

I'm not sure if I get this right. Do you mean that the 'Gemeinde' entry is used from the linked Marktakteursdata table in the webportal and not always available for each Einheit?

**Comment by gplssm** [comment]
> I'm not sure if I get this right. Do you mean that the 'Gemeinde' entry is used from the linked Marktakteursdata table in the webportal and not always available for each Einheit?

True! Gemeinde, PLZ, Ort, .. could all be joined from the units table. But, the grid operators name is also given in the Lokationen table on the webportal. Therefore, I assumed that the Marktakteurs data is joined here. Anyhow, I think we can take the Gemeinde and so on from the units table. Otherwise, let me know, then I would take care about Marktakteurs data which is currently not prioritized very high.

**Comment by KathiEsterl** [comment]
Hi Guido! 
Carlos and I are working on the implementation of the method for regionalization of future wind onshore and pv ground mounted. Could you inform us as soon as you have integrated this information in the workflow? 
I also subscribed to this issue now, so probably I will be informed anyway - I am not sure. 
Thanks a lot!

**Comment by gplssm** [comment]
Definitely! But I'm sorry that i have to say that it might take some days longer. I had some trouble downloading a that data and the download is still running...

**Comment by KathiEsterl** [comment]
> Definitely! But I'm sorry that i have to say that it might take some days longer. I had some trouble downloading a that data and the download is still running...

Don't worry, I think the both of us still have to work on other things in the mean time ;)

**Comment by IlkaCu** [comment]
@gplssm: What's the current status here?

**Comment by gplssm** [comment]
no good news :smirk: 

It is still not done. I had some difficulties that stopped me from making valuable progress (in terms of providing the data). Due to some drawbacks regarding the implementation for bulk location data download I was even worse... 
If everything runs smoothly, I guess, data could be available next week.

In order to speed up, I could offer to download location data for a single technology other than solar first. For example wind. Would this be helpful?

**Comment by gplssm** [comment]
A new MaStR dataset is uploaded to [Zenodo](https://sandbox.zenodo.org/record/808086), but not already integrated into the eGon-data workflow.
In order to start working with the location data prior to the actual integration, please download [the CSV about locations of electricity generating units](https://sandbox.zenodo.org/record/808086/files/location_elec_generation_raw.csv?download=1). Please note the discussion about data format above
