### ISSUE TITLE
Updated number of parallel tasks is not handed over to airflow

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#179]
When the parameter 'jobs' changes in the egon-data configuration, this is not handed over correctly to airflow.cfg. It still includes the first value that was selected.

**Comment by gnn** [comment]
That one was pretty easy. I shouldn't have broken `--jobs` in the first place. Fixed it (hopefully) directly on `dev` with dfcff3232319075cfaa53a3b1a5d0a58df8151c6.

**Comment by ClaraBuettner** [comment]
Yes, I tested it and it worked. Thank you! I will close the issue.
