### ISSUE TITLE
Demandregio uses older version of nuts regions

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#201]
eGon-data imports nuts regions in version 2016. demandRegio uses the the regions from 2013, they added the one nuts3-region which is new in version 2016, to be compatible. But still there are problems with two nuts3-regions (namely DEB16 and DEB19) which slightly changed in version 2016 and got new names (DEB1C and DEB1D). 
I checked it in qGis, the new and the old boundaries look very similar so I think we can just rename them. 
The errors are in population_prognosis. I could fix them there, but I guess we might get problems with the different names in other tasks as well. I'm wondering if I should rename the nuts3-regions of demandregio directly in the import. 
@IlkaCu what do you think?

**Comment by nesnoj** [comment]
We're using the 2020 version, aren't we? At least the [VG250 URL](https://github.com/openego/eGon-data/blob/c6930701d51ea5b554d764ed09a5d43fb353a632/src/egon/data/datasets.yml#L24) points to the 01.01.2020 version.

(I've similar problems with the emob data which uses older VG and I've to adapt..)

**Comment by ClaraBuettner** [comment]
> We're using the 2020 version, aren't we? At least the [VG250 URL](https://github.com/openego/eGon-data/blob/c6930701d51ea5b554d764ed09a5d43fb353a632/src/egon/data/datasets.yml#L24) points to the 01.01.2020 version.
> 

Yes, we download the data from 2020, but the NUTS versions haven't changed since 2016, see [here](https://ec.europa.eu/eurostat/de/web/nuts/history).

> (I've similar problems with the emob data which uses older VG and I've to adapt..)

In my case the excel files in the above link helped to find the differences between different versions, maybe this could also help you.
