### ISSUE TITLE
Zensus cells without population but with households

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#202]
There are three zensus cells that don't have a population, but have households. (zensus_population_ids 167668, 476491, 751371).
This currently leads to errors in household_prognosis but might also affect other tasks later on.

**Comment by IlkaCu** [comment]
Is this the case for the German data sets or the one of Schleswig-Holstein? 
It might be a reasonable and easy solution to delete those cells from the data set, what do you think?

**Comment by ClaraBuettner** [comment]
This also happens for buildings and apartments. I would suggest to delete all rows in the zensus-misc tables which have a population < 0. I implemented this and already started to test it, but since the task import-zensus-misc needs about 3 hours, it needs some time to see the results.

**Comment by nesnoj** [comment]
Do those contradicting cell data appear in the raw dataset too or is it a flaw in the import?
If there're only 3 cells in DE I consent to drop them..

**Comment by ClaraBuettner** [comment]
> Do those contradicting cell data appear in the raw dataset too or is it a flaw in the import?

Those cells also appear in the raw files. 

> If there're only 3 cells in DE I consent to drop them..

In case of households, there are only these three cells. But there are much more cells without a population, but with buildings. (Only in Schleswig-Holstein ~1000). Regarding qGis and openstreetmap, these are in many cases holiday homes. 
But there are also other cases, where it e.g. looks on openstreetmap like a single farm but is listed in Zensus as 3 houses without a population. 
I don't know much about the Zensus data and how it was exactly created. @IlkaCu , can you help?
