### ISSUE TITLE
task "run_osmtgmod" fails

### ISSUE THREAD

**Issue by KathiEsterl** [openego/eGon-data#206]
All the other tasks work, but this task fails. 
Attached you find the log. 
[run_osmtgmod_log.txt](https://github.com/openego/eGon-data/files/6284754/run_osmtgmod_log.txt)

**Comment by ClaraBuettner** [comment]
Just to be sure, have you installed all needed python packages and other [pre-requisites](https://github.com/openego/eGon-data#pre-requisites)?

**Comment by KathiEsterl** [comment]
> Just to be sure, have you installed all needed python packages and other [pre-requisites](https://github.com/openego/eGon-data#pre-requisites)?

Java was missing... Now it is working. Thank you!
