### ISSUE TITLE
Describe the workflow of data processing

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#23]
Use the section [workflow]() for describing how the eGo^n data processing works. It should include at least (please add more)

- [x] A  transparent and reproducible open data based data processing pipeline for generating scenario data...
- [x] Referring to ego^n project context (use ego-n.org)
- [x] Processes spatial data, time series and other data
- [x] In principle language-agnostic but mostly Python and SQL is used
- [x] Local containerized PostgreSQL database for SQL processing
- [x] Airflow organizes the order of execution of processing steps through so-called Operators
- [x] Updating [the workflow sketch](https://gist.github.com/gplssm/31aa4da15d58c3471f2398d29613363f) and including it would be help but maybe too much work!?
- [x] Airflow description
- [ ] Docker description including connection infos

**Comment by IlkaCu** [comment]
I adjusted @gplssm's workflow sketch. I would appreciate any feedback as I am not very happy with it yet. I am not sure if the sketch illustrates the data exchange between tasks and local db sufficiently. 
![Workflow_egon_data](https://user-images.githubusercontent.com/16799094/96872166-8d56c280-1473-11eb-8524-b73dbd05c5b0.png)

**Comment by IlkaCu** [comment]
I reworked the workflow sketch. 

[DP_Workflow_15012021.pdf](https://github.com/openego/eGon-data/files/5820973/DP_Workflow_15012021.pdf)
