### ISSUE TITLE
Tables used for mapping 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#233]
In this ticket we would like to collect all 'mapping' tables to avoid redundancies and identify possible simplifications. 
Please add more entries to the table below: 

| table name  | columns  | implemented? |
| ------------- |:-------------:| :-------:|
| boundaries.egon_map_zensus_nuts3      | zensus_population_id, zensus_geom, nuts3| replaced by boundaries.egon_map_zensus_vg250 |
| boundaries.egon_map_zensus_vg250      | zensus_population_id, zensus_geom, vg250_municipality_id, vg250_nuts3  |   yes|
| grid.mv_grid_districts <--> municipalities | subst_id, geom | no |
| boundaries.egon_map_mvgriddistrict_vg250 | subst_id, griddistrict_geom, vg250_nuts1 | yes |
| demand.map_zensus_district_heating_areas | zensus_population_id, area_id | yes |

**Comment by nesnoj** [comment]
I think this can be closed?!
