### ISSUE TITLE
Branch naming conventions

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#25]
Up front: this is bikeshed territory so I hope it's not too annoying
I saw that @gplssm used `feature/` as the prefix for feature branches, while I'm accustomed to using `features/`, because the prefix translates to a folder inside the Git repository and I'm used to using plural for folder names, e.g. `documents` and `images`. Would you mind using that convention for this repository?

**Comment by gplssm** [comment]
Wouldn't mind at all to use this convention! Thanks for explaining. I would say, let's define a naming convention for easily linking branches and issues. I propose (what I normally use)

`features/#<issued-id>-very-brief-description`

It would further other prefixes

- `fix/`
- `refactoring/`

**Comment by IlkaCu** [comment]
I agree with the naming convention suggested by @gplssm.

**Comment by gnn** [comment]
I'd use `fixes` and `refactorings`, opting for plural for the same reason as with `features`. But again, that's just me. If you prefer singular, we can go for that. Consistency would be more important.

**Comment by gplssm** [comment]
> I'd use `fixes` and `refactorings`, opting for plural for the same reason as with `features`. But again, that's just me. If you prefer singular, we can go for that. Consistency would be more important.

Let's follow your conventions. I don't have a strong opinion on using my conventions.

**Comment by gnn** [comment]
Since this convention is already written down in CONTRIBUTING.rst, I guess it's settled and this issue can be closed.
If you still have further remarks, feel free to re-open and comment, @gplssm and @IlkaCu .
