### ISSUE TITLE
Identify CTS load areas including peak load and annual demand

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#250]
As part of the load areas, CTS sector-sepcific load areas are constructed from adjacent census cells with annual demand > 0 that are located within one MV grid district.

**Comment by gplssm** [comment]
Remaining TODOs

- [ ] Write module docstring for documenting the dataset
- [ ] Change peak load calculation to be calculated based on the aggregated demand time series for all sectors for each load area
- [ ] Add Dataset and integrate into pipeline
- [ ] Add CHANGELOG note

**Comment by nesnoj** [comment]
Superseded by #1014
