### ISSUE TITLE
Temporary distribution of PV rooftop capacities 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#255]
As the potential areas for PV rooftop aren't available at the Ffe open data platform yet, we would like to implement an interim solution on the HV/MV level. 

**Basic idea:** Distribute capacities for Germany (egon100RE) or the federal states (eGon2035) linearly to the household and CTS demands per mv-griddistrict. 

**Tasks:** 
* Map mv grid districts and federal states (nuts1), also see issue #233 
* Sum up demands for households and CTS per mv griddistricts 
* Distribute PV capacities linearily to el. demands to the mv griddistricts 
* Add data to pf tables

**Comment by nesnoj** [comment]
@khelfen is currently implementing a new distribution #684. The DB table `supply.egon_scenario_capacities` contains scenario data for eGon2035 (fed state) and eGon100RE (1 value for DE). Is the latter already supplied by p-e-s or a dummy value @ClaraBuettner? And is this the right table to import the capacities for eGon100RE from?

(btw: for eGon100RE the component value differs from the ones in eGon2035, see pic below)

![grafik](https://user-images.githubusercontent.com/15910173/156733639-9260d4e0-a8b3-4b95-9b1b-1c06da71c4ac.png)

**Comment by ClaraBuettner** [comment]
> @khelfen is currently implementing a new distribution #684. The DB table `supply.egon_scenario_capacities` contains scenario data for eGon2035 (fed state) and eGon100RE (1 value for DE). Is the latter already supplied by p-e-s or a dummy value @ClaraBuettner? And is this the right table to import the capacities for eGon100RE from?
> 

The installed capacity for eGon100RE is from a first p-e-s calculation, it will change when we run p-e-s again with all changes (e.g. your mobility data). So it is not the final value but also not dummy data. 
And yes, the table is the right one. 

> (btw: for eGon100RE the component value differs from the ones in eGon2035, see pic below)
> 
> ![grafik](https://user-images.githubusercontent.com/15910173/156733639-9260d4e0-a8b3-4b95-9b1b-1c06da71c4ac.png)

Thank you for the remark, I will change this.
