### ISSUE TITLE
GitHub actions fail

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#271]
After merging the dev branch including the dataset versioning into my branch the GitHub Actions fail. (#269)
Since they didn't fail before the merge I assume that changes on the dev lead to this problem.

**Comment by gnn** [comment]
It's been a while since this has been opened so it's about time to fix it. PR #475 is opened to monitor the progress on this.

**Comment by gnn** [comment]
Fixed. At least the build is not failing any more. If it starts failing again, it will be for a different reason.
