### ISSUE TITLE
Insert household demand time series into database

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#295]
Currently, raw data of household electricity demand time series is read from a `.h5` file (accessible through a function). For easier access, in particular, when mapping of zensus cells and household profile IDs is published on OEP, it makes sense to have the profile on OEP as well. Therefore, during the workflow household demand time series should be inserted into the database.

But, please consider

- It's quite an amount of data (~6 GB `.h5`) which doubles up in the container's volume
- It needs to be documented in the mapping table that profile IDs link to this table
- Data access from file needs to be replaced by database access

**Comment by nesnoj** [comment]
Maybe: Use reduced size of profiles for test region
