### ISSUE TITLE
run_pypsaeursec fails

### ISSUE THREAD

**Issue by EvaWie** [openego/eGon-data#299]
Even though fiona is installed in the environment, I use, the task run_pypsaeursec seems to fail because of problems with fiona.

|   ImportError: the 'read_file' function requires the 'fiona' package,
|   but it is not installed or does not import correctly.

Maybe there is another underlying problem. The log is quite long. The problem could also be related to the used Ubuntu and python version.

Addition: The important part of the log was the following:
|   Importing fiona resulted in: libtbb.so.2: cannot open shared object
|   file: No such file or directory

**Comment by EvaWie** [comment]
As stated in [here](https://github.com/openego/eGon-data/pull/218#issuecomment-834632580) libtbb2 needs to be installed using
sudo apt install libtbb2.

**Comment by EvaWie** [comment]
The Pre-requisites of branch [features/#138-integrate-pysa-eur-sec](https://github.com/openego/eGon-data/tree/features/%23138-integrate-pysa-eur-sec) need to be updated.

**Comment by ClaraBuettner** [comment]
I added libtbb2 to the pre-requisites
