### ISSUE TITLE
Selecting georeferenced data via oedialect 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#32]
I tried to select data from the OEP via the oedialect but always get an error when selecting geo-referenced data: 
(e.g. with the example of @gplssm I found in the redmine)

> ParseException:Invalid HEX char
> Traceback (most recent call last):
>   File "<ipython-input-1-7ba0d221c842>", line 33, in <module>
>     index_col='gid')
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/pandas/io/sql.py", line 383, in read_sql_query
>     chunksize=chunksize,
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/pandas/io/sql.py", line 1314, in read_query
>     parse_dates=parse_dates,
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/pandas/io/sql.py", line 124, in _wrap_result
>     frame = DataFrame.from_records(data, columns=columns, coerce_float=coerce_float)
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/pandas/core/frame.py", line 1788, in from_records
>     arrays, arr_columns = to_arrays(data, columns, coerce_float=coerce_float)
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 547, in to_arrays
>     data = [tuple(x) for x in data]
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 547, in <listcomp>
>     data = [tuple(x) for x in data]
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/geoalchemy2/types.py", line 164, in process
>     return self.ElementType(value, **kwargs)
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/oedialect/dialect.py", line 488, in init_WKBElement
>     data = shapely.wkb.dumps(shapely.wkb.loads(data, hex=True))
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/shapely/wkb.py", line 15, in loads
>     return reader.read_hex(data)
>   File "/home/clara/first_try_dp/lib/python3.6/site-packages/shapely/geos.py", line 442, in read_hex
>     "Could not create geometry because of errors "
> WKBReadingError: Could not create geometry because of errors while reading input.
> 

It doesn't depend on the table I try to access (I tried it with different ones with the same problem) and also happens when I only query data. 

Package versions are: 
GeoAlchemy2==0.8.4
oedialect==0.0.9
SQLAlchemy==1.3.14

I don't know how to takle this problem and would be very pleased if you could help me with this.

**Comment by ClaraBuettner** [comment]
When I install oedialect==0.0.8 it works fine. I can work with this version by now.

**Comment by gnn** [comment]
Now thats weird. This means it's definitely an `oedialect` issue that I need to look into.

**Comment by gplssm** [comment]
> When I install oedialect==0.0.8 it works fine. I can work with this version by now.

Could you @ClaraBuettner  then, temporarily, set this version specification in the requirements? This helps other people to get around the issue that @ClaraBuettner found.

**Comment by ClaraBuettner** [comment]
Currently, oedialect is not part of the requirements. I can add this and the version dependency to the setup.py.

**Comment by KirannBhavaraju** [comment]
@ClaraBuettner  @gplssm  I started to fix this issue in the oedialect, but could you guys please assist me with an example of a Geo-Referenced Table? I am unaware. It would also help if you shared the example in redmine, i do not think i have access... or your code... ^^'

**Comment by gnn** [comment]
[Answered][0] in the `oedialect` repository. Seems like the issue isn't reproducible anymore, so maybe we can drop the upper version limit on the `oedialect`?

[0]: https://github.com/OpenEnergyPlatform/oedialect/issues/40#issuecomment-779387686

**Comment by ClaraBuettner** [comment]
I did some test and could not reproduce the problem, sorry for the confusion. So yes, I think we can remove the upper version limit.
