### ISSUE TITLE
Log: Could not import disaggregator

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#320]
The log frequently shows
`Could not import disaggregator. Please run task 'demandregio-installation'`
but the task has been successfully run and disaggregator is installed (downstream demand tasks ran and I can also import the disaggregator in the venv).
So I guess I can ignore this?

**Comment by ClaraBuettner** [comment]
This log was very confusing, I removed it in ee445abdc40a3dbef29dc5b7c5d54d3d52abe62e.
