### ISSUE TITLE
Rename eTraGo tables 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#334]
We would like to rename the input tables for eTrago to less complicated names. Therefore @ClaraBuettner and @IlkaCu suggest to rename it to `grid.egon_etrago_generator` instead of `grid.egon_pf_hv_generator` and so on.
@ulfmueller: Would you agree? 

@KathiEsterl: We would like to ask you to implement the renaming as soon as we agree on the new names. This task includes the renaming in the table creation part of the workflow, the datasets.yml file and any other place in egon-data were the old table names occur.

**Comment by ulfmueller** [comment]
Renaming has some implications - as far as I am concerned - also in the [pypsa-eur-sec integration branch](https://github.com/openego/eGon-data/tree/features/%23138-integrate-pysa-eur-sec) ... I guess I would leave it as it is - but I would agree anyhow - especially if I don't have to change my code ;)
