### ISSUE TITLE
Rename subst_id to bus_id

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#335]
We agreed on using `bus_id` instead of `subst_id` in our tables. Please search for columns named `subst_id` in our workflow and rename it to `bus_id`.

**Comment by KathiEsterl** [comment]
I will work on this task here: [https://github.com/openego/eGon-data/tree/features/%23169-renaming-gid-and-subst_id](url)
This branch combines this task with the tasks explained in issue #169 .
