### ISSUE TITLE
Store files in working dir

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#341]
In some tasks, files are stored in the a task's directory instead of the working dir which induces subsequent problems and makes the pipeline more error-prone.
This came up in https://github.com/openego/eGon-data/pull/338#discussion_r673135401 , check out for more background info.

- check if your dataset is affected
- modify your task, use a proper way to get current working dir (see link above how to do that)
- adjust downstream tasks accordingly (or notify responsible person)

This should be approached as soon as all tasks will have been migrated to datasets.

@gnn Please amend if I've missed something here..

**Comment by gnn** [comment]
Damn. I [commented][0] on the other thread before seeing this. So here's a short summary along with some more short comments:

  * This is a duplicate of [#203][-1] which also has a, probably outdated, [PR][1] associated with with it. Feel free to close whichever you want. The PR can for example easily be changed to be associated with the issue you're currently reading.
  * The [contribution guidelines][2] point this out as a best practice.
  * The [comment][3] linked above doesn't really tell you how to store files in (a subdirectory of) the current working, but goes into great detail on how to "correctly" access data files shipped with the repository. Which is also important, but a different issue. The contribution guidelines do tell you [how to use the current working directory][4], though.
  * If this is adopted, consider not dropping everything directly into the working directory, but creating a neat hierarchy. This is just a bonus though. :)

I'm actually on "vacation" until the 2021-07-30, so I might not be too active in these issues until then.

[-1]: ./203
[0]: https://github.com/openego/eGon-data/pull/338#discussion_r674269142
[1]: ./208
[2]: ../blob/dev/CONTRIBUTING.rst
[3]: https://github.com/openego/eGon-data/pull/338#discussion_r673135401
[4]: ../blob/dev/CONTRIBUTING.rst#where-to-save-downloaded-data

**Comment by nesnoj** [comment]
>     * This is a duplicate of [#203](./203) which also has a, probably outdated, [PR](./208) associated with with it. Feel free to close whichever you want. The PR can for example easily be changed to be associated with the issue you're currently reading.

Oh, that's what happens with too many issues... for sake of a higher visibility I'll keep mine ;).

>     * The [contribution guidelines](../blob/dev/CONTRIBUTING.rst) point this out as a best practice.
>     * The [comment](https://github.com/openego/eGon-data/pull/338#discussion_r673135401) linked above doesn't really tell you how to store files in (a subdirectory of) the current working, but goes into great detail on how to "correctly" access data files shipped with the repository. Which is also important, but a different issue. The contribution guidelines do tell you [how to use the current working directory](../blob/dev/CONTRIBUTING.rst#where-to-save-downloaded-data), though.

Cheers!

**Comment by nailend** [comment]
> There're 2 more migrated datasets which do not store the files in the working dir: OSM and VG250
> @nailend Could you please take care of this?
> I've done most of it in #411 but it must be checked if there are other downstream tasks that use these entries.

I have also identified the scripts from `importing/zensus` as still using the task directory. Will add this to #411

**Comment by nailend** [comment]
Merge into weekend-branch

**Comment by nesnoj** [comment]
> > There're 2 more migrated datasets which do not store the files in the working dir: OSM and VG250
> > @nailend Could you please take care of this?
> > I've done most of it in #411 but it must be checked if there are other downstream tasks that use these entries.
> 
> I have also identified the scripts from `importing/zensus` as still using the task directory. Will add this to #411

#411 merged into `dev`, thanks 4 your efforts @nailend!
Seems that there're no further files stored outside of the working dir :tada: :tada: :tada: 
Closing..
