### ISSUE TITLE
dependencies of heat-supply.district-heating

### ISSUE THREAD

**Issue by KathiEsterl** [openego/eGon-data#353]
This task accesses data out of the table _supply.egon_power_plant_ to identify chp-potentials:
**eGon-data/src/egon/data/datasets/heat_supply/district_heating.py** in line **172 ff.**

It fails if there are no entries in this table yet. 

I think some dependencies have to be added here to make sure, all the power plants with chp-potentials are added to the table before running this task.

**Comment by ClaraBuettner** [comment]
There will be changes in the allocation of CHP, so I have to adjust this method in [another branch](https://github.com/openego/eGon-data/tree/features/%23266-integrate-combustion-chp). I will add this dependency there.

**Comment by ClaraBuettner** [comment]
This was solved in #395
