### ISSUE TITLE
Zenodo repository

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#356]
The [repository](https://zenodo.org/record/4896527#.YQFvJkBCSUn) is used to store small-scale raw input data files for the data-processing that can not be automatically downloaded from the internet (e.g. if individual data are extracted from pdf files).

[Collected files](https://next.rl-institut.de/apps/files/?dir=/294_eGon/1_Arbeitsinhalte/AP1/raw_input_small_scale&fileid=844677) that still need to be integrated to the repo:

- [x] household_electricity_demand_profiles (link to files see Readme.md in NC folder)
- [ ] household_heat_demand_profiles
- [ ] MA_Schmidt_Industriestandorte_georef.csv

**Comment by IlkaCu** [comment]
@nesnoj: Could you please add your data sets, which are supposed to be published in the zenodo repo, here?

**Comment by nesnoj** [comment]
> @nesnoj: Could you please add your data sets, which are supposed to be published in the zenodo repo, here?

Done. For now, I've set the licence to CC BY 4.0 for both household profiles @ClaraBuettner but will ask IEE for final approval.

**Comment by AmeliaNadal** [comment]
I removed the biogas_atlas_Germany of the files in NextCloud and the associated documenation.

**Comment by IlkaCu** [comment]
There is one file named `2021-04-09_CTS_WZ_definition_voltage_level.ods` included in the current version of our zenodo upload. As this file is not used in the egon-data workflow, I would remove it. @nesnoj: Any objections?

**Comment by nesnoj** [comment]
> There is one file named `2021-04-09_CTS_WZ_definition_voltage_level.ods` included in the current version of our zenodo upload. As this file is not used in the egon-data workflow, I would remove it. @nesnoj: Any objections?

Thanks for thorough checking! That's my allocation attempt we discussed [some time ago](https://redmine.iks.cs.ovgu.de/oe/projects/ego-n/wiki/12042021_Webko_Verteilung_und_Netzanschluss_GHD). Yes it's not necessary anymore, I moved to another folder in /AP1.

**Comment by IlkaCu** [comment]
Version 0.2 of our data bundle is available here: https://zenodo.org/record/5211145#.YR0BS1tCS-k

**Comment by nesnoj** [comment]
Great! Did you provide the link to 0.2 and not to the latest version on purpose to make sure it's compatible to the current pipeline version?

**Comment by IlkaCu** [comment]
I just provided the link as an information for you, I additionally update the data bundle download here: #397
As soon as this is merged (give me 1h) the additional files will be available after rerunning the central downloading task.

**Comment by nesnoj** [comment]
That's very outdated, right @IlkaCu ?
