### ISSUE TITLE
Extend task "import-zensus-misc" by combined table of buildings, apartments and pop

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#359]
Create table with buildings, apartments and population for all Zensus cells (also with pop = -1 or NULL).
Include cells where there's either building, apartment or population data.

Required e.g. for #262

**Comment by nesnoj** [comment]
As there seems to be no progress in migrating Zensus to datasets, I'll add this to the old structure if you don't mind @ClaraBuettner .

**Comment by ClaraBuettner** [comment]
> As there seems to be no progress in migrating Zensus to datasets, I'll add this to the old structure if you don't mind @ClaraBuettner .

You can do it like this from my point of view, but I will not migrate the Zensus dataset. If I remember it correctly, @gnn wanted to do this.
