### ISSUE TITLE
Integrate egon industrial gas and h2 demands in p-e-s

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGon-data#371]
in order to get more consistency the industrial demand for gas and h2 have to be summed up for Germany and changed within p-e-s. For the other countries everything will stay at it is. 
@AmeliaNadal unfortunately the discussed approach is not easily doable because the industrial_demand="resources/industrial_energy_demand_elec_s{simpl}_{clusters}.csv" gets created within p-e-s...
I just talked to @ClaraBuettner about it and she told me how they did it in case of heat. I think it would be the best to do it as they did it there. Therefore you would create a csv file or similar in egon-data which has the aggregated values for Germany for gas and h2. Inside of our p-e-s fork you would then write a function which overwrites these particular values taking this file as a base.
Check out the [heat PR](https://github.com/openego/pypsa-eur-sec/pull/7/) or additionally ask @ClaraBuettner as a base for your adaptation.

**Comment by AmeliaNadal** [comment]
In eGon100RE, the values of the p-e-s are used for the industrial demands (CH4 and H2).
We verified that these values are consistent with the source of the eGon2035 (https://github.com/openego/eGon-data/issues/626), we won't change them.
