### ISSUE TITLE
Kick out railway mobility in p-e-s fork

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGon-data#375]

**Comment by ulfmueller** [comment]
I have to pass on this task, primarily because I dont have time to test the changes. 
The ToDos:
1. check again, whether it is really a good idea to just kick the railway mobility out in p-e-s. I would vote for it, in order to not get additional installed EE capacity which can be used in our system without having to supply that load.
2. check the prepare_network file for the railway parts and simply delete them. Especially, I would get rid of the rail part [here](https://github.com/openego/pypsa-eur-sec/blob/master/scripts/prepare_sector_network.py#L597-L598)
3. The [ice_share](https://github.com/openego/pypsa-eur-sec/blob/master/scripts/prepare_sector_network.py#L1068-L1070) should be 0 because the electric_share is 1 in our settings. So, there should be nothing more to do. Because, [here](https://github.com/openego/pypsa-eur-sec/blob/master/scripts/prepare_sector_network.py#L1155-L1177) nothing will happen due to our config settings.

**Comment by ClaraBuettner** [comment]
The railway transport is now optional in our pypsa-eur-sec fork. It is set to `False` in the egon-data configuration file. 
The already electrified railway demand is still part of the electricity load curve (from ENTSO-E) but the electricity demand from egon-data which not includes railway transport will be used (see #402 ). So the railway transport will not be part of the final electricity load curve.
