### ISSUE TITLE
Filter industrial landuse areas from osm 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#378]
The industrial demands are currently distributed to all osm areas which are tagged with `landuse = 'industrial' `. 
This also includes areas that do not have an industrial energy demand (e.g. Stadtwerke, Gewerbegebiete or solar parks). 
Th identify possible locations for industrial CHP I filtered the industrial areas, this might be also used to filter the areas which get an industrial demand: https://github.com/openego/eGon-data/blob/d062dd149583c74240fda28e9e746d69b735f6b8/src/egon/data/datasets/chp/small_chp.py#L297-L311

**Comment by IlkaCu** [comment]
Filter/ Remove industrial landuse areas from demand distribution methodology which are intersecting with industrial sites.
