### ISSUE TITLE
Include checks to ensure data validity 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#382]
To ensure the validity of our resulting data, some data checks should be integrated in the workflow. Central resulting tables such as eTraGo tables should be part of the checks. 
One useful example: 
https://github.com/openego/eGon-data/blob/75f05b4e3ca1886c49c995a6fcf23bc7f69d9361/src/egon/data/datasets/heat_supply/__init__.py#L110-L125

**Comment by nesnoj** [comment]
Thanks for taking care!
How can we integrate additional checks?

@nailend Could you add some points/scrips/links to other issues here for validating the HH el. demand that have been used during the development?
