### ISSUE TITLE
Remove version columns from existing tables 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#384]
We agreed on removing the version columns from all tables prior to the (not yet existing) OEP-export task. 
This applies to the following tables: 

- [ ] grid.egon_etrago_... (Ilka)
- [ ] demand.egon_etrago_electricity_cts (Ilka)
- [x] demand.district_heating_areas (Clara)
- [x] demand.egon_peta_heat (Clara)
- [x] demand.map_zensus_district_heating_areas (Clara)
- [ ] others?

**Comment by ClaraBuettner** [comment]
I removed the version columns in the heat demand and district heating tables in #363
