### ISSUE TITLE
Dispatch of CH4 production

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#386]
For now, the dispatch of the CH4 production is let to the optimizer. However, this cannot insure that the overall values of the produced gas matches the NEP values. 
On the other hand, forcing the gas production like it could be done through p_set_fixed (https://github.com/openego/eGon-data/blob/dev/src/egon/data/datasets/gas_prod.py#L219) might disadvantage e.g. power2gas installations.
The dispatch of the CH4 production could let to the optimizer with the introduction of a marginal cost and maybe a distinction between natural gas and biogas.

**Comment by fwitte** [comment]
I would root for having (different) marginal costs for natural gas and biogas.
