### ISSUE TITLE
Remove column 'country' from table supply.egon_scenario_capacities

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#391]
Remove column `country` from table `supply.egon_scenario_capacities` and make sure `nuts` column is filled to provide information about the scope of the data.

**Comment by ClaraBuettner** [comment]
There is no data for other renewable and other non renewable, 'Sonstige Konventionelle' and 'Sonstige Erneuerbare' has to be renamed to 'sonstige ..' here: 
https://github.com/openego/eGon-data/blob/555e58c7141d5bc18c29a74b288e01a42dac852b/src/egon/data/datasets/scenario_capacities.py#L131-L145
