### ISSUE TITLE
Paths contain hard-coded slashes in some tasks

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#398]
Old topic, but still pending:
The following tasks make use of absolute file paths which (beside of coding standards) most likely prevents the pipeline to be run under Windows (even if users of this so-called OS is not our primary target group :penguin:):
- [x] demandregio @ClaraBuettner @IlkaCu 
- [x] geothermal @ClaraBuettner 
- [x] scenario_capacities @ClaraBuettner 
- [x] calculate_dlr @ClaraBuettner 
- [x] insert-gas-grid @AmeliaNadal 

(list might be incomplete)
Low prio but it's easy to fix and saves some pain for other users.

See @gnn's post on this topic: https://github.com/openego/eGon-data/pull/338#discussion_r673135401
Related: #59

**Comment by ClaraBuettner** [comment]
All these functions use files from the data bundle. I thought a path like this: 
https://github.com/openego/eGon-data/blob/7ac8e03a289003047faee268d0d34a2d3b32efd7/src/egon/data/datasets/scenario_capacities.py#L119-L121
is a relative path because it is a sub-folder of the egon-data working directory. 
So I am a bit wondering how I should change this. Should I use `Path(.)/` instead of `os.path.join()` ?

**Comment by nesnoj** [comment]
Aah sorry, "absolute" is quite misleading. It's all about the slashes in the path.

In your example above, the "data_bundle_egon_data/nep2035_version2021" part will work on Linux but will crash on Windows due to the hard-coded slash as it cannot be resolved properly (Win uses "\").
Working version:
```
 target_file = os.path.join( 
     "data_bundle_egon_data",
     "nep2035_version2021",
     scenario_config('eGon2035')['paths']['capacities']) 
```
(PS: Path is preferred if we stick to @gnn's recommendations though)

**Comment by ClaraBuettner** [comment]
I replaced the paths with slashes with` Path` objects in my scripts on this branch:https://github.com/openego/eGon-data/tree/features/%23398-remove-slashes-in-paths
If you like, you can also change the other tasks in this branch.

**Comment by AmeliaNadal** [comment]
I replaced the paths with slashes with Path objects in my scripts on the same branch and created a pull request (and I you as reviewer @nesnoj).

**Comment by nesnoj** [comment]
Thx for your efforts!
