### ISSUE TITLE
Include osmTGmod

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#4]
Integrate the osmTGmod tool into the egon-data workflow. 
Clarify if we can keep the table structure and if the data should be published at the OEP.

**Comment by ulfmueller** [comment]
I did not find any preprocessing scripts which create the two osmTGmod tables grid.otg_ehvhv_bus_data  grid.otg_ehvhv_branch_data . @gplssm when you worked on the 'preprocessing 2.0' you probably excluded this part?! Or did you find s.th.? At least I think I remember that you searched for s.th....
I suppose you helped yourself as in [here](https://github.com/openego/data_processing/blob/dev/preprocessing/osmtgmod/import_osmtgmod.py) which does not include a osmTGmod data creation and rather takes a certain osmTGmod output as an input.

Well, this time the osmtgmod data creation should be implemented reproducibly which I suppose has to be redone from scratch based on this [documention](https://github.com/openego/osmTGmod/blob/master/osmTGmod_documentation_0.1.0.pdf). 

Then, this script should be considered: https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_osmtgmod_to_pypsa.sql

Then, we have to check the quality of the newly generated grid and check whether the [ex-post corrections](https://github.com/openego/data_processing/blob/master/utilities/ego_dp_fix_ehv_subnetworks.sql) still can be usefully applied.

**Comment by ulfmueller** [comment]
Once #1 is finished I would start with this job. @gplssm any projections when the PR #31 will be merged?

**Comment by ulfmueller** [comment]
Currently osmTGmod is designed such that it either downloads and filters osm data (using osmosis) or takes an already filtered pbf-file. So I probably do not need an already imported database but rather need to know where the downloaded (and filtered) geofabrik file is at so the process takes consistently the same osm data.
@gplssm can you tell me how I can link to the same osm data you are using for the import?
