### ISSUE TITLE
Migrate zensus to datasets

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#422]
@gnn Please migrate zensus to datasets as we agreed on.

As I made some extensions in #421 you may wait until that has been merged to `dev` or you start from that branch (`features/#359-zensus-add-combined-bld-apt-pop-table`).

In #277 you wrote that the migration is already in progress?! (3 months ago :wink: )

**Comment by nesnoj** [comment]
#421 has been merged tonight..

**Comment by nesnoj** [comment]
Any progress here? @gnn

**Comment by IlkaCu** [comment]
@gnn: Is there any progress concerning this task? If you like, I can take this over. 
Just let me know if you want me to do so and whether you already implemented something I could make use of.
