### ISSUE TITLE
demand.egon_sites_ind_load_curves: p_set-timeseries is constant value

### ISSUE THREAD

**Issue by KathiEsterl** [openego/eGon-data#429]
While trying the function to calculate the industrial sites' p_set timeseries for DSM, we noticed that the results are timeseries with a constant value instead of 'real' timeseries. 

The relevant function is here: [https://github.com/openego/eGon-data/blob/212654065bb3d679a2dc1b1d8d2369ddae809674/src/egon/data/datasets/industry/temporal.py#L218](url)

**Comment by IlkaCu** [comment]
Unfortunately I won't be able to tackle this before next week. Maybe @ClaraBuettner can support in case it needs to be solved quickly.

**Comment by ClaraBuettner** [comment]
As described in https://github.com/openego/eGon-data/pull/438#issuecomment-916185052 this is not a bug. The load curves of some industrial branches are a constant line according to demandRegio.
