### ISSUE TITLE
Missing table "grid.egon_mv_grid_district"

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#432]
All tasks depending on the mv_grid_districts failed in a local run. 
I think this was caused because the version number of the mv grid dataset was not updated in #407 . In my case, the task was skipped but I still have the old table `grid.mv_grid_district.`

**Comment by nesnoj** [comment]
Thanks for reporting! Indeed, we missed that :-/
Yes I guess it only occurs when the task is skipped as it ran it successfully in the weekend branch...
I prepared a fix in #433, I hope this is sufficient (the prefix stuff was quite complicated as there're so many dependencies... thanks @nailend)
