### ISSUE TITLE
Assign HH demand profiles to buildings

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#435]
Each building in table `openstreetmap.osm_buildings_filtered` (created in #262/#430, not available in dev yet) needs to get assigned profiles from table `demand.egon_household_electricity_profile_in_census_cell`.

Notes
- [x] New table `demand.egon_household_electricity_profile_in_building` with `osm_id` and `building_profile_ids` (same format as in `demand.egon_household_electricity_profile_in_census_cell`'s `cell_profile_ids`)
- [x] For the mapping of buildings to zensus cells, you can use table `boundaries.egon_map_zensus_buildings_filtered` (currently only available in branch `features/#262-preprocess-osm-buildings-amenities` #430 as well as in the weekend branch)
- [x] Distribute randomly, it is more important that every building gets a profile than one gets multiple profiles
- [ ] (nice-to-have: can we easily consider the buildings' area?)
- [x] If no. of profiles < no. of buildings: ok for now, some buildings don't get a profile assigned as not all buildings are residential
- [x] If no. of profiles > no. of buildings: ok
- [ ] <s> If no. of profiles >> no. of buildings: we have to create some virtual buildings. To start, check with column `building_count` in table `society.egon_destatis_zensus_apartment_building_population_per_ha` if we have at least zensus data on the no. of buildings. We have to discuss further steps here..</s>
- [ ] Challenge: how to cope with cells without profiles? #431
- [x] Please integrate into hh demand task
- [x] Add peak load to building by summing up the profiles and use max

**Comment by nailend** [comment]
The first implementation will do:
- reduce to zensus cells which have profiles and buildings
- distribute all existing profiles randomly to buildings even if not the same amount
- if more buildings, some will get no profile
- if less buildings, some will get multiple profiles
- zensus cell without buildings but profiles will be extracted
- synthetic buildings will be generated
- if the rate of profiles/buildings is very high, additional buildings will be generated

**Comment by nesnoj** [comment]
Sounds good!

I checked the region of Kiel and it looks as if the ratio is 1-2 in rural areas (which makes sense due to single-/two-family houses) and increases in urban areas. Ther're some red (rate: >20) areas in the suburbs, e.g. [Kiel Mettenhof](https://goo.gl/maps/GeNzzvPZMv6SFobr5) which has quite a lot of high buildings with many apartments, so at first sight it looks plausible to me.
But that's just a first fast sample..

![grafik](https://user-images.githubusercontent.com/15910173/136550729-3650a498-3f97-4c82-8006-24021adc61b2.png)

**Comment by nailend** [comment]
![grafik](https://user-images.githubusercontent.com/51374526/137933170-6314128d-6ad8-49d6-aea7-b1fc0c95cfe8.png)

Example for "Pülsen"

**Comment by nailend** [comment]
The following picture shows the boarder of Schlweswig-Holstein and Hamburg. Apparently the borders of the osm_ids are blurred and a few buildings are associated to SH. So far, this does not lead to any problems as the osm_ids are matched to census cells via `ST_Within' of building centroid and census cell polygon. But in the edge case of, existing osm_id but not zensus profiles but population this might come up again (#431)

![Clipboard - 30  Oktober 2021 22_07](https://user-images.githubusercontent.com/51374526/139853904-8dd11ae7-9580-477c-8c5d-b727b24a9739.png)

**Comment by nesnoj** [comment]
> The following picture shows the boarder of Schlweswig-Holstein and Hamburg. Apparently the borders of the osm_ids are blurred and a few buildings are associated to SH

As explained in the last weekly, this is probably due to the fact that in the state extracts of OSM there's no hard clipping at the borders but areas near the borders are retained (in this case maybe buildings somehow associated to the landuse areas)... so this shouldn't be a problem.

**Comment by nailend** [comment]
> The first implementation will do:
>     *  <s> if the rate is high (>5), additional synthetic buildings will be generated (need for differentiation of urban/rural)    </s> further analysis needed, see example picture

There is quite some deviation in zensus and osm data which can partially be explained by different counting methods. As one house in osm data can be counted  as multiple buildings in zensus depending on the number of house entrances, etc

![grafik](https://user-images.githubusercontent.com/51374526/140649027-b437f5d8-3d0d-48c8-b9ab-8730f7596b47.png)

For simplicity, synthetic buildings are initially created only for cells without osm-data.  The following image shows the difference in data for the marked cell, which has no synthetic buildings because there are osm-marked buildings. The cells around the marked cell have no osm-marked buildings and therefore have synthetic buildings derived from census building data.

![grafik](https://user-images.githubusercontent.com/51374526/140648542-abfb44a4-6b7c-4a1e-85b1-e552560b5710.png)

**Comment by fwitte** [comment]
Hi,
just tested the current state of the CI branch on my machine and this error appeard on the hh_demand_buildings.map-houseprofiles-to-buildings:

```
CONTEXT:  COPY osm_buildings_synthetic, line 1, column geom_point: "POINT (4359437.579471766 3362419.739079922)"
Traceback (most recent call last):
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/hh_demand_buildings.py", line 348, in map_houseprofiles_to_buildings
    synthetic_buildings.to_postgis(
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1808, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/geopandas/io/sql.py", line 431, in _write_postgis
    gdf.to_sql(
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/pandas/core/generic.py", line 2872, in to_sql
    sql.to_sql(
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/pandas/io/sql.py", line 717, in to_sql
    pandas_sql.to_sql(
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/pandas/io/sql.py", line 1761, in to_sql
    sql_engine.insert_records(
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/pandas/io/sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/pandas/io/sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/geopandas/io/sql.py", line 312, in _psql_insert_copy
    cur.copy_expert(sql=sql, file=s_buf)
psycopg2.errors.InvalidParameterValue: Geometry SRID (0) does not match column SRID (3035)
CONTEXT:  COPY osm_buildings_synthetic, line 1, column geom_point: "POINT (4359437.579471766 3362419.739079922)"
```
Seems like just a forgotten .set_crs() on some dataframe, or the lateste version is not yet merged into CI. Just in case you wanted to fix it before the weekend :).

Have a nice weekend

**Comment by nesnoj** [comment]
Thanks @fwitte for reporting!
@nailend do you have time to fix this today? I'm not familiar with the current state in the ci branch..

**Comment by nailend** [comment]
@fwitte Thanks for the hint. As you already mentioned, the CI-Branch does not have the current version. @nesnoj This problem should already be fixed.

**Comment by fwitte** [comment]
Great, have a nice weekend!
