### ISSUE TITLE
Number of HH demand profiles does not match zensus' number of HH

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#437]
As discussed via phone.

Example:
- grid_id: 100mN35178E42938
- count of HH in `egon_destatis_zensus_household_per_ha`: 7
- count of profiles in `egon_household_electricity_profile_in_census_cell`: 15

**Comment by nailend** [comment]
Are you sure its this way and not the other way around?
destatis data is telling the amount of people living in households and there is one profile per household.
So normaly the destatis HH count should be higher the the amount of profiles

**Comment by nailend** [comment]
If I ask the db with:
```SELECT * FROM society.egon_destatis_zensus_household_per_ha
WHERE grid_id = '100mN35178E42938' AND attribute = 'INSGESAMT'
```
I get 16 households. There might be sth wrong with your count. But its still one off because of the secrecy-reason thing, which we already discussed [here](https://github.com/openego/eGon-data/pull/260#issuecomment-886671238) and should be fixed already....

**Comment by nailend** [comment]
If I remember right, we decided to only create data for missing cells but not correct the number of households for existing cells as the assumed that it would not affect the aggregated load-profiles as they are scaled with demand-regio data anyways.
At this point, we probably did not think about mapping the profiles to the OSM polygons which do also deviate from the zensus data, don't they?

**Comment by nailend** [comment]
> If I remember right, we decided to only create data for missing cells but not correct the number of households for existing cells as the assumed that it would not affect the aggregated load-profiles as they are scaled with demand-regio data anyways.
> At this point, we probably did not think about mapping the profiles to the OSM polygons which do also deviate from the zensus data, don't they?

*drawbacks and limitations* are currently stating:
```
* Census data with attribute 'HHTYP_FAM' is missing for some cells with small
 amount of households. This data is generated using the average share of household types
  for cells with similar household number
```

I would prefer to stay with the current situation but change it to:
```
* Census data with attribute 'HHTYP_FAM' is missing for some cells with small
 amount of households. This data is generated using the average share of household types
  for cells with similar household number. For some cells the summed amount of households
per type deviates from the total number with attribute 'INSGESAMT'. As the profiles are scaled
with demand-regio data at nuts3-level the impact at a higher aggregation level is negligible.
For sake of simplicity, the data is not corrected
```

**Comment by nesnoj** [comment]
> I get 16 households. There might be sth wrong with your count.

Yes, I did not set a filter so the last entry in the table was shown with wrong attribute. I also have 16 for `INSGESAMT`. My bad, I'm happy that I made a mistake here :relieved: 

>But its still one off because of the secrecy-reason thing, which we already discussed here and should be fixed already....

Ah, right, I totally forgot about that. Let's keep this as it is, even if the sum of `HHTYP_FAM` deviates slightly from `INSGESAMT`.

> I would prefer to stay with the current situation but change it to:

Yes! I like your description, please change it and close this issue.
