### ISSUE TITLE
Scenario datasets to be published in the WebApp

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#447]
As shown in the [WebApp](https://egon.rl-institut.de/) there're 2 main sections:
1. **Scenarios:** static input data generated by the pipeline for both target scenarios eGon2035 and eGon100RE
-> for all datasets (except category "Data model") 2 datasets are required, the data shown is controlled by the scenario switch
2. **Results:** results from our calculations (subject to #448)

This issue is to collect all datasets for 1. we want to publish. Each dataset in the list below will become one entry (with switch) with a specific data type (polygon, point, line, [choropleth map](https://en.wikipedia.org/wiki/Choropleth_map)). The list below is a first proposal and needs your input. **Please drop your ideas as comment below, I'll update the list regularly.**

Beside the layer switches, it will be possible to create plots in the left menu, I added some ideas to the list.
__________________________

### Boundaries
(country, federal states, districts, municipalities) are always shown in the app depending on the zoom level.

### Base data
- [ ] population on NUTS3 as choropleth, number of households as pop up

### Demand
Electricity
- [ ] *Layer switch:* Electricity HH on MV grid district level (annual demand as choropleth map, min/max as pop up)
- [ ] *Layer switch:* Electricity CTS on MV grid district level (annual demand as choropleth map, min/max as pop up)
- [ ] *Layer switch:* Electricity IND on MV grid district level (annual demand as choropleth map, min/max as pop up)

Heat 
- [ ] *Layer switch:* Heat (individual heating) HH on MV grid district level (annual demand as choropleth map, min/max as pop up)
- [ ] *Layer switch:* Heat (individual heating) CTS on MV grid district level (annual demand as choropleth map, min/max as pop up)
- [ ] *Layer switch:* Heat (district heating) HH+CTS per district heating area (annual demand as choropleth map, min/max as pop up)

Gas

- [ ] *Layer switch:* CH4 IND (annual demand as choropleth map, min/max as pop up)
[Polygons: grid.egon_voronoi_ch4]
- [ ] *Layer switch:* H2 IND (annual demand as choropleth map, min/max as pop up)
[Polygons: grid.egon_voronoi_h2_grid]

Transport
- [ ] *Layer switch:* Transport (motorized individual travel) [Number of EVs as choropleth map, types of EVs in pop up]
- [ ]  *Layer switch:* Transport (motorized individual travel) [Annual charging demand as choropleth map, maximum charging in uncontrolled case in pop up, maximum available charging power (flexibel and inflexibel) in pop up]
- [ ] *Layer switch:* Transport (heavy-duty transport) [annual H2 demand as choropleth map]
[Polygons: grid.egon_voronoi_h2_grid]

Plots
- [ ] *Plot:* Demand for all 4 sectors above for Germany [barplot or stacked barplot] - time series plot from Clara would also be nice

### Supply
Wind Onshore
- [ ] *Layer switch:* Installed capacity wind [choropleth map]
- [ ] *Layer switch:* Produced energy wind [choropleth map]
- [ ] *Layer switch:* wind turbines [points]
- [ ] *Layer switch:* Potential areas wind [polygons]

Wind Offshore (grid connection point)
- [ ] *Layer switch:* Installed capacity wind [choropleth map]
- [ ] *Layer switch:* Produced energy wind [choropleth map]
- [ ] *Layer switch:* wind turbines [points]

PV ground
- [ ] *Layer switch:* Installed capacity PV ground [choropleth map]
- [ ] *Layer switch:* Produced energy PV ground [choropleth map]
- [ ] *Layer switch:* PV ground systems [points]
- [ ] *Layer switch:* Potential areas PV ground [polygons]

PV roof
- [ ] *Layer switch:* Installed capacity PV roof [choropleth map]
- [ ] *Layer switch:* Produced energy PV roof [choropleth map]
- [ ] *Layer switch:* PV roof systems [points]

Gas

Warning: the potential that can be used across the year is limited by a contraint (later on in eTraGo), the value of the limitation is to be found in scenario.egon_scenario_parameters (gas_parameters: "max_gas_generation_overtheryear")
- [ ] *Layer switch:* Potential natural gas production (CH4) [choropleth map] (eGon2035 only)
- [ ] *Layer switch:* Potential biogas production (CH4)  [choropleth map] (eGon2035 and eGon100RE)

Other power plants
- [ ] *Layer switch:* Installed capacity gas fired pp (includes biogas) [choropleth map] (Thermal capacity in pop up)
- [ ] *Layer switch:* Installed capacity biomass fired pp [choropleth map] (Thermal capacity in pop up)
- [ ] *Layer switch:* Installed capacity hydro pp [choropleth map]
- [ ] *Layer switch:* Installed capacity other pp [choropleth map] (Thermal capacity in pop up, not specify carrier as it is mostly other)

Plots
- [ ] *Plot:* Installed capacity for all types above for Germany [barplot] + Wind and PV potential feed-in

### Grids
Electricity (Status Quo)
- [ ] *Layer switch:* EHV grids [lines] (overhead/underground, parallel lines, voltage level, s_nom in pop up)
- [ ] *Layer switch:* EHV/HV stations [points] (voltage levels)
- [ ] *Layer switch:* HV grids [lines]  (overhead/underground, parallel lines, voltage level, s_nom in pop up)
- [ ] *Layer switch:* HV/MV stations [points] (voltage levels)
- [ ] (*Layer switch:* MV and LV grids - nice-to-have as we might suggest )

Gas
- [ ] *Layer switch:* CH4 grid [lines] (eGon2035) (p_nom in MW)
- [ ] *Layer switch:* CH4 grid and H2_retrofit grid [lines] (eGon100RE, these both grids do have the same topology, p_nom in MW)
- [ ] *Layer switch:* H2 potential extension grid [lines] (carrier: "H2_gridextension", p_nom is 0 but they do have a topology)

### Flexibility Potential
Gas
- [ ] *Layer switch:* CH4 stores [choropleth map or points] (e_nom in MWh)
- [ ] *Layer switch:* Potential H2 underground storage [choropleth map or points]  (e_nom_max in MWh)

Electricity
- [ ]  *Layer switch:* DSM potential [choropleth map]
- [ ] DLR?
- [ ] Electromobility - delta soc min und max

Plot?

### Data model
- [ ] *Layer switch:* Medium-voltage grid districts [polygons]
- [ ] *Layer switch:* Load areas [polygons] annual electricity demand sum, population and annual demand per sector in pop up
- [ ] *Layer switch:* Load areas [polygons] annual heat demand sum, population and annual demand per sector in pop up
- [ ] *Layer switch:* Zensus cells [polygons]

### Sector coupling 
- [ ] *Layer switch:* Central and rural heat pumps
- [ ] ...

**Comment by ClaraBuettner** [comment]
For the heat demands, I would show the annual demands. If we want to show the seasonality, we could additional show a plot of the heat demands over the year, or do this for all carriers, e.g. like this: 
![load_timeseries_de](https://user-images.githubusercontent.com/22964326/218410639-0d60d3be-95ea-4cac-a90f-db3e35d3548e.png)
We could also add a polygon layer for our district heating grids. 

Flexibility options of the electricity sector (DSM, DLR) are currently not on this list. Do we want to keep it like this?
