### ISSUE TITLE
Update OSM dataset

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#486]
Update OSM (currentl 01.01.2021) to a newer version, cf. https://github.com/openego/eGon-data/issues/435#issuecomment-952654765 to have a recent building dataset available.

May lead to osmTGmod issues, integration needs to be checked thoroughly.

**Comment by nesnoj** [comment]
Results from run on fresh installation:

Initially the task `osmtgmod.run` failed with new OSM data:
`psycopg2.errors.InvalidParameterValue: Geometry type (Point) does not match column type (LineString)`

[Full log](https://github.com/openego/eGon-data/files/7903742/egon-data-processing-pipeline_osmtgmod.run_2022-01-18T12.35.33.419798%2B00.00_1.log)

Apparently the manual fix for Garenfeld #245 was not applied due to the condition:
https://github.com/openego/eGon-data/blob/fd3eb54c0122a483f370a46ec28dfb9cf1892614/src/egon/data/datasets/osmtgmod/__init__.py#L184-L214

After changing it to "germany-22" the task ran successfully :airplane: .
The other tasks as well except for those ones failing before too (al least on my end, e.g. `electrical_neighbours.grid`).

@ClaraBuettner @ulfmueller 
You said you could check the grid model, what's your preferred format for the `grid.egon_etrago_*` tables? .csv , .backup , ..?

**Comment by ClaraBuettner** [comment]
> @ClaraBuettner @ulfmueller You said you could check the grid model, what's your preferred format for the `grid.egon_etrago_*` tables? .csv , .backup , ..?

I would prefer a backup of the `grid.egon_etrago_` tables

**Comment by nesnoj** [comment]
I've sent you a link to the backup file via mail..

**Comment by nesnoj** [comment]
You wrote that you experienced problems with the new OSM dataset, are there any new findings here?

**Comment by ClaraBuettner** [comment]
@nesnoj: Have you already created a branch for the OSM update?

**Comment by nesnoj** [comment]
> > @nesnoj: Have you already created a branch for the OSM update?
> 
> I think so, gimme a sec...

No, just tested manually.
I think the only things that have to be adjusted are the files to `germany-220101.osm.pbf` / `schleswig-holstein-220101.osm.pbf`:
https://github.com/openego/eGon-data/blob/ee5cd59e95344e58102e0fb70da8202d7b65ba7c/src/egon/data/datasets.yml#L1-L10
...and your manual handling.
If I'm not mistaken the metadata is adapted automatically..

**Comment by nesnoj** [comment]
Any updates here?
