### ISSUE TITLE
Missing CRS in vg250

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#490]
I ran into some pipeline errors as the geometry of the vg250 tables didn't have a crs set while getting uploaded to the db.
As described in the [metadata](https://github.com/openego/eGon-data/blob/73865d0715b1152eebb6c1c236af9a9feeb367e1/src/egon/data/datasets/vg250/__init__.py#L428) the srid should be `4326`.

Therefore I recommend to add the srid to the geometry-definition while uploading to postgres [here](https://github.com/openego/eGon-data/blob/73865d0715b1152eebb6c1c236af9a9feeb367e1/src/egon/data/datasets/vg250/__init__.py#L106)

**Comment by nesnoj** [comment]
That's odd. When I load `boundaries.vg250_gem` or `boundaries.vg250_krs` in QGIS it shows 4326 as CRS.
Could you please post the error message? And what code raises the error?

(BTW, there're many occurrences where the dtype is exactly set with `dtype={"geometry": Geometry()}` without errors in the pipeline.)

**Comment by nailend** [comment]
Sorry, didn't keep the log and now wasn't able to reconstruct this error after new db-setup.

**Comment by nesnoj** [comment]
Please close this one if outdated @nailend
