### ISSUE TITLE
Integrate DemandRegio disaggregator

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#5]
The DemandRegio data needs to be integrated in egon-data, this can be done by either integrating the DemandRegio Disaggregator or importing the resulting data sets. 
* check if the Ffe Opendata website also provides resulting data set or input data only 
* right now we have a tendency to integrating the tool

**Comment by IlkaCu** [comment]
The ffe dataplatform does not provide resulting data from the disaggregator. Thus we should integrate the disaggregator itself into our workflow.
List of data we like to extract from the disaggregator on NUTS-3 level: 
- el. consumption of private households 
- el. consumption of commercial sector 
- el. consumption of industry differentiated by industrial sectors
- population

**Comment by IlkaCu** [comment]
@wheitkoetter and @EvaWie: Could you please list the DemandRegio data you need?

**Comment by IlkaCu** [comment]
As soon as we have a complete list of required data we should discuss which of the data sets should be stored in db tables. In case the data will be further processed using we can create it on demand.

**Comment by wheitkoetter** [comment]
@IlkaCu We plan to derive the spatially and temporally resolved gas load from the heat demand, which is determined in FL, and also want to use the industrial facility locations which are used by FL (both already discussed with Clara and Eva). Thus most likely we will not need demand regio data. For this reason for us in OL there is no explicit need that demandregio data are integrated into the db (if FL needs such data we might indirectly also use them).

**Comment by IlkaCu** [comment]
For calculating the electricity consumption per household two methods are available.

> Using population invokes a top-down-method, i.e. the overall electricity consumption of entire Germany is being spread by distribution keys based on the population to calculate the consumption per region.
Using households invokes a bottom-up-method, i.e. the average electricity consumption known for each household size are used for calculating the consumption per region.

But only the bottom-up-method is available for the year 2050. Therefore I suggest to rely on this method for both scenario years.

**Comment by IlkaCu** [comment]
We forked the disaggregator repo to adjust and integrate the tool in our egon-data workflow.

**Comment by IlkaCu** [comment]
Planned adjustments:
* reduce input values for el. consumption of private hh to meet numbers from JRC 
*

**Comment by ClaraBuettner** [comment]
> Planned adjustments:
> 
>     * reduce input values for el. consumption of private hh to meet numbers from JRC
> 
We might not do this because the values without DHW are already close to the one from JRC. I excluded the DWH demands in this branch of the disaggregator: https://github.com/openego/disaggregator/tree/features/adjustments_hh 


>     * adjust code to be able to change the year within the function instead of config file
This is already included in the latest version of the disaggregator.
