### ISSUE TITLE
The updated saline structurual data is available

### ISSUE THREAD

**Issue by fwitte** [openego/eGon-data#522]
I received a shapefile containing the data shown in the figure 7-1 of the report (see below).

![grafik](https://user-images.githubusercontent.com/20252362/142440853-b16a7d33-0fef-44b4-afaa-3686beb794a0.png)

We can filter the data according to the categories of the legend supplied, therefor an update should be made. I suggest first merging #478 and updating in a new pull request.

I was not (not yet) able to find the data with the respective storage potential assessment information (eligibleor not, no numbers) in the download center of the bgr, therefore we might need to request permission to upload the shapefile to the databundle.

**Comment by fwitte** [comment]
Requested permission, we can upload the data with the appropriate references (InSpEE-DS report, BGR/Geoviewer).

@IlkaCu: Can we update the data-bundle soon?

**Comment by IlkaCu** [comment]
> Requested permission, we can upload the data with the appropriate references (InSpEE-DS report, BGR/Geoviewer).
> 
> @IlkaCu: Can we update the data-bundle soon?

I was planning to update the data-bundle today or tomorrow anyways. Please update the files and description on the NC.

**Comment by fwitte** [comment]
I'll let you know, when the data is uploaded. This will also require a change in the #478 workflow as the data structure changed.

**Comment by fwitte** [comment]
Changes have been made, will be merged into CI if data is available in databundle.
