### ISSUE TITLE
Migrate /processing/loadarea/ to datasets

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#525]
The creation of load areas must be moved to datasets.

**Comment by nesnoj** [comment]
Thanks for your efforts @IlkaCu but the loadareas cannot be simply migrated (they can, but it does not make much sense to me).
As the underlying data has completely changed methods are changing too (e.g. #250). We're working on this..

**Comment by IlkaCu** [comment]
Does it hinder your work to have the old stuff integrated in the datasets structure? I wanted to finally get rid of the processing and importing folders. 
If it causes any problems on your side, I can revert my changes easily.

**Comment by nesnoj** [comment]
No, go ahead :)
