### ISSUE TITLE
Move gas related scripts from processing to datasets folder

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#528]
Please move the scripts

- [gas_areas.py](https://github.com/openego/eGon-data/blob/dev/src/egon/data/processing/gas_areas.py)
- [power_to_h2.py](https://github.com/openego/eGon-data/blob/features/%23527-move-plotting-function-to-district-heating-dataset/src/egon/data/processing/power_to_h2.py)

from the processing to the datasets folder and adjust the scripts accordingly.

**Comment by IlkaCu** [comment]
On the CI branch there is an additional script which should be moved to the datasets folder: [h2_to_ch4.py](https://github.com/openego/eGon-data/blob/continuous-integration/run-everything-over-the-weekend/src/egon/data/processing/h2_to_ch4.py)

**Comment by fwitte** [comment]
Good points, will move the stuff.

**Comment by AmeliaNadal** [comment]
I made the requiered changes in the branch features/#474-insert-hydrogen-infrastructure which should be merged soon (PR https://github.com/openego/eGon-data/pull/478).

**Comment by fwitte** [comment]
All scripts have been moved in #478
