### ISSUE TITLE
Having both a `table_prefix:` configured and using in the `output_tables:` is unnecessary

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#53]
Having both a `table_prefix:` configured and using in the `output_tables:` is unnecessary and it would probably be better to only have the prefix and the table names and always generate the complete table name by merging prefix and table name. This is also evidenced by the fact that we split this name again [later][0], when we could just use the file name if it would be configured that way.
Another nuance: all these file names are only `output_tables:` because the source tables get directly copied as is to the target schema.

[0]: https://github.com/openego/eGon-data/blob/1da746659c1a04940d7c42a6a58980cefc537f8f/src/egon/data/importing/openstreetmap/import_osm.py#L155

_Originally posted by @gnn in https://github.com/openego/eGon-data/pull/31#discussion_r524858375_

**Comment by nesnoj** [comment]
Outdated
