### ISSUE TITLE
Integrate the gas turbines into the eTraGo tables

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#548]
The gas turbines are distributed in [power_plants.non_chp_conventional.](https://github.com/openego/eGon-data/blob/dev/src/egon/data/datasets/power_plants/conventional.py). Since they are modeled as link components between CH4 and AC buses, the integration into the eTraGo tables differs from the one for other power plants.

**Comment by fwitte** [comment]
@IlkaCu: Can you give me a brief overview on the power plant structure in the db? This would facilitate/speed up the implementation on my side :).
