### ISSUE TITLE
Insert cost assumptions from NEP and technology-data to scenario_parameters

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#549]
Fuel and CO2 prices will be added to the scenario parameters table according to table 6 in NEP 2035, Version 2021, 1. Entwurf (S.39).
Other marginal and capital costs are taken from technology-data repository

**Comment by fwitte** [comment]
Just a reminder for myself: these information might be relevant for CH4/biogas import as well @AmeliaNadal, I will put in on my todo list.

**Comment by ClaraBuettner** [comment]
FOM costs are part of the investments costs in pypsa-eur-sec (see here: https://github.com/openego/pypsa-eur-sec/blob/40cd0447f73a605c71b39576430739bbfb595667/scripts/prepare_sector_network.py#L666).
