### ISSUE TITLE
Integrate eMobility: motorized individual travel

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#553]
- [x] add MIT trips to datapackage #602
- [x] write trip pool to DB
- [x] add reqd. params to scenario table
- [x] obtain RS7 and KBA data, handle missing entries
- [x] merge muns, RS7, KBA data
- [ ] nice-to-have: improve vehicle segment distribution by KBA fz12
- [x] allocate EV numbers pop-weighted to different spatial levels: reg. districts, muns, MVGDs
- [x] draw from pool and assign to MVGDs
- [x] support test mode
- [x] generate model timeseries: load, availability, DSM profile, static params

**Comment by nesnoj** [comment]
One more question @ClaraBuettner concerning the filling of eTraGo tables:
Are there task dependencies I should rely on beside `EtragoSetup`? I could imagine that there might be concurring tasks writing to eTraGo tables which is a problem when using `next_etrago_id()`? (even if it's unlikely tasks could get the same max id)

**Comment by nesnoj** [comment]
@ulfmueller @ClaraBuettner 
While preparing the model data I found "land transport EV" already being a carrier in `grid.egon_etrago_load` - looks exactly like the [one used by p-e-s](https://github.com/openego/pypsa-eur-sec/blob/40cd0447f73a605c71b39576430739bbfb595667/scripts/prepare_sector_network.py#L1098-L1103). What task creates those ones? Are they placeholders? Can we drop it?

**Comment by ClaraBuettner** [comment]
> One more question @ClaraBuettner concerning the filling of eTraGo tables: Are there task dependencies I should rely on beside `EtragoSetup`? I could imagine that there might be concurring tasks writing to eTraGo tables which is a problem when using `next_etrago_id()`? (even if it's unlikely tasks could get the same max id)

You don't need an additional dependency for writing into the tables. There might be conflicts with `next_etrago_id()` (see #514 ) but we didn't run into them up to now and therefore didn't come up with a solution yet.

**Comment by ClaraBuettner** [comment]
> @ulfmueller @ClaraBuettner
> 
> While preparing the model data I found "land transport EV" already being a carrier in `grid.egon_etrago_load` - looks exactly like the [one used by p-e-s](https://github.com/openego/pypsa-eur-sec/blob/40cd0447f73a605c71b39576430739bbfb595667/scripts/prepare_sector_network.py#L1098-L1103). Also, there're TS on those in `grid.egon_etrago_load_timeseries`. Same for the other emob components such as BEV charger in `grid.egon_etrago_link`...
> 
> As agreed on before, I wanna replace the p-e-s export by my data. What task creates the data above?

These are the mobility loads of foreign countries, we copied all foreign loads from pypsa-eur-sec. 
If you also have data for the other countries, it could be also an option to overwrite the data for pypsa-eur-sec and keep the copy function in egon-data.

**Comment by nesnoj** [comment]
> 
> You don't need an additional dependency for writing into the tables. There might be conflicts with `next_etrago_id()` (see #514 ) but we didn't run into them up to now and therefore didn't come up with a solution yet.

I see, guess most tasks bulk-write new components using pandas and this probably won't rise problems as all data is committed before the next task starts. However, my task takes a couple of hours. It iterates over grid districts and creates components per grid district. So there's a higher probability of conflicts. I see if I can switch to bulk-insert or a fallback if an id already exists.

**Comment by nesnoj** [comment]
> These are the mobility loads of foreign countries, we copied all foreign loads from pypsa-eur-sec. If you also have data for the other countries, it could be also an option to overwrite the data for pypsa-eur-sec and keep the copy function in egon-data.

To get this right: we have 2 places where this data is held, right?
1. for the scenario generation via p-e-s: currently original data from p-e-s (data bundle), will be replaced a soon as you provide some location it shall be exported to @ClaraBuettner . So the tables from 2. are not used here, correct?
2. for eTraGo run only: in tables `grid.egon_etrago_*`. By which task are they created?

I do not have data but I'd tend to scale my timeseries by the amount of EV per country. I'll get back to this in tomorrow's session.

BTW, the buses in `grid.egon_etrago_bus` seem to be at wrong locations: the (all?) p-e-s ones are located near Africa, the one in SH was created by me:

![image](https://user-images.githubusercontent.com/15910173/149907230-8d0f01c2-2253-423e-9ab3-3c41f4d47315.png)

Ah, just saw that @fwitte created an issue on this: #640 :smile_cat:

**Comment by nesnoj** [comment]
Quick question @ClaraBuettner: In some grid districts there are no EV in some scenarios (e.g. 6 in eGon2035).
Currently, my code does not create any components in the eTraGo tables for those MVGDs. I assume this ok with your model - or does this induce problems?

**Comment by ClaraBuettner** [comment]
> Quick question @ClaraBuettner: In some grid districts there are no EV in some scenarios (e.g. 6 in eGon2035). Currently, my code does not create any components in the eTraGo tables for those MVGDs. I assume this ok with your model - or does this induce problems?

Yes, that is ok with our model.
