### ISSUE TITLE
The gas voronoi creation fails with buses inserted outside of German borders

### ISSUE THREAD

**Issue by fwitte** [openego/eGon-data#560]
After adding the eGon100RE bus data for the European neighbors (from pypsa-eur-sec), the gas_areas.create-voronoi tasks fail. The gas voronois should be created based on the buses in Germany only, therefore we need to exclude the European neighbor buses from buses to create the voronois on. At the moment, we can do this by filtering for 'eGon2035' in the scn_name column, this will however only work temporarily.

I have two solutions in mind:
- We rename carrier of the gas buses of European neighbors to something like `H2_FR`, `H2_BE`, .... This way, we can filter for scn_name and carrier.
- After filtering the buses for scn_name we add a routine to check which of those buses are in Germany and which not.

What do you think @AmeliaNadal, @ClaraBuettner, @ulfmueller, @IlkaCu? Rocket emoji for first solution, thumbs up for second solution, comment for other solution :).

**Comment by fwitte** [comment]
After we have decided, I will make the changes accordingly. For now, I add the temporary fix mentioned above to make CI run this weekend :).

**Comment by ClaraBuettner** [comment]
When the neighboring countries were integrated we introduced a column for the country name in `grid.egon_etrago_bus`. So I would vote for using this column to filter all H2 buses in Germany.

**Comment by IlkaCu** [comment]
@ClaraBuettner's suggestion seems to be the easiest one to me. 
But in general I would leave decisions like this to you, as the ones being responsible for the code implementation, especially in cases like this, where the output should be the same for all options.

**Comment by fwitte** [comment]
Okay, that sounds very good. Then I will simply filter by country :)
