### ISSUE TITLE
Missing filters in data processing for gas data

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#567]
To fullfil the commit https://github.com/openego/eGon-data/pull/478/commits/4b8589ce0dab0df9973b7a27f11fb16ac5dcb8f6, add scanario filter in https://github.com/openego/eGon-data/blob/dev/src/egon/data/datasets/industrial_gas_demand.py.

**Comment by fwitte** [comment]
- [ ] To fullfil the commit 4b8589c, add scanario filter in https://github.com/openego/eGon-data/blob/dev/src/egon/data/datasets/industrial_gas_demand.py.
- [ ] Filters for deletion from egon_etrago_store/link/... are missing. We can implement it like so https://github.com/openego/eGon-data/commit/7a4dddf8b492fd5cb86e2c759244885fb2f80b34.
