### ISSUE TITLE
Adjust p-e-s carriers to eGon carriers for eGon100RE scenario

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#575]
p-e-s makes use of a different carrier naming than we used to do it in the eGon project. This needs to be adjusted for the eGon100RE scenario.

**Comment by ClaraBuettner** [comment]
The carrier for supply.egon_scenario_capacities are adjusted here: 

https://github.com/openego/eGon-data/blob/ed8ee0777c769c53a91397e1a5106d35749b6eb1/src/egon/data/datasets/scenario_capacities.py#L517-L595

In 409cf38ccd6c564b9cbe7d7ec11dcaf2b079f6a0 the reservoir capacities are renamed as well

**Comment by IlkaCu** [comment]
We agreed on applying the carrier names from eGon2035 in the eGon100RE scenario (Germany and abroad), too.
