### ISSUE TITLE
Integrate electricity storages for eGon100RE in etrago tables

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#581]
Integrate electricity storages for eGon100RE in etrago tables

**Comment by ClaraBuettner** [comment]
Pumped hydro capacities abroad for eGon2035 are added here: 
https://github.com/openego/eGon-data/blob/eb4ec505e3c14b7f48dd72175711ec1f2fade8db/src/egon/data/datasets/electrical_neighbours.py#L944-L1003

**Comment by IlkaCu** [comment]
Parameters on efficiency are missing for pumped_hydro plants in foreign countries.
