### ISSUE TITLE
Potential areas outside of Germany

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#592]
One of the pv ground mounted plants for eGon100RE is allocated to a potential area outside of Germany (blue line): 
![image](https://user-images.githubusercontent.com/22964326/146889043-45c600c7-56cc-40e0-8755-4b636e26269f.png)
I think we should cut the potential areas at the border.
@nesnoj: Can I add this to your `re_potential_areas` dataset? I could also update PowerPlants but I would prefer to cut the potential areas directly before inserting them into the database.

**Comment by nesnoj** [comment]
Uh, that's odd! Thanks for this observation!
I found out why this happens.
I'll could add a clipping but I wanted to update the dataset in any case, so I'll consider this issue.

Is it time-critical for you?

**Comment by ClaraBuettner** [comment]
> Uh, that's odd! Thanks for this observation! I found out why this happens. I'll could add a clipping but I wanted to update the dataset in any case, so I'll consider this issue.
> 
> Is it time-critical for you?

The dev and CI branch currently fail for ` dataset-boundary=='Everything'` because of this issue. It would be good to have a running dev branch, so I would prefer to fix this soon/before the next CI-run. 
I manually fixed this for the latest CI run by inserting only data for eGon2035, I could also commit that as an intermediate bugfix.

**Comment by nesnoj** [comment]
> I manually fixed this for the latest CI run by inserting only data for eGon2035, I could also commit that as an intermediate bugfix.

Sorry for this extra work.
No, I'll take care asap #595
