### ISSUE TITLE
Update RE potential areas

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#595]
Update data added in #124 to
- include latest data
- fix critical #592

**Comment by nesnoj** [comment]
Some stats fyi @ClaraBuettner:

**Current dataset**
- `potentialarea_pv_road_railway`:
area: 4990 sqm, installable power: 499 GW
- `potentialarea_pv_agriculture`:
area: 7041 sqm, installable power: 704 GW

**New dataset**
- `potentialarea_pv_road_railway`:
area: 1132 sqm, installable power: 113 GW
- `potentialarea_pv_agriculture`:
area: 6341 sqm, installable power: 634 GW

(assuming 100 MW/sqkm for power values)

As you can see the agri areas didn't change much. The most important change in the new data is the restriction of the max. soil quality for `potentialarea_pv_road_railway` to exclude areas with high soil quality in those areas (as in agri).
Studies give different values for the min. required installed capacity in a 100% RE world. E.g. [Agora](https://www.agora-energiewende.de/veroeffentlichungen/klimaneutrales-deutschland-2045/) says e.g. ~230 GW ground-mounted PV (+135 GW other).. So both area types had to be used from this point of view. Sure enough, p-e-s could give different values (which - to my mind - should be validated against the picture drawn by studies).

If you think we'll run into problems with those reduced potential areas (e.g. not usable areas for new plants due to existing plants, ...) please drop me a note.

**Comment by ClaraBuettner** [comment]
PyPSA-eur-sec assumes an overall possible capacity of ~360 GW for solar ground mounted in Germany. In the first calculation, the ground mounted pv generators in Germany are extended to 159 GW, this might change in the final run. 
So the potential areas next to roads and railways might not be enough, but in that case we could also consider the agriculture potential areas.
