### ISSUE TITLE
Identify potential areas needed in egon-data 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#6]
In the DP section REA wind potential areas were applied. We need to identify which potential areas (also beside wind potential areas) will be needed in egon-data and which (external) data might be used. This task is closely connected to the reallocation of power plants in the REA section.

**Comment by gplssm** [comment]
This can be closed right?

**Comment by IlkaCu** [comment]
yes. Potential areas are already integrated in the workflow
