### ISSUE TITLE
Update p-e-s fork

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGon-data#604]
I have been testing if merging the newest p-e-s master development into our fork works. For one, the atlite update can be addressed like this. Moreover, it might be an advantage because the scigrid gas grid is included in the newest p-e-s development. Last but not least, we are up-to-date again...
The task has generated results already (only the last subtask make_summary task is still failing). They need to be further evaluated.

The corresponding branches:

- https://github.com/openego/eGon-data/tree/features/update-pes
- https://github.com/openego/pypsa-eur-sec/tree/batteries-and-update-pes

ToDos:

- [x] check whether there are relevant changes in the e-mobility part ( @nesnoj )
- [x] check the gas part ( @AmeliaNadal )
- [x] check the heat part (@ClaraBuettner )
- [x] (@ulfmueller dont forget to merge the [battery branch](https://github.com/openego/pypsa-eur-sec/tree/feature/batteries) once the decision is taken
- [ ] if we update, consider and preferably take the next version which should be out soon and should be mostly like the current master ( see [pes release announcement](/https://github.com/PyPSA/pypsa-eur-sec/issues/214)) 
...

**Comment by ClaraBuettner** [comment]
I run your branch and had a look at the heat data. The district heating shares were not set correctly, I fixed it in https://github.com/openego/pypsa-eur-sec/commit/d583fb12c2c6363c4ae70439ff8f9178c3368cf7 The other changes for the heat sector are still working. 

When running pypsa-eur-sec I get many warnings about links with an undefined bus. It looks like the `EU gas` bus is missing. Maybe that is just a bug in my installation, could you check if you have that bus in you network @ulfmueller?

**Comment by ulfmueller** [comment]
@AmeliaNadal told me today they would be fine with an updated p-e-s. Once @nesnoj gives feedback on his part, we can decide if we stick with the updated version. If this happens, can you (@AmeliaNadal ) check if the gas parameters (in particular [these](https://github.com/openego/pypsa-eur-sec/blob/update-pes/config_egon.yaml#L255-L264) are set correctly?

**Comment by nesnoj** [comment]
Checking [release notes](https://pypsa-eur-sec.readthedocs.io/en/latest/release_notes.html) and [blame `prepare_sector_network.py`](https://github.com/openego/pypsa-eur-sec/blame/a676bb6514135e5d0f02c260324ae56b6c1ff28e/scripts/prepare_sector_network.py#L1326) the transport sector seems not to be overhauled (except for CO2 costs for ICE vehicles).

Also, @ClaraBuettner has already [removed the railway part](https://github.com/openego/pypsa-eur-sec/pull/8/), guess this must be done again.

I'm fine with the update.

**Comment by ulfmueller** [comment]
Very good @nesnoj - Thx for checking! In fact, the railway part, as I merged the update with our development, is already removed as @ClaraBuettner once implemented it.

**Comment by AmeliaNadal** [comment]
By running the [features/update-pes branch](https://github.com/openego/eGon-data/tree/features/update-pes), the task run-pypsa-eur-sec is failing with the following error:

>  |   Traceback (most recent call last):
> 
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/pypsa-
> |   eur/.snakemake/scripts/tmpeb42yoh4.base_network.py", line 592, in
> |   <module>
> |       n = base_network()
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/pypsa-
> |   eur/.snakemake/scripts/tmpeb42yoh4.base_network.py", line 542, in
> |   base_network
> |       buses = _load_buses_from_eg()
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/pypsa-
> |   eur/.snakemake/scripts/tmpeb42yoh4.base_network.py", line 121, in
> |   _load_buses_from_eg
> |       buses = (pd.read_csv(snakemake.input.eg_buses, quotechar="'",
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/.snakemake/conda/6b10fdc4
> |   69cf12dadbef2eb8b549f7a7/lib/python3.8/site-
> |   packages/pandas/util/_decorators.py", line 311, in wrapper
> |       return func(*args, **kwargs)
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/.snakemake/conda/6b10fdc4
> |   69cf12dadbef2eb8b549f7a7/lib/python3.8/site-
> |   packages/pandas/io/parsers/readers.py", line 680, in read_csv
> |       return _read(filepath_or_buffer, kwds)
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/.snakemake/conda/6b10fdc4
> |   69cf12dadbef2eb8b549f7a7/lib/python3.8/site-
> |   packages/pandas/io/parsers/readers.py", line 575, in _read
> |       parser = TextFileReader(filepath_or_buffer, **kwds)
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/.snakemake/conda/6b10fdc4
> |   69cf12dadbef2eb8b549f7a7/lib/python3.8/site-
> |   packages/pandas/io/parsers/readers.py", line 933, in __init__
> |       self._engine = self._make_engine(f, self.engine)
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/.snakemake/conda/6b10fdc4
> |   69cf12dadbef2eb8b549f7a7/lib/python3.8/site-
> |   packages/pandas/io/parsers/readers.py", line 1231, in _make_engine
> |       return mapping[engine](f, **self.options)
> |     File "/home/nada_am/AN_eGon/eGon_code/eGon-data-
> |   workflow/egondata_0/wd_0/run-pypsa-eur-sec/.snakemake/conda/6b10fdc4
> |   69cf12dadbef2eb8b549f7a7/lib/python3.8/site-
> |   packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in
> |   __init__
> |       self._reader = parsers.TextReader(src, **kwds)
> |     File "pandas/_libs/parsers.pyx", line 470, in
> |   pandas._libs.parsers.TextReader.__cinit__
> |   TypeError: Expected list, got str

(I am obtaining the same error by running manually 'snakemake -j1 prepare_sector_networks'.)
@ulfmueller, have you already seen this error?

**Comment by ulfmueller** [comment]
No, I am not familiar with this error. It seems to be a problem with the input data which is being imported. Did you change any data? I would check this importing function and the corresponding file which shall be imported. In your error message, these lines seem to be leading to the file and maybe the source of the error: 
```
 _load_buses_from_eg
| buses = (pd.read_csv(snakemake.input.eg_buses
```
If you havent changed anything I cant think of the error's source right now....

**Comment by fwitte** [comment]
Snakemake should be restricted to `snakemake<7`, since it requires versions of jinja2 incompatible with apache-airflow (`jinja2<2.12.0`) and flask (`jinja2<3.0`).

**Comment by ClaraBuettner** [comment]
There is still no new release of pypsa-eur-sec and the repository doesn't indicate that there will be one soon. So I would tend to not wait any longer and use the version referenced in this branch. Are there any objections?
