### ISSUE TITLE
Rename carrier 'pv' to 'solar'

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#617]
The ground mounted pv park should have `carrier = 'solar'.` But currently the carrier is changed to 'pv' here: 
https://github.com/openego/eGon-data/blob/e82acd887655a5e0460b09bf5a4816410cf731b8/src/egon/data/datasets/fill_etrago_gen.py#L222-L225

@CarlosEpia Can you adjust this so that the carrier is 'solar' in `grid.egon_etrago_generator` ?

**Comment by CarlosEpia** [comment]
Sure. I will adjust it.

**Comment by CarlosEpia** [comment]
Hi @ClaraBuettner. The required adjustment is already available in the branch [https://github.com/openego/eGon-data/tree/fixes/%23617-Rename-carrier-pv-to-solar](url)
During the process, I ran egon-data and marked the task "fill_etrago_genertors" as failed in order to check the input data. I found out that there are some "solar", "wind_onshore", and "wind_offshore" generators in the table grid.egon_etrago_generator (I can send you a copy if you want to check) before I import them from the power plants table. Are they supposed to be there? There are also some generators with installed capacities equal to "0". Please let me know if you consider that I should check it deeply.

**Comment by IlkaCu** [comment]
> Hi @ClaraBuettner. The required adjustment is already available in the branch [https://github.com/openego/eGon-data/tree/fixes/%23617-Rename-carrier-pv-to-solar](url) During the process, I ran egon-data and marked the task "fill_etrago_genertors" as failed in order to check the input data. I found out that there are some "solar", "wind_onshore", and "wind_offshore" generators in the table grid.egon_etrago_generator (I can send you a copy if you want to check) before I import them from the power plants table. Are they supposed to be there? There are also some generators with installed capacities equal to "0". Please let me know if you consider that I should check it deeply.

If I am not mistaken the generators you just described are the foreign generator capacities connected to the AC buses in the neighboring countries. But installed capacities equal to zero seems a bit odd.

**Comment by ClaraBuettner** [comment]
> > Hi @ClaraBuettner. The required adjustment is already available in the branch [https://github.com/openego/eGon-data/tree/fixes/%23617-Rename-carrier-pv-to-solar](url) During the process, I ran egon-data and marked the task "fill_etrago_genertors" as failed in order to check the input data. I found out that there are some "solar", "wind_onshore", and "wind_offshore" generators in the table grid.egon_etrago_generator (I can send you a copy if you want to check) before I import them from the power plants table. Are they supposed to be there? There are also some generators with installed capacities equal to "0". Please let me know if you consider that I should check it deeply.
> 
> If I am not mistaken the generators you just described are the foreign generator capacities connected to the AC buses in the neighboring countries. But installed capacities equal to zero seems a bit odd.

Yes, the described generators are the ones in foreign countries. The generators with `p_nom = 0` were caused by a minor bug in the electrical_neigbours dataset. I fixed this in #612 (95cbff442c7424cf0cf311aabdaf1c355515247f).

**Comment by CarlosEpia** [comment]
Thanks for the clarification. I proceed to create the PR.
