### ISSUE TITLE
Disable testing on macOS via Travis

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#62]
It looks like Travis has started to limit the amount of builds which can be run during a certain period of time. See issue #41 for a slightly more elaborate [explanation](https://github.com/openego/eGon-data/issues/41#issuecomment-734888949). Since macOS builds are more expensive than others in this regard, I suggest disabling testing on macOS entirely instead of spending time on fixing this. But since I don't know the impact of such a decision, I wanted to you for your opinion on this,  @gplssm and @IlkaCu. And if you know anyone who would be impacted by this decision and should be part of the discussion, feel free to `@` him here and add him to the assignees.
If we decide to go forward with this, I'll close issue #42 in favour of this and modify PR #43 to accordingly.

**Comment by gplssm** [comment]
I've faced the newly introduced limits/changed pricing on Travis in https://github.com/OpenEnergyPlatform/open-MaStR/. There, I ran into queuing times of > 1 h to start the jobs which was slightly annoying. This is a problem which affects repos in this organization as Travis counts on per organization basis. This means for us that we might run into the same problem later, once we work more on the other repos in our organization.

My solution was to switch to GitHub Workflows. Which, honestly, works like a charm! Super fast and easy [to configure](https://github.com/OpenEnergyPlatform/open-MaStR/blob/afa6f2597512e79aebc2315e6bf1b5f4ab4c465d/.github/workflows/ci.yml).

I would suggest to do the same here. But, before we start to change anything we have to check if GitHub Workflows really offers unlimited builds for public repos as I understood it from [here](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/#simple-pay-as-you-go-pricing).
Moreover, if we consider to test on Windows or macOS later, we should check now if this would be possible with GitHub Workflows.

Good to know: tox [is supported](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#running-tests-with-tox).

**Comment by gnn** [comment]
I hope moving your post was OK, @gplssm. If not, feel free to undo everything I've done. ;)
For this issue, I'd basically only wanted to know whether you two agree with only testing on Linux for now and picking macOS tests back up and/or starting testing on Windows at some later time.

**Comment by IlkaCu** [comment]
I do agree with limiting the testing to Linux for now and have Windows next on the priority list.

**Comment by gplssm** [comment]
> I hope moving your post was OK, @gplssm. If not, feel free to undo everything I've done. ;)
> For this issue, I'd basically only wanted to know whether you two agree with only testing on Linux for now and picking macOS tests back up and/or starting testing on Windows at some later time.

Sorry for not replying the actual question. I'm totally fine with Linux only (for now). Anyways, from workflow setup side it doesn't look too difficult, but we can do it later.
