### ISSUE TITLE
Buses from the P-E-S eGon100RE are located at 0/0

### ISSUE THREAD

**Issue by fwitte** [openego/eGon-data#640]
This is at least the case in the current CI run, see attached shapefiles.
[eGon100RE_european_buses.zip](https://github.com/openego/eGon-data/files/7887386/eGon100RE_european_buses.zip)

**Comment by nesnoj** [comment]
Will this one be solved? @ClaraBuettner @ulfmueller

**Comment by AmeliaNadal** [comment]
Newly described in #803.
