### ISSUE TITLE
Create result table for number of households and buildings with el+heat profiles per census cell

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#642]
In tasks `electricity_demand_timeseries.hh_buildings.map-houseprofiles-to-buildings` #489 and `heat_demand_timeseries.HTS.demand-profile-generator` #558 el+heat profiles are assigned to buildings.

Needed: table with number of buildings and households per census cell with el+heat profiles.
Currently only table `demand.egon_household_electricity_profile_of_buildings` contains similar information in a unsuitable format.

Create new table `demand.egon_household_building_count_with_demand_profiles`, format:
```
cell_id    building_count    household_count
============================================
1          4                 6
...        ...               ...
```

Is this what you had in mind @ClaraBuettner ?
Couldn't think of a shorter table name, open for proposals ;)

**Comment by ClaraBuettner** [comment]
> In tasks `electricity_demand_timeseries.hh_buildings.map-houseprofiles-to-buildings` #489 and `heat_demand_timeseries.HTS.demand-profile-generator` #558 el+heat profiles are assigned to buildings.
> 
> Needed: table with number of buildings and households per census cell with el+heat profiles. Currently only table `demand.egon_household_electricity_profile_of_buildings` contains similar information in a unsuitable format.
> 
> Create new table `demand.egon_household_building_count_with_demand_profiles`, format:
> 
> ```
> cell_id    building_count    household_count
> ============================================
> 1          4                 6
> ...        ...               ...
> ```
> 
> Is this what you had in mind @ClaraBuettner ? Couldn't think of a shorter table name, open for proposals ;)

Maybe we could even add the building_id and/or type of the household or number of persons? So sth. like this:

| zensus_population_id | building_id | household_type / n_persons
| ------------- | ------------- | ------------- |

When I'm not mistaken you already have this data in your `demand.egon_household_electricity_profile_of_buildings`  table. 
Regarding the name, it could be also an option to move it to the society schema and call it e.g. `society.egon_household_building_count` or `society.egon_household_building_per_ha`

**Comment by nailend** [comment]
> When I'm not mistaken you already have this data in your `demand.egon_household_electricity_profile_of_buildings` table. 

Exactly, all the information is there but not as sums of the specific categories (e.g. building_count, household_count) like @nesnoj proposed. Is an extra table needed? Like this?

![grafik](https://user-images.githubusercontent.com/51374526/150552587-24d152b4-51a6-463e-a388-72e235c9cf4b.png)

```SQL
SELECT cell_id, Count(distinct(building_id)) as building_count, count(profile_id) as hh_count,
array_agg(distinct(LEFT(profile_id, 2))) as hh_types_unique, 
array_agg(LEFT(profile_id, 2)) as hh_types
FROM demand.egon_household_electricity_profile_of_buildings
Group By cell_id
LIMIT 100
```

@ClaraBuettner  I don't understand your table proposal, especially the column (household_type/n_persons).

We can derive the number of person living in households but its full of assumptions, we took to determine the type of household in the first place. Is this necessary? Would be quite some effort. 



 


Regarding the name, it could be also an option to move it to the society schema and call it e.g. `society.egon_household_building_count` or `society.egon_household_building_per_ha`

**Comment by nailend** [comment]
@ClaraBuettner could you have a look here and share your perspective please?

**Comment by ClaraBuettner** [comment]
> > When I'm not mistaken you already have this data in your `demand.egon_household_electricity_profile_of_buildings` table.
> 
> Exactly, all the information is there but not as sums of the specific categories (e.g. building_count, household_count) like @nesnoj proposed. Is an extra table needed? Like this?
> 
> ![grafik](https://user-images.githubusercontent.com/51374526/150552587-24d152b4-51a6-463e-a388-72e235c9cf4b.png)
> 
> ```sql
> SELECT cell_id, Count(distinct(building_id)) as building_count, count(profile_id) as hh_count,
> array_agg(distinct(LEFT(profile_id, 2))) as hh_types_unique, 
> array_agg(LEFT(profile_id, 2)) as hh_types
> FROM demand.egon_household_electricity_profile_of_buildings
> Group By cell_id
> LIMIT 100
> ```
> 
> @ClaraBuettner I don't understand your table proposal, especially the column (household_type/n_persons). What do we need this for?
> 
> We could derive the number of person living in households with its assumptions, we took to determine the type of household in the first place. Every household type would get a specific n_persons value assigned.

@nailend: I'm sorry for my late reply! 
Since I only use the number of buildings and households, the table @nesnoj  proposed in [the beginning](https://github.com/openego/eGon-data/issues/642#issue-1108009262) would be also fine for me. 
I was just wondering if you would like to share your final distribution of selected household types a bit more directly. But if you don't want to do this or don't know if it is necessary, we could also write only the number of buildings and households per cell.

**Comment by nailend** [comment]
With #652  there will be the possibility to get the cellwise hh_type distribution:
![grafik](https://user-images.githubusercontent.com/51374526/153010035-ab7ca0be-1962-4083-890c-fc3684409627.png)

```SQL
SELECT cell_id, array_agg(array[cast(hh_5types as char), hh_type])
FROM society.egon_destatis_zensus_household_per_ha_refined
GROUP BY cell_id
LIMIT 100```
