### ISSUE TITLE
Missing generator timeseries in eTraGo tables

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#645]
In `fill_etrago_gen` all entries from `grid.egon_etrago_generator_timeseries` are dropped: 
https://github.com/openego/eGon-data/blob/d677eceb32e5b6813ad65ca210e925da1dd2e850/src/egon/data/datasets/fill_etrago_gen.py#L145-L150

But other tasks also fill this table and this data is missing. Deleting from the table needs to be implemented with conditions. 
@CarlosEpia Should I fix this or could you do that?

**Comment by CarlosEpia** [comment]
Hi  @ClaraBuettner! thanks for letting me know about this bug. I will fix it.

**Comment by CarlosEpia** [comment]
Solved in PR #659.
