### ISSUE TITLE
Add more information to Getting started/ Installation section 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#65]
We need to add some more information on the installation of egon-data, its prerequisites and first steps to execute the workflow. 
**Prerequisites**
- [x] installation of docker and docker-compose
- [x] add user to docker group https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
- [x] osm2pgsql: Install with `sudo apt install osm2pgsql`

**Installation**
- [x] virtual environment recommended
- [x] git clone `git@github.com:openego/eGon-data.git`
- [x] installing in editable mode recommended: `pip install -e eGon-data`

**FAQ/trouble shooting section**
Refer to closed github issues, such as
- [x] #37
- [x] #36
- [x] Explain what to do when `PackageNotFoundError: No package metadata was found for egon.data` appears, see and link to #60 
- [x] Explain what to do if triggered DAG does not gets executed with picture from #33 

**Using Airflow**

- [x] start Airflow: `egon-data` serve in your terminal & open `localhost:8080` in your browser

**Comment by gnn** [comment]
I found a way of having DAGs be "On" by default, so you might want to tick off the fourth FAQ item. Check out the corresponding commit 9d8d01fefb45c6712d9ba7294a3d19bf150ab4b3. You're of course free to still keep it open and mention it in the FAQ if you want to.

**Comment by gplssm** [comment]
With https://egon-data.readthedocs.io/en/latest/getting_started.html#pre-requisites I actually think we can tick
> osm2pgsql: Install with sudo apt install osm2pgsql

Objections?

Also

> git clone git@github.com:openego/eGon-data.git
> installing in editable mode recommended: pip install -e eGon-data


I started a branch for this: https://github.com/openego/eGon-data/pull/71

**Comment by gnn** [comment]
I pushed commits to PR #71 which address the remaining un-ticked boxes.
