### ISSUE TITLE
Wrong year in table `demand.egon_demandregio_cts_ind` for eGon100RE

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#668]
Shouldn't that be 2050?

![image](https://user-images.githubusercontent.com/15910173/155098371-823e8482-0187-4341-80bf-a5c864487a0c.png)

**Comment by IlkaCu** [comment]
No, it is correct like this. DemandRegio only provides demand data for industry and cts up to year 2035 - therefore we had to use this information also for our eGon100RE scenario.

**Comment by nesnoj** [comment]
Ok, thanks for the clarification
