### ISSUE TITLE
Assign CTS demands to buildings

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#671]
Similar to #435 for households, CTS demands need to be allocated to buildings.

Idea
- Use the aggregated el. CTS profile grid district level from `demand.egon_etrago_electricity_cts`, but it's probably better to use [this function](https://github.com/openego/eGon-data/blob/3983dac0743c6361ee4e023791235c6c5bbce647/src/egon/data/datasets/electricity_demand/temporal.py#L38-L114) to obtain the timeseries.
- Disaggregation to census cell:
This profile is linearly scaled down to census cell level using the annual el. demand per census cell and scenario, it is located in `demand.egon_demandregio_zensus_electricity` (sector="service").
- Disaggregation to buildings and amenities:
  - Use only
    - buildings with amenities (`openstreetmap.osm_buildings_with_amenities`) and
    - amenities (`openstreetmap.osm_amenities_not_in_buildings`) which have no building assigned. Create synthetic building for each amenity (maybe 5x5m as in HH)
  - The annual demand and cell profile is scaled down to building level by using the building's area
  - Additionally for buildings: use count of amenities (col `n_amenities_inside`) in a building for weighting the building's demand, if I remember correctly @piaulous' analyses have shown that a linear weighting may overestimate the peak load (and therefore the demand) **TODO**.
  - In cells w/ el. demand but w/o buildings, create synthetic ones. Different to the residential sector, we have no additional data on number of buildings so the demand is the only we got. A reasonable assumption is necessary (some mean value from other cells?)  **TODO**
  - How to split up demand between buildings w/ amenities and amenities? **TODO**

**Comment by nesnoj** [comment]
Sorry, the right table for the amenities is **not** `openstreetmap.osm_amenities_shops_filtered` but `openstreetmap.osm_amenities_not_in_buildings`, I adjusted my post above.
Unfortunately, the preprocessing does not come to an end in reasonable time, I will restructure this part and restart the DAG in eGon-data2..

**Comment by nailend** [comment]
**Disagregate cts:**

1. mv_grid level
2. census level
3. buildings level

1 -> 2:
- annual demand share per mv_grid (same for both scenarios)
- use demand regio annual demand at census cell level
- group by mv_grid and calc share
- cts-profiles already scaled? @nesnoj 

2 -> 3:

- cells with amenities
    - <s> distribute to building by polygon-area </s> 
    - distribute to building with amenity-share of building per cell
        - amenities within buildings
            - n_amenity_inside differs to own calculation (osm_amenity_id per osm_building_id)
            - use own calculation? @nesnoj 
        - amenities without buildings
            - create synthetic building
        
- cells without amenites
    - take random building from buildings_filtered
    - define max annual demand per building? @nesnoj

**Comment by nailend** [comment]
First implementation is running in SH. Current issues are:
- missing information on educated-guess for cells without information on amenities or buildings
- currently using 1 building per cell and 1 amenity per building as first implementation
- there are duplicated building ids, resulting from SQL scripts. These are adhoc dropped as I couldn't find the source.

**Comment by nailend** [comment]
|                                          | cells | buildings | amenities |
|------------------------------------------|-------|-----------|-----------|
| df_buildings_with_amenities              |  2716 |    6510   |    9826   |
| df_buildings_without_amenities           |  8370 |    8370   |    8370   |
| df_synthetic_buildings_with_amenities    |  517  |    654    |    654    |
| df_synthetic_buildings_without_amenities |  1045 |    1045   |    1045   |
| **total**                                | **12648** | **16579**     | **19895**     |

**Comment by nailend** [comment]
![newplot(1)](https://user-images.githubusercontent.com/51374526/179843218-efb45e04-8103-411f-bcf9-3227250d8584.png)

**Comment by nailend** [comment]
![cts-2-buildings - Frame 1](https://user-images.githubusercontent.com/51374526/192762866-9c3e8d30-8afe-4c2f-b795-102b2324fe00.jpg)

This is the final implementation.

**Comment by nailend** [comment]
> For SH
> 	cells 	buildings 	amenities
> df_buildings_with_amenities 	2716 	6510 	9826
> df_buildings_without_amenities 	8370 	8370 	8370
> df_synthetic_buildings_with_amenities 	517 	654 	654
> df_synthetic_buildings_without_amenities 	1045 	1045 	1045
> **total** 	**12648** 	**16579** 	**19895**

For DE:
|                                          | cells | buildings | amenities |
|------------------------------------------|-------|-----------|-----------|
| df_buildings_with_amenities              |  97.752 |    219.463   |    309.279   |
| df_buildings_without_amenities           |  353.059 |    657.482  |    657.482   |
| df_synthetic_buildings_with_amenities    |  18.079  |    22.472    |    22.472    |
| df_synthetic_buildings_without_amenities |  40.856 |    81.712   |    81.712   |
| **total**                                | **509.746** | **981.129**     | **1.070.945**     |

**Comment by nailend** [comment]
Resulting Peak load compared to residential ones

|                 |               |  **count** | **mean** |  **std** | **min** |  **25%** |  **50%** |  **75%** |     **max** |
|----------------:|--------------:|-----------:|---------:|---------:|--------:|---------:|---------:|---------:|------------:|
|     **cts**     | **eGon100RE** | 981,136    | 33,254.7 | 40,134.6 | 9.8     | 11,085.1 | 21,279.7 | 4,0392.2 | 2,842,573.8 |
|                 |  **eGon2035** | 981,136    | 45,371.3 | 58,926.0 | 11.5    | 14,549.0 | 28,211.3 | 5,4108.9 | 6,785,765.0 |
| **residential** | **eGon100RE** | 21,360,296 | 3,173.4  | 3,378.0  | 759.0   | 2,135.2  | 2,475.5  | 3,029.6  | 627,676.6   |
|                 |  **eGon2035** | 21,360,296 | 3,526.6  | 3,740.8  | 907.7   | 2,388.7  | 2,735.9  | 3,335.7  | 678,399.6   |

**Comment by nailend** [comment]
Distribution of peak loads for scenario 2035.
 
![grafik](https://user-images.githubusercontent.com/51374526/192772533-31d5f2ed-fd28-46da-882a-30617d437bdb.png)


![grafik](https://user-images.githubusercontent.com/51374526/192772325-9b3aca43-bc06-41dd-9341-1700bf68337c.png)

**Comment by nailend** [comment]
@birgits
