### ISSUE TITLE
Annualize `capital_costs` in eTraGo tables

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#672]
The `capital_costs` are currently overnight costs, which might be misleading. In addition eTraGo needs annualized costs for the investment optimization, so we will annualize the capital costs directly in eGon-data.

**Comment by ClaraBuettner** [comment]
@fwitte: While updating the capital costs I stumbled over this line: 
https://github.com/openego/eGon-data/blob/1d5e22938e6969932e3edc2d45cee8b30edd9527/src/egon/data/datasets/scenario_parameters/parameters.py#L251
I thought that H2 feedin is not extendable, so you don't need any costs. Is that correct?

**Comment by fwitte** [comment]
Correct!

**Comment by ClaraBuettner** [comment]
> Correct!
> 
> Edit: It was extendable at first, must be a residual. I'll adjust it in a PR, once I finished work one some eTraGo stuff.

I can also adjust it in this branch if that's fine for you.

**Comment by fwitte** [comment]
That would be nice, thank you :)
