### ISSUE TITLE
Decide if all VG250 MVIEWS will be kept

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#68]
While transferring vg250 import and preparation scripts from @openego/data_processing, I stumbled upon a script that creates a lot of materialized views in addition to orginial vg250. The filter, for example, entities with valid geometries. 
I know that some of these are used in other parts of @openego/data_processing, but I can't say which exactly. I would like to remove mviews which are not needed anymore.

For finding out which one are used, I would like to ask you for help. Whenever you integrate a script to the pipeline, please note it down in the list below

### List of kep MVIEWS

_ticked will be kept_

- [x] boundaries.vg250_sta_tiny_buffer
- [x] boundaries. vg250_sta_invalid_geometry
- [x] boundaries.vg250_sta_union
- [x] boundaries.vg250_sta_bbox
- [x] boundaries.vg250_lan_union
- [x] boundaries.vg250_krs_area
- [x] boundaries.vg250_gem_valid
- [x] boundaries.vg250_gem_clean
- [x] boundaries.vg250_gem_hole
- [ ] ~boundaries.bkg_vg250_statistics_view~

**Comment by gplssm** [comment]
Now, I realized I was on the wrong track this morning. After reading the above again, I saw the intention is exactly the other way around.
The above listed views/tables get all created (except for the one that is stroked through) during the workflow. Now, and maybe @ClaraBuettner and @IlkaCu correctly said, it is about to find out which one aren't use.

Therefore, as described above, please tick the ones you've at least once in the eGon-data workflow. This means, I won't delete these ones.

**Comment by IlkaCu** [comment]
All the mviews mentioned in the list above are created in the egon-data workflow and will be kept like this.
