### ISSUE TITLE
Wrong solar capacities `supply.egon_power_plants` for eGon2035

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#695]
Given capacities in `supply.egon_power_plants`:

![grafik](https://user-images.githubusercontent.com/15910173/157607455-5d924b18-fd29-4105-8352-a271b03e1e80.png)

According to data bundle's `NEP2035_V2021_scnC2035.xlsx` solar should amount to 120 GW.

PS: at first sight, gas and oil generation capacities also seem to be flawed but I'm not familiar with the splits and carrier allocation so not sure...

**Comment by nesnoj** [comment]
Uh, the PV capacity seems to include PV ground capacities only (as listed in `supply.egon_scenario_capacities`) so seems to be correct.

I'll leave this one open to discuss the assumptions in PV ground share and to extend the task by solar rooftop.

**Comment by nesnoj** [comment]
Some questions/remarks on **PV ground**:

**1. Difference in capacities - why?**
`supply.egon_power_plants`: 29.33 GW
`supply.egon_scenario_capacities`: 35.93 GW

**2. On the ground-mounted share:**

Numbers in `supply.egon_power_plants` for 2035: 29.33 GW, total 120 GW -> 24.4 %
You use the same ratio as in MaStR, right?

Previous analyses have shown that the quality of column "Lage" in the MaStR is poor (units until 31.12.2020):
- The share in MaStR: 11,55 GW, total 53.52 GW -> 21,6 %
Official tables ([1](https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/ErneuerbareEnergien/ZahlenDatenInformationen/EEGinZahlen_2019.xlsx?__blob=publicationFile&v=4), [2](https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/ErneuerbareEnergien/ZahlenDatenInformationen/VOeFF_Registerdaten/2020_12_EEGZubauwerte.xlsx?__blob=publicationFile&v=2)) from BNetzA: 15.6 GW -> 29,1 % which is a significant difference.
- Extreme example Brandenburg: MaStR 1535 MW, tables from BNetzA 3092 MW! (Checking the data reveals that missing ground-mounted PV is tagged "BaulicheAnlagen" so a correction would be at least challenging..)

As we cannot fix this in reasonable time, it'd be ok for us to keep it and add a note to the docs.

**3. Existing sites are currently neglected (only potential areas with existing sites)**

This is problematic for several reasons:
- many sites are likely to be available for PV ground in the future (unlike WEC sites)
- changing all locations will change the DG's topology dramatically (resulting e.g. in overestimated grid expansion costs...)

Is it feasible for you to keep the existing sites and units? So keep units from status quo and add new ones in potential areas as implemented (but only potential areas without existing plant(s)).

**4. Some plants have way too high capacities (assuming a generous 1 MW/ha) - bug?**

Example:
![grafik](https://user-images.githubusercontent.com/15910173/157719523-fea33ed4-cf3e-47fe-8242-bbd194958c0b.png)

**Comment by IlkaCu** [comment]
> Some questions/remarks on **PV ground**:
> 
> **1. Difference in capacities - why?** `supply.egon_power_plants`: 29.33 GW `supply.egon_scenario_capacities`: 35.93 GW

I cannot answer this immediately, but I will further investigate it as soon as the current CI run finished. 

> **2. On the ground-mounted share:**
> 
> Numbers in `supply.egon_power_plants` for 2035: 29.33 GW, total 120 GW -> 24.4 % You use the same ratio as in MaStR, right?
> 
> Previous analyses have shown that the quality of column "Lage" in the MaStR is poor (units until 31.12.2020):
> 
>     * The share in MaStR: 11,55 GW, total 53.52 GW -> 21,6 %
>       Official tables ([1](https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/ErneuerbareEnergien/ZahlenDatenInformationen/EEGinZahlen_2019.xlsx?__blob=publicationFile&v=4), [2](https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/ErneuerbareEnergien/ZahlenDatenInformationen/VOeFF_Registerdaten/2020_12_EEGZubauwerte.xlsx?__blob=publicationFile&v=2)) from BNetzA: 15.6 GW -> 29,1 % which is a significant difference.
> 
>     * Extreme example Brandenburg: MaStR 1535 MW, tables from BNetzA 3092 MW! (Checking the data reveals that missing ground-mounted PV is tagged "BaulicheAnlagen" so a correction would be at least challenging..)
> 
> 
> As we cannot fix this in reasonable time, it'd be ok for us to keep it and add a note to the docs.
> 

We **did not** take this information from MaStR but from the NEP. There are individual shares for every federal state. 
> **3. Existing sites are currently neglected (only potential areas with existing sites)**
> 
> This is problematic for several reasons:
> 
>     * many sites are likely to be available for PV ground in the future (unlike WEC sites)
> 
>     * changing all locations will change the DG's topology dramatically (resulting e.g. in overestimated grid expansion costs...)
> 
> 
> Is it feasible for you to keep the existing sites and units? So keep units from status quo and add new ones in potential areas as implemented (but only potential areas without existing plant(s)).

We all discussed our procedure several times during its development and I doubt that we have the time to change our methods again unless you present very strong arguments to do so. To be honest, I do not understand the arguments/reasons you listed above yet. Maybe a discussion for Wednesday? 

> 
> **4. Some plants have way too high capacities (assuming a generous 1 MW/ha) - bug?**
> 

We will have a deeper look - it might be caused by a join of different potential areas. 

> 
> **5. Carrier name**
> 
> In `supply.egon_power_plants` there's only solar, in `supply.egon_scenario_capacities` I see both solar and solar_rooftop. Why?

The capacities for solar_rooftop were directly fed into the `grid.egon_etrago_generators` table by the interim [method to distribute the capacities to grid districts](https://github.com/openego/eGon-data/blob/dev/src/egon/data/datasets/power_plants/pv_rooftop.py#L34-L217). Therefore you only find the PV ground plants in this table.

**Comment by IlkaCu** [comment]
> 
> **1. Difference in capacities - why?** `supply.egon_power_plants`: 29.33 GW `supply.egon_scenario_capacities`: 35.93 GW
> 

A closer investigation revealed that this difference in capacities occurs in four different federal states: Brandenburg (DE4), Mecklenburg-Vorpommern (DE8), Sachsen (DED) and Sachsen-Anhalt (DEE). The potential areas in these federal state are not sufficient to meet the target capacity. 
An adjustment in our method to also take existing plants outside of potential areas into account potentially reduces this problem but it will most likely not completely erase it. A backup method might be needed to deal with the remaining capacities.

**Comment by IlkaCu** [comment]
There seems to be a bug in the code, as a closer look at the potential areas shows that there should still be sufficient capacity available. I will further investigate this tomorrow.

**Comment by nesnoj** [comment]
> > **1. Difference in capacities - why?** `supply.egon_power_plants`: 29.33 GW `supply.egon_scenario_capacities`: 35.93 GW
> 
> A closer investigation revealed that this difference in capacities occurs in four different federal states: Brandenburg (DE4), Mecklenburg-Vorpommern (DE8), Sachsen (DED) and Sachsen-Anhalt (DEE). The potential areas in these federal state are not sufficient to meet the target capacity. An adjustment in our method to also take existing plants outside of potential areas into account potentially reduces this problem but it will most likely not completely erase it. A backup method might be needed to deal with the remaining capacities.

Thanks for checking! Sounds like a good reason for #382.
Does that mean u will touch the distribution as well? :smile_cat:
