### ISSUE TITLE
Offshore turbines not located offshore in `supply.egon_power_plants`

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#696]
![grafik](https://user-images.githubusercontent.com/15910173/157611252-9ef420cd-a556-4fc5-a650-3001b1432cd8.png)

**Comment by ulfmueller** [comment]
sorry, no expert on this, but it looks like that they are georeferenced to their connection points to the main grid.

**Comment by nesnoj** [comment]
> sorry, no expert on this, but it looks like that they are georeferenced to their connection points to the main grid.

Thanks for your comment. For some nodes that seems plausible, but what about e.g. Osnabrück?
BTW, it's not relevant for the distribution grids but it'd be good to have proper coordinates for the WebApp #447

**Comment by ClaraBuettner** [comment]
> > sorry, no expert on this, but it looks like that they are georeferenced to their connection points to the main grid.
> 
> Thanks for your comment. For some nodes that seems plausible, but what about e.g. Osnabrück? BTW, it's not relevant for the distribution grids but it'd be good to have proper coordinates for the WebApp #447

Yes, these are the existing and future connection points. According to NEP (https://www.netzentwicklungsplan.de/sites/default/files/paragraphs-files/NEP_2035_V2021_1_Entwurf_Teil1_1.pdf), table 20, page 121 the TSOs assume e.g. connection points near Osnabrück (Suchraum Gemeinden Ibbenbüren / Mettingen /Westerkappeln) and 40km from Duisburg (Suchraum Zensenbusch).
