### ISSUE TITLE
PostgreSQL sometimes raises a "could not resize shared memory segment" error during a full worfklow run

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#702]
This was [mentioned](https://github.com/openego/eGon-data/issues/377#issuecomment-1066445745) in issue #377 and since there was no issue for this error yet, I'd thought I'd open one in order to gather all the information about it. I found a good explanation on why this happens in [this thread][0] and I also figured out two possible solutions from the Docker docs and [this article about "Shared Memory & Docker"][4]:

  - manually configure the size of "/dev/shm" in Docker's compose file using [`shm_size`][1], or
  - make the Docker container use the host's "/dev/shm" by using a ["bind mount"][2] under the service's [`volumes`][3] key in the compose file.

I'll try the second option first, because that way I don't have to figure out to what value `shm_size` has to be set in order to prevent the error from occurring.

Btw., please correct me if the title is wrong and the error also occurs when running the workflow limited to `Schleswig-Holstein`.

[0]: https://www.postgresql.org/message-id/CAG903PrStVFsFbh02MrANe0M6wgFGwf_mzVcd%2BZeL-D57QOggQ%40mail.gmail.com
[1]: https://docs.docker.com/compose/compose-file/compose-file-v3/#shm_size
[2]: https://docs.docker.com/storage/bind-mounts/
[3]: https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
[4]: https://datawookie.dev/blog/2021/11/shared-memory-docker/

**Comment by nesnoj** [comment]
Thanks for tackling this problem, we observed this as well in #267 and #258 where increasing the `shm_size` (first of your options) did not solve the problem. So let's see if the second one does better..
