### ISSUE TITLE
The `demand-profile-generator` task fails when `download-era5` did not complete successfully

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#719]
More specifically, I'm talking about `heat_demand_timeseries.HTS.demand-profile-generator` and `era5.download-era5`. I started a `Schleswig-Holstein` run based on commit 2f57511ee136bfc65ee25b1eefec8832b47375c8 in an improperly configured environment which made `era5.download-era5` immediately fail without downloading anything. The only other task which failed in this run, too, was `heat_demand_timeseries.HTS.demand-profile-generator`. After clearing `era5.download-era5` and making it succeed, `heat_demand_timeseries.HTS.demand-profile-generator` ran successfully, too. So I might be incorrect, but it looks like there's an unspecified dependency between `era5.download-era5`, or one of it's downstream tasks, and `heat_demand_timeseries.HTS.demand-profile-generator`. Could somebody more knowledgable about those two task please confirm this?
I've also uploaded the [failure log][0] for the `heat_demand` task.

[0]: https://gist.github.com/gnn/4742b0d2b164a6c9cf379030a3c93a80#file-demand-profile-generator-log

**Comment by nesnoj** [comment]
You're right, era5 is [missing in the dependency list](https://github.com/openego/eGon-data/blob/63a4ea698dfad1c379edf9229d8b75b6f8f205fb/src/egon/data/airflow/dags/pipeline.py#L565). I talked to @ClaraBuettner on Monday and she'll prepare a fix..

**Comment by ClaraBuettner** [comment]
Thanks to @IlkaCu the missing dependency was already added in  77f5acd8304d2dac7c6f43814f6f1ae02b8a0378
