### ISSUE TITLE
Final gas demand in Norway eGon2035

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#723]
In the TYNDP data, there is no final gas demand for Norway (CH4), a value should be searched and implemented.

**Comment by IlkaCu** [comment]
Can this issue be closed?

**Comment by AmeliaNadal** [comment]
> Can this issue be closed?

This issue is not problematic or urgent: there is a gas demand in Norway in eGon2035 (in the right order of magnitude), but this value should be improve, because it's actually the heat demand of Norway in 2050 (result of p-e-s).
Therefore, I wouldn't close this issue (same for the issue #728: not a priority but should be tackled at one point).

**Comment by AmeliaNadal** [comment]
This issue is not problematic: there is a gas demand in Norway in eGon2035 in the right order of magnitude
This value could be improve, because it's actually the heat demand of Norway in 2050 (result of p-e-s).
However, this inconsistency is documented, so that it could be improved if needed.
