### ISSUE TITLE
Missing gas_bus_id in Baden-Württemberg

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#734]
One municipality of Baden-Württemberg (Büsingen am Hochrhein) is isolated from the rest of Germany (marked in orange). This area is not part of any CH4 voronoi (shown in red). There is an industrial area in the municipality, when a CHP is assigned to this area, the chp-tasks run into errors. 

![image](https://user-images.githubusercontent.com/22964326/165108871-4b2d5e21-d5e5-4510-b363-5670d36f61da.png)

I tried to have a look into https://github.com/openego/eGon-data/blob/dev/src/egon/data/datasets/generate_voronoi.py but couldn't find the reason. @fwitte or @AmeliaNadal: Can you help me?

**Comment by fwitte** [comment]
Working on it, thanks for notifying!

**Comment by fwitte** [comment]
Fixed it in the PR, the enclaves are now included in the voronois:

![grafik](https://user-images.githubusercontent.com/20252362/165709761-3c4578c3-f905-4ca3-ada0-d9de15fcc84c.png)
