### ISSUE TITLE
Update HH electricity demand profiles

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#735]
Update HH demand profiles to fix bugs:
- [x] remove leap year: use 2011 instead of 2016
- [x] removed daylight saving
- [x] adjusted pool size of family types to match with Zensus 2011
- [x] update import in egon-data
- [x] merge  profile type O2, O1 and O0 in egon-data
- [x] update filename in `datasets.yml`

**Comment by nesnoj** [comment]
The daylight saving cannot be quickly removed by IEE, we gotta fix this manually in the HDF file(s).

**Comment by nailend** [comment]
As DST change happens from 2-3am, when there is almost no significant electricity load, we will fix it just by adding the mean value at summer-time change and remove one hour at winter-time change.

**Comment by nailend** [comment]
Pool size matching zensus 2011
Type | Profile | %
-- | -- | --
O2 | 100 | 0.1
O1 | 200 | 0.2
OO | 500 | 0.5
OR | 900 | 0.9
P1 | 10,000 | 10.0
P2 | 10,000 | 10.0
P3 | 5,500 | 5.5
PO | 17,000 | 17.0
PR | 11,000 | 11.0
SK | 6,400 | 6.4
SO | 24,000 | 24.0
SR | 14,400 | 14.4
**SUMME** | 100,000 | 100.00

Household types O2, O1 and OO will be merged as they are used as one category in egon-data
