### ISSUE TITLE
Tables missing prefix

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#738]
There some tables which are missing a prefix:
- [x] #746
- [x] demand.heat_idp_pool -> demand.egon_heat_idp_pool
- [x] demand.heat_timeseries_selected_profiles - demand.egon_heat_timeseries_selected_profiles

**Comment by fwitte** [comment]
@nesnoj: Is this a naming convention thing? I can update the saltstructure stuff, since I implemented that dataset.

**Comment by nesnoj** [comment]
Yes, we once agreed on using the original source as prefix, so if you can afford this change that would be nice.
If the data is altered to a significant degree, we are the authors so we use the prefix `egon_`.

**Comment by nesnoj** [comment]
@ClaraBuettner As you just made adjustments to the heat demand ts in #870, could you take the chance and rename the 2 tables above as well?

**Comment by nesnoj** [comment]
Thanks for [changing](https://github.com/openego/eGon-data/commit/19987161c83e1f065598e0a06096dab0dd520ae3)! :)
