### ISSUE TITLE
Importing osm with osm2pgsql fails due to missing password

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#74]
The original problem was that the task 'migrate_osm' failed because of missing osm tables:
> psycopg2.errors.UndefinedTable: relation "public.osm_line" does not exist

But the problem actually accrues earlier in 'import_osm' and airflow just not showed the error message of a subtask. 
So as @gnn proposed, I added `check=True,` [here](https://github.com/openego/eGon-data/blob/04fdfc2117bc5acdd144dc21d0c129ab0a1dec28/src/egon/data/importing/openstreetmap/__init__.py#L73-L77). With this setting, I get an error in import_osm: 

> subprocess.CalledProcessError: Command 'osm2pgsql --create --slim --hstore-all --number-processes 4 --cache 4096 -H 127.0.0.1 -P 54321 -d egon-data -U egon -p osm -S oedb.style /home/clara/GitHub/eGon-data/src/egon/data/importing/openstreetmap/bremen-200101.osm.pbf' returned non-zero exit status 1.

When I run the osm2pgsql command in the terminal I get the following error message: 

> Using built-in tag processing pipeline
> Using projection SRS 3857 (Spherical Mercator)
> Osm2pgsql failed due to ERROR: Connection to database failed: fe_sendauth: no password supplied

So somehow the password to the database is missing in psm2pgsql.

**Comment by gplssm** [comment]
I can't reproduce on dev with

```
Python
3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]

pip
20.3

Git
dev@04fdfc2117bc5acdd144dc21d0c129ab0a1dec28
```

The password is supplied via the environment variable `PGPASSWORD`.

You could maybe try to execute function `to_postgres()` outside of airflow and set a breakpoint here: https://github.com/openego/eGon-data/blob/04fdfc2117bc5acdd144dc21d0c129ab0a1dec28/src/egon/data/importing/openstreetmap/__init__.py#L76
Then you could check if the correct password is read from the config file.

@gnn if you have better ideas how to understand what's happening on @ClaraBuettner PC, please go ahead!

**Comment by ClaraBuettner** [comment]
When I run `to_postgres()` outside of airflow the password is read-in correctly. But it was missing from the command I run in the terminal (which was `osm2pgsql --create --slim --hstore-all --number-processes 4 --cache 4096 -H 127.0.0.1 -P 54321 -d egon-data -U egon -p osm -S oedb.style /home/clara/GitHub/eGon-data/src/egon/data/importing/openstreetmap/bremen-200101.osm.pbf`) so I think the execution in the shell without a password cause this problem. 

But I get another error now: 

> osm2pgsql version 0.94.0 (64 bit id space)
> 
> Using built-in tag processing pipeline
> Using projection SRS 3857 (Spherical Mercator)
> Setting up table: osm_point
> 

> Osm2pgsql failed due to ERROR: CREATE UNLOGGED TABLE osm_point (osm_id int8,"access" text,"addr:housename" text,"addr:housenumber" text,"addr:interpolation" text,"admin_level" text,"aerialway" text,"aeroway" text,"amenity" text,"area" text,"barrier" text,"bicycle" text,"brand" text,"bridge" text,"boundary" text,"building" text,"capital" text,"construction" text,"covered" text,"culvert" text,"cutting" text,"denomination" text,"disused" text,"ele" text,"embankment" text,"foot" text,"generator:source" text,"harbour" text,"highway" text,"historic" text,"horse" text,"intermittent" text,"junction" text,"landuse" text,"layer" text,"leisure" text,"line" text,"lock" text,"man_made" text,"military" text,"motorcar" text,"name" text,"natural" text,"office" text,"oneway" text,"operator" text,"place" text,"population" text,"power" text,"power_source" text,"public_transport" text,"railway" text,"ref" text,"religion" text,"route" text,"service" text,"sidewalk" text,"shop" text,"sport" text,"surface" text,"toll" text,"tourism" text,"tower:type" text,"tunnel" text,"water" text,"waterway" text,"wetland" text,"width" text,"wood" text,"z_order" int4,"tags" hstore,way geometry(POINT,3857) ) WITH ( autovacuum_enabled = FALSE ) failed: ERROR:  type "hstore" does not exist
> LINE 1: ...xt,"width" text,"wood" text,"z_order" int4,"tags" hstore,way...

I don't have the hstore-expansion in my database but I assume I need it. Is this added with the ` --hstore-all` or somewhere else?

**Comment by gplssm** [comment]
Thanks for more information on that. There are actually two issues: 

- `osm2pgsql` executed via Airflow does not recognize environment variables passed with `env={"PGPASSWORD": docker_db_config["POSTGRES_PASSWORD"]}`
- the hstore extension is missing

Let's solve them separately. 

> When I run `to_postgres()` outside of airflow the password is read-in correctly. 

:+1: this mean that passing the env variable works in general. Just not when it is executed with airflow.
Doe you still have the `check=True` in your current code as you wrote here https://github.com/openego/eGon-data/issues/74#issue-760223320?
This would be necessary for passing the postgres password via env variables, see [here](https://stackoverflow.com/questions/2231227/python-subprocess-popen-with-a-modified-environment#comment101621421_4453495)

> But it was missing from the command I run in the terminal (which was `osm2pgsql --create --slim --hstore-all --number-processes 4 --cache 4096 -H 127.0.0.1 -P 54321 -d egon-data -U egon -p osm -S oedb.style /home/clara/GitHub/eGon-data/src/egon/data/importing/openstreetmap/bremen-200101.osm.pbf`) so I think the execution in the shell without a password cause this problem.
> 
> But I get another error now:
> 
> > osm2pgsql version 0.94.0 (64 bit id space)
> > Using built-in tag processing pipeline
> > Using projection SRS 3857 (Spherical Mercator)
> > Setting up table: osm_point
> 
> > Osm2pgsql failed due to ERROR: CREATE UNLOGGED TABLE osm_point (osm_id int8,"access" text,"addr:housename" text,"addr:housenumber" text,"addr:interpolation" text,"admin_level" text,"aerialway" text,"aeroway" text,"amenity" text,"area" text,"barrier" text,"bicycle" text,"brand" text,"bridge" text,"boundary" text,"building" text,"capital" text,"construction" text,"covered" text,"culvert" text,"cutting" text,"denomination" text,"disused" text,"ele" text,"embankment" text,"foot" text,"generator:source" text,"harbour" text,"highway" text,"historic" text,"horse" text,"intermittent" text,"junction" text,"landuse" text,"layer" text,"leisure" text,"line" text,"lock" text,"man_made" text,"military" text,"motorcar" text,"name" text,"natural" text,"office" text,"oneway" text,"operator" text,"place" text,"population" text,"power" text,"power_source" text,"public_transport" text,"railway" text,"ref" text,"religion" text,"route" text,"service" text,"sidewalk" text,"shop" text,"sport" text,"surface" text,"toll" text,"tourism" text,"tower:type" text,"tunnel" text,"water" text,"waterway" text,"wetland" text,"width" text,"wood" text,"z_order" int4,"tags" hstore,way geometry(POINT,3857) ) WITH ( autovacuum_enabled = FALSE ) failed: ERROR:  type "hstore" does not exist
> > LINE 1: ...xt,"width" text,"wood" text,"z_order" int4,"tags" hstore,way...
> 
> I don't have the hstore-extension in my database but I assume I need it. Is this added with the ` --hstore-all` or somewhere else?

The flag `--hstore-all` requires the hstore extension to be installed. The installation should happen in the background with calling the [entrypoint script](https://github.com/openego/eGon-data/blob/e06d52fba0aaf07cb24a73d2eccb27d932d4e6cd/src/egon/data/airflow/entrypoints/create_postgis_extension.sql) during startup of the docker container.
I thought you would be using docker for providing the database. Aren't you? Then, I would understand why the extension was not installed :thinking: 

> When I add hstore manually to the database extensions, the import works as expected. So I think it's just this missing extension.

I guess you used the same command as in the entrypoint script `CREATE EXTENSION hstore;` right?

**Comment by ClaraBuettner** [comment]
> Thanks for more information on that. There are actually two issues:
> 
>     * `osm2pgsql` executed via Airflow does not recognize environment variables passed with `env={"PGPASSWORD": docker_db_config["POSTGRES_PASSWORD"]}`
> 
>     * the hstore extension is missing
> 
> 
> Let's solve them separately.
> 
> > When I run `to_postgres()` outside of airflow the password is read-in correctly.
> 
> +1 this mean that passing the env variable works in general. Just not when it is executed with airflow.
> Doe you still have the `check=True` in your current code as you wrote here [#74 (comment)](https://github.com/openego/eGon-data/issues/74#issue-760223320)?
> This would be necessary for passing the postgres password via env variables, see [here](https://stackoverflow.com/questions/2231227/python-subprocess-popen-with-a-modified-environment#comment101621421_4453495)
> 

Right now, it works also with airflow. The problem with the password only accured because I called the osm2pgsql in a terminal without providing the password. Sorry for the missunderstanding, but this problem is solved. 

> The flag `--hstore-all` requires the hstore extension to be installed. The installation should happen in the background with calling the [entrypoint script](https://github.com/openego/eGon-data/blob/e06d52fba0aaf07cb24a73d2eccb27d932d4e6cd/src/egon/data/airflow/entrypoints/create_postgis_extension.sql) during startup of the docker container.
> I thought you would be using docker for providing the database. Aren't you? Then, I would understand why the extension was not installed thinking
> 
Yes I use docker for the database. But even if I run airflow completely from the beginning, it still uses the existing, previously created database in docker. I also still have tables I created before with another branch in the docker database. I don't get a new, clear database in every run of airflow. I'm not sure if something is wrong with this. 

> > When I add hstore manually to the database extensions, the import works as expected. So I think it's just this missing extension.
> 
> I guess you used the same command as in the entrypoint script `CREATE EXTENSION hstore;` right?
Yes, I used this command.

**Comment by ClaraBuettner** [comment]
I checked the logs of docker and it always says

> PostgreSQL Database directory appears to contain a database; Skipping initialization

when I run the egon-data DAG with airflow. I'm not sure if this is right. I thought I get a new database with every run.

**Comment by gnn** [comment]
> I checked the logs of docker and it always says
> 
> > PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> when I run the egon-data DAG with airflow. I'm not sure if this is right. I thought I get a new database with every run.

That's what I thought initially, too. But it's not the case. The Docker container is set up in such a way, that the location of the database files is stored in a directory on your machine. So the database persists between `egon-data` runs. Which is a good thing, because it helps avoid unnecessary repetition of tasks. But it might be the cause of your `hstore` problems.


> The flag `--hstore-all` requires the hstore extension to be installed. The installation should happen in the background with calling the [entrypoint script](https://github.com/openego/eGon-data/blob/e06d52fba0aaf07cb24a73d2eccb27d932d4e6cd/src/egon/data/airflow/entrypoints/create_postgis_extension.sql) during startup of the docker container.
> I thought you would be using docker for providing the database. Aren't you? Then, I would understand why the extension was not installed 

The entrypoint scripts "are only run if you start the container with a data directory that is empty". See the PostgreSQL Docker container's [documentation](https://hub.docker.com/_/postgres) under "Initialization scripts", first warning. So if it failed to install the extension during the first run for some reason, you'll always be missing it. I had the same problem. I already have a solution for this. Modify the initialization script to contain
```sql
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS postgis;
```
instead and call it in a database initialization task which is always run at the start of the pipeline via
```sh
psql -h localhost -p 54321 -U egon -d egon-data \
  -f src/egon/data/airflow/entrypoints/create_postgis_extension.sql \
  --set ON_ERROR_STOP=True
```
Obviously most of the command line arguments have to be determined via configuration or some other dynamic way, which is why I didn't have time to commit this yet.

**Comment by gplssm** [comment]
Meanwhile, until the proposed fix of https://github.com/openego/eGon-data/issues/74#issuecomment-747394441 is merged, you can take the workaround of deleting the said data directory (the place where the database is stored). Running it afterwards again, the entryscripts should be executed successfully.

`rm -r $HOME/docker/volumes/postgres/egon-data` (you probably have to prepend `sudo`)

But be aware: it remove all the data.

**Comment by gnn** [comment]
But I guess you don't need that, because you already added the extension manually, right? If you did this, the change should also persist across `egon-data` runs and the import task shouldn't fail anymore.

**Comment by gnn** [comment]
I added two separate issues dealing with the flaws that this issue uncovered. So if this issue doesn't occur for you anymore, @ClaraBuettner, you can close it.

**Comment by ClaraBuettner** [comment]
Yes, this issue is solved for me. Many thanks for your help!
