### ISSUE TITLE
Add pv home batteries per mv grid district 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#749]
Home batteries should define a lower boundary of the extendable battery storage units. The overall number of batteries is taken from NEP for eGon2035. 
The distribution should be done according to the installed pv rooftop capacity and depends on #684

**Comment by IlkaCu** [comment]
Installed capacity for pv home batteries according to NEP C2035: 16,8 GW. Number can be found here: `NEP2035_V2021_scnC2035.xlsx`

**Comment by khelfen** [comment]
> Installed capacity for pv home batteries according to NEP C2035: 16,8 GW. Number can be found here: `NEP2035_V2021_scnC2035.xlsx`

At the moment, the capacity was entered into the tables in GW. This needs to be changed to MW.

**Comment by IlkaCu** [comment]
> > Installed capacity for pv home batteries according to NEP C2035: 16,8 GW. Number can be found here: `NEP2035_V2021_scnC2035.xlsx`
> 
> At the moment, the capacity was entered into the tables in GW. This needs to be changed to MW.

Good point. Thanks for bringing that up.
