### ISSUE TITLE
Move database extension creation into DAG task

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#76]
Replacing the [current extension creation code](https://github.com/openego/eGon-data/blob/e06d52fba0aaf07cb24a73d2eccb27d932d4e6cd/src/egon/data/airflow/entrypoints/create_postgis_extension.sql) with
```
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS postgis;
```
and running it at the start of the pipeline via something like
```
psql -h localhost -p 54321 -U egon -d egon-data \
  -f src/egon/data/airflow/entrypoints/create_postgis_extension.sql \
  --set ON_ERROR_STOP=True
```
makes sure that the pipeline always fails early if the extension can't be created. This should prevent #74, whose discussion has a [comment](https://github.com/openego/eGon-data/issues/74#issuecomment-747394441) with more details, from reoccurring for others.

**Comment by IlkaCu** [comment]
I faced the problem that extension `postgis_raster` wasn't created automatically.

**Comment by ClaraBuettner** [comment]
@gnn I noticed that this will be solved with PR which also includes other things and is still marked as draft. But because we frequently run into this error, do you think that it could make sens to solve this preliminary differently? I could also implement this.

**Comment by gnn** [comment]
I'm currently solving this, because when supporting multiple databases, initializing the database has to be done differently anyway. Will push a solution today.
