### ISSUE TITLE
Wind-offshore capacities exceed input values

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#773]
The latest CI run showed that for scenario `eGon2035` the wind_offshore capacities for Germany exceed the input values by 148%. 
Might be related to the updated osm data?!

**Comment by CarlosEpia** [comment]
The commits 3bc74b5440c9a779c9271fcad321c5c739d8822a and c756e53e6a2a3e26c31b623409e427e7999edd24 were created in March but are not part of dev yet. Their purpose was to create the wind offshore power plants for the eGon100RE. The data for the eGon2035 scenario was overwritten by the data of the other scenario and this created the problem. It was solved in the commit c48b3b90e8d049052432e97ef048f2c8c99e0ea2.

@IlkaCu do you remember which branch contains the mentioned commits? In case of yes, could you cherry-pick the commit c48b3b90e8d049052432e97ef048f2c8c99e0ea2 to get it merged into dev with the other related changes?

P.s. 1: I did a small change regarding the creation of the offshore power plants for the eGon100RE. I scaled the data for 2040 in the file "NEP2035_V2021_scnC2035". In this way, we don't have power plants with an installed capacity = 0. Please let me know if it also makes sense for you.

P.s. 2: I realized that the script "fill_etrago_gen.py" has not been modified to group the power plants for the eGon100RE scenario. The issue https://github.com/openego/eGon-data/issues/776 was created for this.

**Comment by CarlosEpia** [comment]
Already solved.
