### ISSUE TITLE
Move open features to 2022-06-10 CI branch

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#806]
There's a new CI branch, called `continuous-integration/run-everything-over-the-weekend-2022-06-10`. The branch will be left at it's current name until all features which still need to be tested and are present in the old CI branch are moved to this new branch. To this end, would you please merge everything you want to have tested into the new branch and check the box next to your nick below, once you have done so?

  - [x] @AmeliaNadal
  - [x] @ClaraBuettner 
  - [x] @IlkaCu 
  - [x] @fwitte 
  - [x] @nesnoj 
  - [x] @CarlosEpia 

Since I don't know the names of everybody who still works on the workflow, I intentionally named only the people which I knew of the top of my head. If you know of anybody else who should chime in and be noted with whether all his changes are moved to the new branch, please edit this post to include his name in the list. Checking the box next to your name then has the following meanings:

  - All my features which should be tested in a full run are newly merged or moved from the old CI branch into `continuous-integration/run-everything-over-the-weekend-2022-06-10`.
  - I don't know anybody which should be in this list who isn't already in it.

Once all boxes are checked, I'll delete the old CI branch, rename the new one and close this issue.

**Comment by nesnoj** [comment]
I'd say, not responding for 25 days is definitely a yes.

**Comment by nesnoj** [comment]
C'mon @IlkaCu, tick it so we can get rid of the branch ;)

**Comment by nailend** [comment]
Which one is the current CI branch used? I am a bit lost. This one?

**Comment by ClaraBuettner** [comment]
> Which one is the current CI branch used? I am a bit lost. This one?

Yes, the current CI-branch is still the one called `continuous-integration/run-everything-over-the-weekend-2022-06-10`

**Comment by nesnoj** [comment]
As agreed on today, I deleted the old CI branches
- `continuous-integration/run-everything-over-the-weekend`
- `continuous-integration/run-everything-over-the-weekend-v2`
