### ISSUE TITLE
Create lowflex scenario

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#822]
We discussed an (eTraGo) no-flex scenario several times in the past. Today, we agreed on creating it.
The main question is how to integrate it into the pipeline while keeping the time expenditure low. The cleanest way seems to be new scenario names such as `eGon2035_noflex`. We estimated that changing all steps that write into the `grid.egon_etrago_*` tables is too time-consuming do we decided to add a postprocessing step instead.

The questions that arise are: what needs to be changed for the several sectors/flex? Can the data from the existing scenarios just be duplicated, scenario name changed and some unnecessary components be dropped to create a noflex scenario? (e.g. storages for DSM) For many components this seems possible. If that's not possible for a flex, the eTraGo tables might need to be filled beforehand in the respective tasks.

@ClaraBuettner @IlkaCu @CarlosEpia @AmeliaNadal @fwitte 
I'd like to ask you to add the flex you're responsible for, whether a no-flex scenario can derived from the default scenario via postprocessing of the data in `grid.egon_etrago_*`, and required changes:

- DSM (@ClaraBuettner): **yes** - 
Drop stores with carrier 'dsm' from grid.egon_etrago_store and grid.egon_etrago_store_t, 
links with carrier 'dsm' from grid.egon_etrago_link and grid.egon_etrago_link_t, 
buses with carrier 'dsm' from grid.egon_etrago_bus 
- rural heat (@ClaraBuettner): **yes** - 
Drop stores with carrier '"rural_heat_store" from grid.egon_etrago_store, 
 links with carrier ["rural_heat_store_charger" , "rural_heat_store_discharger"] from grid.egon_etrago_link,  
 buses with carrier 'rural_heat_store' from grid.egon_etrago_bus 
- central heat (@ClaraBuettner): **yes** - 
Drop stores with carrier '"central_heat_store" from grid.egon_etrago_store, 
 links with carrier ["central_heat_store_charger" , "central_heat_store_discharger"] from grid.egon_etrago_link,  
 buses with carrier 'central_heat_store' from grid.egon_etrago_bus 
- emobility MIT (@nesnoj): **no** - Components need to be parametrized differently. Will be handled in the MIT dataset. #821.
- DLR (@CarlosEpia ): Yes.
No changes are required. If not values are passed for a scenario, it is assumed that the electrical transmission capacity is static.
- H2 (@AmeliaNadal): **yes**
For for both scenarios: Drop buses with carrier 'H2_saltcavern' from grid.egon_etrago_bus,
 all links related to these buses (carriers 'power_to_H2', 'H2_to_power') from grid.egon_etrago_link,
 and stores with carrier 'H2_underground' from grid.egon_etrago_store.
Drop links with carrier 'H2_gridextension' from grid.egon_etrago_link for eGon100RE.

**Comment by nesnoj** [comment]
@AmeliaNadal @fwitte I kindly ask you to add your flex above.

**Comment by nesnoj** [comment]
I propose the following scenario names:

eGon2035: `eGon2035_noflex`
eGon100RE: `eGon100RE_noflex`

(which I will now use for the eMob part)

In case we will have more variations in different sectors, a more sophisticated name (e.g. [as in p-e-s](https://github.com/openego/pypsa-eur-sec/blob/40cd0447f73a605c71b39576430739bbfb595667/config.yaml#L18)) could be helpful.

**Comment by AmeliaNadal** [comment]
> * H2 (@AmeliaNadal): **yes**
>       For for both scenarios: Drop buses with carrier 'H2_saltcavern' from grid.egon_etrago_bus,
>       all links related to these buses (carriers 'power_to_H2', 'H2_to_power', 'H2_ind_load') from grid.egon_etrago_link,
>       and stores with carrier 'H2_underground' from grid.egon_etrago_store.
>       Drop links with carrier 'H2_gridextension' from grid.egon_etrago_link for eGon100RE.

The links with carriers 'H2_feedin' and 'H2_to_power' (not only the ones connected to H2_saltcavern buses) could also be removed in order to limit the electricity-H2 flexibility. However, it is contra intuitive that the system build these components. Therefore we would remove them only if we state that the optimization build them largely.

**Comment by nesnoj** [comment]
> I propose the following scenario names:
> 
> eGon2035: `eGon2035_noflex`
> eGon100RE: `eGon100RE_noflex`

I renamed the scenarios in #922 to:

eGon2035: `eGon2035_lowflex`
eGon100RE: `eGon100RE_lowflex`

**Comment by AmeliaNadal** [comment]
As discuss today, the H2 steel tank storages (storages with carrier 'H2_overground') could also be removed if this flexibility is used in a huge proportion to compensate the absence of the saltcavern storages.

**Comment by ClaraBuettner** [comment]
If I'm not mistaken `H2_to_power` and `power_ro_H2` links connecting `H2 grid` to `AC` should be kept, only the ones connection `H2_saltcaverns` should be deleted. Looking at the result of the current script, all links with these carriers are dropped. Is this correct?

**Comment by IlkaCu** [comment]
> If I'm not mistaken `H2_to_power` and `power_ro_H2` links connecting `H2 grid` to `AC` should be kept, only the ones connection `H2_saltcaverns` should be deleted. Looking at the result of the current script, all links with these carriers are dropped. Is this correct?
> 
> To exclude dynamic line rating, s_max_pu timeseries of lines shouldn't be copied, right @CarlosEpia?

Please also update the first comment in this issue, in case the information there is not up to date.

**Comment by IlkaCu** [comment]
> If I'm not mistaken `H2_to_power` and `power_ro_H2` links connecting `H2 grid` to `AC` should be kept, only the ones connection `H2_saltcaverns` should be deleted. Looking at the result of the current script, all links with these carriers are dropped. Is this correct?

It seems that I just didn't read the description well enough. :roll_eyes: 
I will change the code accordingly.

**Comment by CarlosEpia** [comment]
> > If I'm not mistaken `H2_to_power` and `power_ro_H2` links connecting `H2 grid` to `AC` should be kept, only the ones connection `H2_saltcaverns` should be deleted. Looking at the result of the current script, all links with these carriers are dropped. Is this correct?
> > To exclude dynamic line rating, s_max_pu timeseries of lines shouldn't be copied, right @CarlosEpia?
> 
> Please also update the first comment in this issue, in case the information there is not up to date.

Right. In that way, the capacity of the line will be set to its nominal value for every snapshot.
