### ISSUE TITLE
The weekend run might not get started this weekend

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#839]
During this week a task got added which takes a pretty long time. Together with the fact that there already is a task present which takes a very long time, the weekend run does not finish during the course of one week. Since this means that the run didn't fully finish for a few weeks now, we thought that it would be a good idea to not stop the run and start it anew this Friday in order to let new code in later tasks also get some testing.
If you have a particular reason to veto this decision, please drop a comment below or write me (@gnn) an email. You don't have to state your reason, simply saying that it's important for you that the run gets started anew this Friday would be enough. :)

**Comment by nesnoj** [comment]
Accepted! ;)
