### ISSUE TITLE
Starting the webserver

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#84]
Because we do not have Docker at the DLR, we try to avoid the task initdb and connect only to our local database and we create for that a test branch: https://github.com/openego/eGon-data/tree/feature/dlr_tests. By running the command `egon-data serve`, I obtain:
- **the attached  logfile** (normally pipeline.py.log but extension name changed, located in eGon-data\src\egon\data\airflow\logs\scheduler\latest)
[pipeline.txt](https://github.com/openego/eGon-data/files/5787727/pipeline.txt)

- **In the terminal** the following output (and error messages):

> The 'initdb' command is deprecated and removed in Airflow 2.0, please use 'db init' instead
> DB: sqlite:////home/nada_am/AN_eGon/eGon_code/eGon-data/git_eGon-data_dlr_tests/eGon-data/src/egon/data/airflow/airflow.db
> [2021-01-08 15:17:16,346] {db.py:378} INFO - Creating tables
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> WARNI [airflow.models.crypto] empty cryptography key - values will not be stored encrypted.
> print_test_0
> print_test_1
> Done.
>  ____    |__( )_________  __/__  /________      __
> ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
> ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
>  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
> /home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/site-packages/airflow/settings.py:395: DeprecationWarning: `session_lifetime_days` option from `[webserver]` section has been renamed to `session_lifetime_minutes`. The new option allows to configure session lifetime in minutes. The `force_log_out_after` option has been removed from `[webserver]` section. Please update your configuration.
>   warnings.warn(
> [2021-01-08 15:17:29,339] {__init__.py:50} INFO - Using executor SequentialExecutor
> [2021-01-08 15:17:29,339] {dagbag.py:417} INFO - Filling up the DagBag from /home/nada_am/AN_eGon/eGon_code/eGon-data/git_eGon-data_dlr_tests/eGon-data/src/egon/data/airflow/dags
> print_test_0
> print_test_1
> Running the Gunicorn Server with:
> Workers: 4 sync
> Host: 0.0.0.0:8080
> Timeout: 120
> Logfiles: - -            
> [2021-01-08 15:17:35 +0100] [20404] [INFO] Starting gunicorn 19.10.0
> [2021-01-08 15:17:35 +0100] [20404] [ERROR] Connection in use: ('0.0.0.0', 8080)
> [2021-01-08 15:17:35 +0100] [20404] [ERROR] Retrying in 1 second.
> [2021-01-08 15:17:36 +0100] [20404] [ERROR] Connection in use: ('0.0.0.0', 8080)
> [2021-01-08 15:17:36 +0100] [20404] [ERROR] Retrying in 1 second.
> [2021-01-08 15:17:37 +0100] [20404] [ERROR] Connection in use: ('0.0.0.0', 8080)
> [2021-01-08 15:17:37 +0100] [20404] [ERROR] Retrying in 1 second.
> [2021-01-08 15:17:38 +0100] [20404] [ERROR] Connection in use: ('0.0.0.0', 8080)
> [2021-01-08 15:17:38 +0100] [20404] [ERROR] Retrying in 1 second.
> [2021-01-08 15:17:39 +0100] [20404] [ERROR] Connection in use: ('0.0.0.0', 8080)
> [2021-01-08 15:17:39 +0100] [20404] [ERROR] Retrying in 1 second.
> [2021-01-08 15:17:40 +0100] [20404] [ERROR] Can't connect to ('0.0.0.0', 8080)
> [2021-01-08 15:19:31,347] {cli.py:1045} ERROR - No response from gunicorn master within 120 seconds
> [2021-01-08 15:19:31,348] {cli.py:1046} ERROR - Shutting down webserver

- **Opening the browser at localhost:8080**, the following message:

> Ooops.
> 
> 
>                           ____/ (  (    )   )  \___
>                          /( (  (  )   _    ))  )   )\
>                        ((     (   )(    )  )   (   )  )
>                      ((/  ( _(   )   (   _) ) (  () )  )
>                     ( (  ( (_)   ((    (   )  .((_ ) .  )_
>                    ( (  )    (      (  )    )   ) . ) (   )
>                   (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
>                   ( (  (   ) (  )   (  ))     ) _)(   )  )  )
>                  ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
>                   (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
>                  ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
>                   ((  (   )(    (     _    )   _) _(_ (  (_ )
>                    (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
>                    ((__)        \\||lll|l||///          \_))
>                             (   /(/ (  )  ) )\   )
>                           (    ( ( ( | | ) ) )\   )
>                            (   /(| / ( )) ) ) )) )
>                          (     ( ((((_(|)_)))))     )
>                           (      ||\(|(|)|/||     )
>                         (        |(||(||)||||        )
>                           (     //|/l|||)|\\ \     )
>                         (/ / //  /|//||||\\  \ \  \ _)
> Node: torch.esy.ve.dlr
> Traceback (most recent call last):
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
>     return fn()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
>     rec = pool._do_get()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
>     return self._create_connection()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
>     return _ConnectionRecord(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
>     self.__connect(first_connect_check=True)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
>     pool.logger.debug("Error on connect(): %s", e)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
>     with_traceback=exc_tb,
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
>     connection = pool._invoke_creator(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
>     return self.dbapi.connect(*cargs, **cparams)
> sqlite3.OperationalError: unable to open database file
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
>     return self._run_view(f, *args, **kwargs)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
>     return fn(self, *args, **kwargs)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/flask_login/utils.py", line 258, in decorated_view
>     return func(*args, **kwargs)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
>     return func(*args, **kwargs)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/airflow/www/views.py", line 2306, in index
>     dags = query.offset(start).limit(dags_per_page).all()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3373, in all
>     return list(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
>     return self._execute_and_instances(context)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
>     querycontext, self._connection_from_session, close_with_result=True
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
>     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
>     conn = self.session.connection(**kw)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
>     execution_options=execution_options,
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
>     engine, execution_options
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
>     conn = bind._contextual_connect()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
>     self._wrap_pool_connect(self.pool.connect, None),
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
>     e, dialect, self
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
>     return fn()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
>     rec = pool._do_get()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
>     return self._create_connection()
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
>     return _ConnectionRecord(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
>     self.__connect(first_connect_check=True)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
>     pool.logger.debug("Error on connect(): %s", e)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
>     with_traceback=exc_tb,
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
>     connection = pool._invoke_creator(self)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/home/nada_am/anaconda3/envs/egondata_env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
>     return self.dbapi.connect(*cargs, **cparams)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
> (Background on this error at: http://sqlalche.me/e/13/e3q8)

What could I do to solve that and start the webserver please?

**Comment by gnn** [comment]
Looks like that's a problem with Apache Airflow version 2.0. Does the same issue occur if you set the `"apache-airflow"` dependency in "setup.py" to `"apache-airflow<2.0"` and reinstall with `pip install -U -e .`?

**Comment by gnn** [comment]
I also finally implemented a solution which should allow you to work without Docker. Check out the code in PR #85. Setting things up to bypass docker is explained in the [CHANGELOG](https://github.com/openego/eGon-data/blob/003dde53f8942a483b89c2879b4fc41812e8a7e4/CHANGELOG.rst).

**Comment by AmeliaNadal** [comment]
> 
> 
> Looks like that's a problem with Apache Airflow version 2.0. Does the same issue occur if you set the `"apache-airflow"` dependency in "setup.py" to `"apache-airflow<2.0"` and reinstall with `pip install -U -e .`?

Yes, I'm already working with Apache-airflow version 1.10.14.

**Comment by gnn** [comment]
> Yes, I'm already working with Apache-airflow version 1.10.14.

Ah, OK. I see now. I got confused by the mention of Airflow 2.0 on the top of the log. But that's just a deprecation warning for the "future". The error seems to be that the server can't access the SQLite database which apache-airflow uses for it't internal data.
This will probably not solve the issue, but could you downgrade to `apache-airflow==1.10.12` via `pip install -U "apache-airflow==1.10.12"` and try again?

**Comment by gnn** [comment]
OK. Took a while to figure that one out. The problem was that there was still a server listening on port 8080, which is why Airflow wasn't able to start another one listening on the same port. In hindsight, it's pretty obvious judging by the fact that the Airflow command line error message was `Connection in use` and also by the fact that the error message in the browser window was always referring to the same Python 3.6 environment, namely the environment of the already running server, regardless of the environment in which `airflow` was actually running.
I'll add this to the troubleshooting section and close this issue afterwards.
