### ISSUE TITLE
Create wind_offshore generators for the eGon100RE scenario

### ISSUE THREAD

**Issue by CarlosEpia** [openego/eGon-data#868]
Wind_offshore generators must be created for the scenario eGon100RE. The wind farms given by NEP are used and then escalated to match the scenario capacity in the table supply.egon_scenario_capacities.

**Comment by IlkaCu** [comment]
Was this tested successfully on CI? I couldn't find a corresponding PR.

**Comment by CarlosEpia** [comment]
> Was this tested successfully on CI? I couldn't find a corresponding PR.

Hi Ilka. This was already tested in CI and merged into dev. https://github.com/openego/eGon-data/pull/869#issue-1342803202

**Comment by IlkaCu** [comment]
And reviewed by myself... ;-) 
I will therefore close this issue

**Comment by IlkaCu** [comment]
I took a closer look and it seems that features from branch features/#868-create-wind_offshore-generators-for-the-eGon100RE-scenario didn't make it to dev branch. Therefore I reopened the ticket.
