### ISSUE TITLE
Use own load buses for gas loads instead directly attaching them to grid

### ISSUE THREAD

**Issue by fwitte** [openego/eGon-data#871]
Since all gas loads (H2 and CH4) are on NUTS3 level, we cannot really say, where the gas load is. To make desaggregation easier after optimization and to make clearer what the data model actually represents, for every load an own bus will be created per NUTS3.

Then for H2 and CH4 the load bus will be connected to

- all grid buses inside that NUTS3
- the nearest H2 or CH4 grid bus outside of the NUTS3 if the NUTS3 has grid buses

and for H2 the load bus will also be connected to

- all H2 cavern buses inside that NUTS3.

**Comment by IlkaCu** [comment]
I just stumbled over this issue. Is it an idea or are you already sure you want and need to implement it like this?
I would suggest to discuss it in one of our next meetings, as this would require some changes in the modeling concept and egon-data.

**Comment by fwitte** [comment]
I did not yet start to implement it, but I do think some of the decisions made earlier in the project (by me) were unreasonable or based on assumptions, which I later learned were incorrect. And it would also compliment with the integration of the H2 loads for mobility @khelfen will start to work on (do you?). I can join you on Wednesday.

**Comment by khelfen** [comment]
@fwitte for now I only implemented the part that determines the H2 demand from HGV traffic per NUTS3 region. Next would be to map the demand to H2 buses like you said. Did you already start with making your changes? Should we have a call?

**Comment by fwitte** [comment]
I did not, we can talk tomorrow, if you have time.
