### ISSUE TITLE
Task `hvmv_substation` fails due to missing table

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#872]
2 clean runs of `continuous-integration/run-everything-over-the-weekend-2022-06-10` (head: 740f279f4bc457666bd568780382b35768661fb9) for DE lead to the same error:

```
psycopg2.errors.UndefinedTable: relation "grid.egon_hvmv_substation" does not exist
```
Apparently, you did some renaming/changed import of the HV/MV substation table in #860.
The table should have been created in [osmtgmod substation](https://github.com/openego/eGon-data/blob/b6afe88eaa8d7a0cb7538a896945e491f4d5f33b/src/egon/data/datasets/osmtgmod/substation.py#L91) but `èxtract()` may never been called? @ClaraBuettner

**Comment by nesnoj** [comment]
BTW, `grid.egon_ehv_substation` is not created either

**Comment by ClaraBuettner** [comment]
Sorry, I forgot to change the table name in two lines of the hvmv-substation script, this should be fixed in https://github.com/openego/eGon-data/pull/860/commits/b2376c2c061d750f05d0b0cf00239d5cd28c4edb.

**Comment by ClaraBuettner** [comment]
> BTW, `grid.egon_ehv_substation` is not created either

These tables are now created in the osmtgmod dataset. The substation-dataset creates and fills the `grid.egon_hvmv_transfer_buses` and `grid.egon_ehv_transfer_buses` tables. Before these changes, the tables were filled in one dataset and updated by another one which resulted into problems when one of them was skipped due to versioning.

**Comment by nesnoj** [comment]
Thanks for the quick fix, I'll give it another try

**Comment by nesnoj** [comment]
Seems to work out

**Comment by nesnoj** [comment]
Now I'm getting `psycopg2.errors.UndefinedTable: table "egon_mv_grid_district" does not exist` in the task `mv_grid_districts.define-mv-grid-districts` (HEAD: 5e0ab3b2c0dae33c51172fde282602eda13a2443).

It is raised in [this line](https://github.com/openego/eGon-data/blob/9651a39ed1123d6fd104d221c059b6f4469c15d3/src/egon/data/datasets/mv_grid_districts.py#L567-L571). @ClaraBuettner you added this drop statement recently. It does not check if the table actually exists. To my mind it can be removed as in L572 there's already a drop statement for this table (which, btw, checks for existence).

**Comment by nesnoj** [comment]
After removing [those lines](https://github.com/openego/eGon-data/blob/9651a39ed1123d6fd104d221c059b6f4469c15d3/src/egon/data/datasets/mv_grid_districts.py#L567-L571) the task finishes successfully

**Comment by ClaraBuettner** [comment]
I changed this in #859. Dropping without `CASCADE` resulted into problems because the eMobility-dataset has a ForeignKey to the mv grids. 
I can add `IF EXISTS` to the drop statement.

**Comment by nesnoj** [comment]
I see, yes that would be nice if you added `IF EXISTS`.

And could you please delete the [ORM drop statement](https://github.com/openego/eGon-data/blob/9651a39ed1123d6fd104d221c059b6f4469c15d3/src/egon/data/datasets/mv_grid_districts.py#L572) then?

PS: It would be also possible to keep the ORM statement and define the cascade in the foreign key relationship but I had troubles in the past and don't wanna mess around with this again.

**Comment by ClaraBuettner** [comment]
> I see, yes that would be nice if you added `IF EXISTS`.
> 
> And could you please delete the [ORM drop statement](https://github.com/openego/eGon-data/blob/9651a39ed1123d6fd104d221c059b6f4469c15d3/src/egon/data/datasets/mv_grid_districts.py#L572) then?
> 
Done in 8cab0bf32ecf852265fefd802e467298e0498de9

**Comment by nesnoj** [comment]
thx

**Comment by nesnoj** [comment]
Just a sec, you also dropped `MvGridDistricts.__table__.create(bind=engine)`, please keep this ;)

**Comment by ClaraBuettner** [comment]
> Just a sec, you also dropped `MvGridDistricts.__table__.create(bind=engine)`, please keep this ;)

Sorry for my confusion, I fixed it again...
