### ISSUE TITLE
Heat pump desaggregation to buildings

### ISSUE THREAD

**Issue by birgits** [openego/eGon-data#903]
Heat pump capacity per MV grid needs to be desaggregated to specific buildings. This is then also used to create heat demand time series of buildings with heat pumps and for buildings with other decentral heating technologies for eTraGo.

**Comment by nailend** [comment]
I am currently running into the following ERROR as we querry every building heat profile (~2000 depending on the MVGD) by its own. Probably the best solution would be generate all profiles in one MVGD at once. Is it easy to adapt the query? @ClaraBuettner 
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 59776 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Ticket expired
connection to server at "127.0.0.1", port 59776 failed: FATAL:  sorry, too many clients already
```

**Comment by nesnoj** [comment]
> I am currently running into the following ERROR as we querry every building heat profile (~2000 depending on the MVGD) by its own.
> 
> ```
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 59776 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Ticket expired
> connection to server at "127.0.0.1", port 59776 failed: FATAL:  sorry, too many clients already
> ```
> 
> Probably the best solution would be generate all profiles in one MVGD at once. Is it easy to adapt the query? @ClaraBuettner 

I'm quite familiar with this error from the eMob side #799. If you tell me via RC which instance is affected, I can fix the docker config accordingly.

> This would anyways take a way to long for whole germany (10min per MVGD > 633h).

And I guess we cannot do much about the duration (cf. @ClaraBuettner mail).. I stopped it after 146h on DE3 (cf. https://github.com/openego/eGon-data/issues/377#issuecomment-1246907338)
