### ISSUE TITLE
Task `heat_demand_timeseries.HTS.demand-profile-generator` fails on dev

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#904]
The desired `dev` stable run started on Wednesday on our server failed at `heat_demand_timeseries.HTS.demand-profile-generator`:
```
CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: None`
```

Full log:
[egon-data-processing-pipeline_heat_demand_timeseries.HTS.demand-profile-generator_2022-08-31T10_22_15.780613+00_00_2.log](https://github.com/openego/eGon-data/files/9488234/egon-data-processing-pipeline_heat_demand_timeseries.HTS.demand-profile-generator_2022-08-31T10_22_15.780613%2B00_00_2.log)

geopandas==0.10.2
HEAD: 22ee7181ac1c10e23533814034b95bcfd4100e30

**Comment by ClaraBuettner** [comment]
I'm not sure if the CRS mismatch created the error. It had also been there when the task finished successful. The last line of the log looks more like the RAM memory was full.

**Comment by nesnoj** [comment]
> I'm not sure if the CRS mismatch created the error. It had also been there when the task finished successful. The last line of the log looks more like the RAM memory was full.

Yes, the different execution times before the error and `SIGKILL` speak for full memory. Also, it says `DataFrame is highly fragmented.`. I could try to track the mem usage but doesn't it make sense to just reduce in intermediate steps? Maybe using [this function](https://github.com/openego/eGon-data/blob/22ee7181ac1c10e23533814034b95bcfd4100e30/src/egon/data/datasets/emobility/motorized_individual_travel/helpers.py#L137) I've been using in eMob MIT?

**Comment by nesnoj** [comment]
It used at least 150 GB of memory - then `SIGKILL` again at a certain point of time..
I propose to focus on the CI problems and skip this overhauled `dev` task.

**Comment by nesnoj** [comment]
Now running with merged #870

**Comment by ClaraBuettner** [comment]
#870 was merged, can we close this issue?

**Comment by nesnoj** [comment]
yepp
