### ISSUE TITLE
Task `heat_demand_timeseries.export-etrago-cts-heat-profiles` stalls

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#916]
Run info: [CI | DE | Clean run | HEAD: 83304cacfd6cb15a052a4310341af86a187c3873]
See instance DE3

Hangs at:
```
[2022-09-06 12:19:42,247] {temporal.py:792} INFO - Working on state: TH.
[2022-09-06 12:19:46,102] {temporal.py:634} INFO - ... creating state-specific load-profiles
```

**Comment by nesnoj** [comment]
Please harmonize the heat profile creation @nailend @ClaraBuettner

**Comment by nesnoj** [comment]
> Please harmonize the heat profile creation @nailend @ClaraBuettner

As the DR data is obtained by `heat_demand_timeseries.individual-heating-per-mv-grid` as well as in `heat_demand_timeseries.export-etrago-cts-heat-profiles`

**Comment by nailend** [comment]
This was solved by [this](https://github.com/openego/eGon-data/pull/870/commits/3060124d129f4cd5e01700fe23a6b2ba1d6012bf0

**Comment by nesnoj** [comment]
thx
