### ISSUE TITLE
Inconsistency in marginal costs for link components

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#942]
Marginal costs are not set consistently for link components. Some components in foreign components have marginal costs assigned for the eGon100RE scenario, but not inside Germany or in scenario eGon2035. 
This should be checked and adjusted.

**Comment by IlkaCu** [comment]
Link components with marginal_costs = 0 in `eGon100RE` are 
- [ ] power_to_H2 (components outside Germany got marginal costs assigned)
- [ ] CH4 (components outside Germany got marginal costs assigned)
- [ ] H2_gridextension
- [ ] H2_ind_load
- [ ] dsm
- [ ] H2_to_CH4 (components outside Germany got marginal costs assigned)
- [ ] H2_retrofit (components outside Germany got marginal costs assigned)
- [ ] CH4_to_H2 (components outside Germany got marginal costs assigned)
- [ ] H2_to_power (components outside Germany got marginal costs assigned)

**Comment by IlkaCu** [comment]
Link components with marginal_costs = 0 in `eGon2035` are

- [ ] power_to_H2
- [ ] CH4
- [ ] rural_heat_store_discharger
- [ ] H2_ind_load
- [ ] dsm
- [ ] H2_to_CH4
- [ ] rural_heat_store_charger
- [ ] DC
- [ ] central_gas_boiler
- [ ] H2_feedin
- [ ] central_gas_CHP_heat
- [ ] central_heat_pump
- [ ] rural_heat_pump
- [ ] CH4_to_H2
- [ ] central_resistive_heater
- [ ] central_heat_store_discharger
- [ ] H2_to_power
- [ ] central_heat_store_charger
- [ ] rural_gas_boiler

**Comment by IlkaCu** [comment]
I converted the lists in the comments above into tables. @ClaraBuettner and @AmeliaNadal: Please add information whether the carriers need to get VOM as marginal costs assigned or not.

**Comment by ClaraBuettner** [comment]
I will create a branch for the links in heat sector.

**Comment by ClaraBuettner** [comment]
Besides, no store or storage_unit has any marginal cost. Is that intended?

**Comment by IlkaCu** [comment]
> Besides, no store or storage_unit has any marginal cost. Is that intended?

No, I will create an additional ticket for this issue.

**Comment by AmeliaNadal** [comment]
I verified in the sources documents that the mentionned (gas) components do not have associated VOM. From my perspective, this issue could be closed (when features/#942-add-vom-heat-sector is merged in dev).
