### ISSUE TITLE
Add voltage level for electricity building loads

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#955]
Please add the voltage level (new column: `voltage_level`) according to [our definitions](https://redmine.iks.cs.ovgu.de/oe/projects/ego-n/wiki/Definition_of_thresholds_for_voltage_level_assignment) to the buildings' peak load table `demand.egon_building_electricity_peak_loads`.
Either as postprocessing step or rather in the CTS task?

This had been done in various other tasks already, just search for "voltage_level".

Caveat: @nailend you distinguished by sector which makes it harder to obtain the actual peak load per building (and to assign `voltage_level` to a certain row)... :-/

Any straightforward way? If a full recalculation/redesign of the table is necessary, it might be easier to just sum up the two peak loads (still, I wouldn't know which row the voltage should be assigned to..).

**Comment by nailend** [comment]
To calculate the actual peak demand would mean to aggregate the various household profiles for residential and the cts for all buildings with both `residential` and `cts` in one building (530,000 buildings). This can be done as a postprocessing task but might take some pipeline time. I would simply append the aggregated peak demand to the table with `sector='both`. This way we would already have a row dedicated to adding the voltage level.

What is the "voltage-level" needed for? The residential peak load is currently not used in ding0.

**Comment by birgits** [comment]
Decision: Add new column "voltage_level". Append for each building a new row with CTS+residential peak load and only add voltage level for those rows with CTS+residential.
