### ISSUE TITLE
Move tested features from `CI` to `dev`

### ISSUE THREAD

**Issue by gnn** [openego/eGon-data#967]
As the current CI has been through a lot, we decided to start the next clean run from a new CI, created fresh from `dev`. In order to do this, the features which are under testing in the current CI and passed the most recent clean run have to be merged into `dev` so that we can start the new CI with a minimal need for initial feature merges. Please use the list below to indicate that you're done merging your tested features into dev:

  - [x] @AmeliaNadal
  - [x] @CarlosEpia 
  - [x] @ClaraBuettner 
  - [x] @IlkaCu 
  - [x] @fwitte 
  - [x] @nesnoj 
  - [x] @khelfen 
  - [x] @nailend 

Since I don't know the names of everybody who still works on the workflow, I intentionally named only the people which I knew of the top of my head. If you know of anybody else who should chime in and be noted with whether all his changes are moved to `dev`, please edit this post to include his name in the list. Checking the box next to your name then has the following meanings:

  - All my features which were tested successfully a full run have been merged into `dev`.
  - I don't know anybody which should be in this list who isn't already in it.

Once all boxes are checked, I'll create a fresh CI from `dev` and close this issue.

We would like for this to be done by Friday or the beginning of next week.

**Comment by khelfen** [comment]
Done by merging #943 and #968

**Comment by gnn** [comment]
Since everybody merged his tested features into `dev`, I created a new [CI][0] based on commit 61186e7f85d64aa152adc2313278563ece7b8747. The next question would be, whether we want to test this version in a clean run first or whether we want to go ahead and merge the current work in progress into the new CI and run that as soon as possible.

Regardless of what we decide, you can already go ahead and merge those commits which are on the old CI but not in `dev` into the new CI. Here's another list:

  - [ ] @AmeliaNadal
  - [ ] @CarlosEpia 
  - [ ] @ClaraBuettner 
  - [ ] @IlkaCu 
  - [ ] @fwitte 
  - [ ] @nailend 
  - [ ] @nesnoj 
  - [ ] @khelfen 

Please tick the box next to your name to indicate that all your remaining work in progress made it into [`continuous-integration/run-everything-over-the-weekend-2022-10-10`][0]. Once all boxes are ticked, I'll delete the old CI. Again, please also fill in any names which I forgot.

[0]: https://github.com/openego/eGon-data/tree/continuous-integration/run-everything-over-the-weekend-2022-10-10

**Comment by khelfen** [comment]
Can the old [`continuous-integration/run-everything-over-the-weekend-2022-06-10`](https://github.com/openego/eGon-data/tree/continuous-integration/run-everything-over-the-weekend-2022-06-10) be deleted?

**Comment by nesnoj** [comment]
> Can the old [`continuous-integration/run-everything-over-the-weekend-2022-06-10`](https://github.com/openego/eGon-data/tree/continuous-integration/run-everything-over-the-weekend-2022-06-10) be deleted?

Yes, done.
