### ISSUE TITLE
Import small input data sets 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#97]
Some of our input data needs to be imported to our workflow from (csv) files. 
Perspectively we would like to collect all input files in a zenodo repository, which will then be accessed from the egon-data workflow. 
On an interim basis we will include this small data sets directly in the Github repository until we have a almost final collection of data sets. 
Please list the data sets you are planning to integrate, which are not publicly available elsewhere, into the workflow: 

- WZ2008 definitions
-  ...

**Comment by gplssm** [comment]
Here's an example how I used pynodo to download data from zenodo: https://github.com/windnode/WindNODE_ABW/blob/badf17b680c6982d04cef3d90804088dcc60097c/docs/conf.py#L25-L45

**Comment by IlkaCu** [comment]
A zenodo repository was set up (https://zenodo.org/record/4896527#.YPAFtzpCT_E) and the download was integrated into our workflow.
