### ISSUE TITLE
Include information on table metadata in documentation

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#98]
Information on the creation of metadata and links to corresponding templates needs to be added to our documentation.

Beschreibung der einzelnen Felder: 
https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v140/metadata_key_description.md

Beispielstring: 
https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v140/example.json

Schema: 
https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v140/schema.json

**Comment by gplssm** [comment]
There is a new version: https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v141

**Comment by nesnoj** [comment]
Done in b8b91223995d705774515f954064af7ab60ef888
